import type { NextConfig } from "next";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { toNextConfigRedirects } from "./src/services/legacy-url-migration/redirect-plan/load-redirects";

const projectRoot = path.dirname(fileURLToPath(import.meta.url));

const nextConfig: NextConfig = {
  // Canonical URLs use trailing slashes (matches intended IA and WordPress heritage).
  trailingSlash: true,
  // Unblock production deploys while catalogue/schema drift is cleaned up.
  // Prefer fixing types over keeping this; do not treat as a permanent policy.
  typescript: {
    ignoreBuildErrors: true,
  },
  // Dev-only: allow 127.0.0.1 as well as localhost so browser Origin checks
  // don't 403 /_next/static chunks when the app is opened via the IP loopback.
  allowedDevOrigins: ["127.0.0.1"],
  images: {
    // Avoid 308 redirects on every optimized image when trailingSlash is true.
    path: "/_next/image/",
    // Keep guide PNGs renderable inline in <img> (default attachment can blank covers).
    contentDispositionType: "inline",
    // Prefer modern formats for LCP/media weight (Next image optimizer).
    formats: ["image/avif", "image/webp"],
    // Next 16 defaults to [75] only; allow sharper heroes for text-heavy diagrams.
    qualities: [75, 90],
    // Heroes display ~720–1200 CSS px; avoid shipping 4k decode by default.
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 60 * 60 * 24 * 30,
    remotePatterns: [
      {
        protocol: "https",
        hostname: "kxxfqtgoxjcif3x5.public.blob.vercel-storage.com",
      },
    ],
  },
  // Heavy export libs are dynamically imported on user action only.
  serverExternalPackages: ["jspdf", "xlsx"],
  experimental: {
    // lucide-react is optimized by default; keep zod tree-shakeable for server data.
    optimizePackageImports: ["zod"],
  },
  turbopack: {
    root: projectRoot,
  },
  /**
   * Legacy + in-app permanent redirects.
   * Source of truth: config/legacy-redirects.json (generated by RedirectPlanGenerator).
   * Do not hand-edit next.config redirect lists — regenerate via npm run migration:redirects.
   */
  async redirects() {
    return toNextConfigRedirects();
  },
  /**
   * Site media packs live in Vercel Blob (not in the Git deploy).
   * Paths stay /guides/… etc.; only Vercel production/preview proxies to Blob.
   * Local `next dev` always serves from public/ — keep BLOB_* in .env.local for
   * upload scripts without enabling rewrites. Override with BLOB_MEDIA_REWRITES=1.
   */
  async rewrites() {
    const blob = (process.env.BLOB_PUBLIC_HOST ?? "").replace(/\/$/, "");
    const useBlobRewrites =
      Boolean(blob) &&
      (process.env.VERCEL === "1" || process.env.BLOB_MEDIA_REWRITES === "1");
    if (!useBlobRewrites) return [];
    const folders = [
      "guides",
      "software",
      "capabilities",
      "use-cases",
      "vendor-ui",
      "industries",
      "features",
      "resources",
      "requirements",
      "for",
    ];
    return folders.map((folder) => ({
      source: `/${folder}/:path*`,
      destination: `${blob}/${folder}/:path*`,
    }));
  },
  async headers() {
    return [
      {
        source: "/og/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=86400, stale-while-revalidate=604800",
          },
        ],
      },
      {
        source: "/brands/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=604800, stale-while-revalidate=2592000",
          },
        ],
      },
      {
        source: "/api/search/suggest",
        headers: [
          {
            key: "Cache-Control",
            value:
              "public, max-age=3600, stale-while-revalidate=86400, s-maxage=3600",
          },
        ],
      },
      {
        source: "/sitemap.xml",
        headers: [
          {
            key: "Cache-Control",
            value:
              "public, max-age=3600, stale-while-revalidate=86400, s-maxage=86400",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
