import type { NextConfig } from "next";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { toNextConfigRedirects } from "./src/services/legacy-url-migration/redirect-plan/load-redirects";
import { blobMediaFileRewrites } from "./src/lib/media/blob-rewrites";

const projectRoot = path.dirname(fileURLToPath(import.meta.url));

const SOFTWARE_TAB_SLUGS = [
  "features",
  "pricing",
  "guides",
  "use-cases",
  "comparisons",
  "alternatives",
  "evidence",
  "methodology",
  "faq",
] as const;

function softwareTabRedirects() {
  return SOFTWARE_TAB_SLUGS.flatMap((tab) => {
    const destination = `/software/:slug/?tab=${tab}`;
    return [
      { source: `/software/:slug/${tab}`, destination, permanent: true },
      { source: `/software/:slug/${tab}/`, destination, permanent: true },
    ];
  });
}

function comparisonReverseRedirects() {
  const file = path.join(projectRoot, "config/comparison-reverse-redirects.json");
  if (!fs.existsSync(file)) return [];
  return JSON.parse(fs.readFileSync(file, "utf8")) as Array<{
    source: string;
    destination: string;
    permanent: boolean;
  }>;
}

const nextConfig: NextConfig = {
  // Canonical URLs use trailing slashes (matches intended IA and WordPress heritage).
  trailingSlash: true,
  // Large static surface (~13k pages). Default 60s page timeout fails under
  // contended workers on Vercel / local — raise so retries are not needed.
  staticPageGenerationTimeout: 180,
  // Standalone `npm run typecheck` is the gate (see engineering-quality CI).
  // Keep Next build-time typecheck off for now so deploy stays fast/stable on
  // the large static surface; do not treat this as permission to regress types.
  typescript: {
    ignoreBuildErrors: true,
  },
  // Dev-only: allow 127.0.0.1 as well as localhost so browser Origin checks
  // don't 403 /_next/static chunks when the app is opened via the IP loopback.
  allowedDevOrigins: ["127.0.0.1"],
  images: {
    // Avoid 308 redirects on every optimized image when trailingSlash is true.
    path: "/_next/image/",
    // Keep guide PNGs renderable inline in <img> (default attachment can blank covers).
    contentDispositionType: "inline",
    // Prefer modern formats for LCP/media weight (Next image optimizer).
    formats: ["image/avif", "image/webp"],
    // Next 16 defaults to [75] only; allow sharper heroes for text-heavy diagrams.
    qualities: [75, 90],
    // Heroes display ~720–1200 CSS px; avoid shipping 4k decode by default.
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 60 * 60 * 24 * 30,
    remotePatterns: [
      {
        protocol: "https",
        hostname: "kxxfqtgoxjcif3x5.public.blob.vercel-storage.com",
      },
    ],
  },
  // Heavy export libs are dynamically imported on user action only.
  serverExternalPackages: ["jspdf", "xlsx"],
  experimental: {
    // lucide-react is optimized by default; keep zod tree-shakeable for server data.
    optimizePackageImports: ["zod"],
  },
  turbopack: {
    root: projectRoot,
  },
  /**
   * Legacy + in-app permanent redirects.
   * Source of truth: config/legacy-redirects.json (generated by RedirectPlanGenerator).
   * Do not hand-edit next.config redirect lists — regenerate via npm run migration:redirects.
   */
  async redirects() {
    return [
      ...toNextConfigRedirects(),
      ...softwareTabRedirects(),
      ...comparisonReverseRedirects(),
    ];
  },
  /**
   * Site media packs live in Vercel Blob (not in the Git deploy).
   * Paths stay /guides/… etc.; only Vercel production/preview proxies to Blob.
   * Local `next dev` always serves from public/ — keep BLOB_* in .env.local for
   * upload scripts without enabling rewrites. Override with BLOB_MEDIA_REWRITES=1.
   */
  async rewrites() {
    const sitemapRewrites = [
      {
        // Pretty child sitemaps → route handler under /sitemaps/
        source: "/sitemap-:name.xml",
        destination: "/sitemaps/:name.xml",
      },
    ];

    const blob = (process.env.BLOB_PUBLIC_HOST ?? "").replace(/\/$/, "");
    const useBlobRewrites =
      Boolean(blob) &&
      (process.env.VERCEL === "1" || process.env.BLOB_MEDIA_REWRITES === "1");
    const media = useBlobRewrites ? blobMediaFileRewrites(blob) : [];
    return {
      beforeFiles: [],
      afterFiles: [...sitemapRewrites, ...media],
      fallback: media,
    };
  },
  async headers() {
    return [
      {
        source: "/og/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=86400, stale-while-revalidate=604800",
          },
        ],
      },
      {
        source: "/brands/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=604800, stale-while-revalidate=2592000",
          },
        ],
      },
      {
        source: "/api/search/:path*",
        headers: [
          {
            key: "Cache-Control",
            value:
              "public, max-age=3600, stale-while-revalidate=86400, s-maxage=3600",
          },
        ],
      },
      {
        source: "/sitemap.xml",
        headers: [
          {
            key: "Cache-Control",
            value:
              "public, max-age=3600, stale-while-revalidate=86400, s-maxage=86400",
          },
        ],
      },
      {
        source: "/sitemaps/:path*",
        headers: [
          {
            key: "Cache-Control",
            value:
              "public, max-age=3600, stale-while-revalidate=86400, s-maxage=86400",
          },
        ],
      },
      {
        source: "/sitemap-:name.xml",
        headers: [
          {
            key: "Cache-Control",
            value:
              "public, max-age=3600, stale-while-revalidate=86400, s-maxage=86400",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
