import type {
  SeoAgentContext,
  SeoAgentMeta,
  SeoAgentRunResult,
  SeoCheckResult,
  SeoFinding,
} from "./types";
import {
  agentReportHeader,
  formatFindingsSection,
  maybeWriteArchive,
  writeLatestReport,
} from "./report-io";

export type SeoAgentRunner = {
  meta: SeoAgentMeta;
  latestFilename: string;
  archiveBasename: string;
  analyze: (ctx: SeoAgentContext) => Promise<{
    checks: SeoCheckResult[];
    findings: SeoFinding[];
    summary: string;
  }>;
};

export async function runSeoAgent(
  runner: SeoAgentRunner,
  ctx: SeoAgentContext,
): Promise<SeoAgentRunResult> {
  const startedAt = ctx.now.toISOString();
  try {
    const { checks, findings, summary } = await runner.analyze(ctx);
    const finishedAt = new Date().toISOString();
    const completed = checks.filter((c) => c.status === "completed").length;
    const skipped = checks.filter((c) => c.status === "skipped").length;
    const failed = checks.filter((c) => c.status === "failed").length;

    const markdown = [
      agentReportHeader({
        title: `${runner.meta.name} report`,
        agentName: runner.meta.name,
        mode: ctx.mode,
        startedAt,
        finishedAt,
        checksCompleted: completed,
        checksSkipped: skipped,
        checksFailed: failed,
        findingCount: findings.length,
      }),
      `## Summary`,
      "",
      summary,
      "",
      `## Checks`,
      "",
      `| Check | Status | Reason |`,
      `| --- | --- | --- |`,
      ...checks.map(
        (c) =>
          `| \`${c.id}\` | ${c.status} | ${c.reason?.replace(/\|/g, "/") ?? "—"} |`,
      ),
      "",
      `## Findings`,
      "",
      formatFindingsSection(findings),
      "",
      `---`,
      "",
      `_Generated by \`${runner.meta.id}\` v${runner.meta.version}. No auto-fixes applied._`,
      "",
    ].join("\n");

    let reportPath: string | undefined;
    let archivePath: string | undefined;
    if (ctx.writeReports !== false) {
      reportPath = writeLatestReport(runner.latestFilename, markdown);
      archivePath = maybeWriteArchive(runner.archiveBasename, markdown, {
        mode: ctx.mode,
        now: ctx.now,
      });
    }

    return {
      meta: runner.meta,
      mode: ctx.mode,
      startedAt,
      finishedAt,
      checks,
      findings,
      summary,
      reportPath,
      archivePath,
    };
  } catch (err) {
    const finishedAt = new Date().toISOString();
    const message = err instanceof Error ? err.message : String(err);
    return {
      meta: runner.meta,
      mode: ctx.mode,
      startedAt,
      finishedAt,
      checks: [
        {
          id: "agent-run",
          status: "failed",
          reason: message,
        },
      ],
      findings: [],
      summary: `Agent failed: ${message}`,
      error: message,
    };
  }
}

export function applyForcedFailures(
  checks: SeoCheckResult[],
  ctx: SeoAgentContext,
): SeoCheckResult[] {
  const forced = ctx.fixtures?.forceCheckFailures ?? [];
  if (forced.length === 0) return checks;
  return checks.map((c) => {
    const hit = forced.find((f) => f.checkId === c.id);
    if (!hit) return c;
    return { ...c, status: "failed" as const, reason: hit.reason };
  });
}
