import type {
  GuideAssetAudit,
  GuideAssetMasterReport,
} from "@/domain/schemas/asset-discovery";
import { recommendationLevelLabel } from "../software-agent/rating";

export function formatGuideAssetMarkdown(audit: GuideAssetAudit): string {
  const lines: string[] = [];
  lines.push(`# ${audit.guideTitle} — Asset Opportunities`);
  lines.push("");
  lines.push(
    `> Generated by **GuideAssetDiscoveryAgent** \`${audit.agentVersion}\` — recommendations only. Does **not** edit guides.`,
  );
  lines.push("");
  lines.push(`- **Guide:** \`${audit.guideSlug}\``);
  lines.push(`- **Route:** ${audit.route}`);
  lines.push(`- **Kind:** ${audit.guideKind}`);
  lines.push(`- **Generated:** ${audit.generatedAt}`);
  lines.push(
    `- **Current visual quality:** **${audit.visualQuality}** — ${audit.visualQualityReason}`,
  );
  if (audit.contentQualityVisualScore !== undefined) {
    lines.push(
      `- **Content Quality visual-media-support:** ${audit.contentQualityVisualScore}/5`,
    );
  }
  if (audit.contentQualityIssueIds.length) {
    lines.push(
      `- **Resolves CQ issues:** ${audit.contentQualityIssueIds.map((id) => `\`${id}\``).join(", ")}`,
    );
  }
  lines.push("");

  lines.push("## Current visual / media state");
  lines.push("");
  lines.push(
    `| Figures | Hero | Video opps | Screenshot opps | Diagram opps | Official source opps | Original visuals |`,
  );
  lines.push(`| ---: | --- | ---: | ---: | ---: | ---: | ---: |`);
  lines.push(
    `| ${audit.currentFigureCount} | ${audit.hasHeroVisual ? "yes" : "no"} | ${audit.summary.videoOpportunities} | ${audit.summary.screenshotOpportunities} | ${audit.summary.diagramOpportunities} | ${audit.summary.officialSourceOpportunities} | ${audit.summary.originalVisualOpportunities} |`,
  );
  lines.push("");

  lines.push("## Section-by-section recommendations");
  lines.push("");
  for (const section of audit.sections) {
    lines.push(`### ${section.sectionTitle}`);
    lines.push("");
    lines.push(
      `- **Block:** ${section.blockType ?? "—"} · **Has teaching visual:** ${section.hasTeachingVisual ? "yes" : "no"} · **Visual would help:** ${section.visualWouldHelp ? "yes" : "no"}`,
    );
    lines.push(`- **Current:** ${section.current.join("; ") || "—"}`);
    lines.push("");
    if (!section.recommendations.length) {
      lines.push("_No material asset recommendation for this section._");
      lines.push("");
      continue;
    }
    let i = 1;
    for (const rec of section.recommendations) {
      lines.push(`#### Recommendation ${i++}: ${rec.title}`);
      lines.push("");
      lines.push(`- **Category:** ${rec.category}`);
      lines.push(
        `- **Priority:** ${recommendationLevelLabel(rec.recommendationLevel)}`,
      );
      lines.push(`- **Usage:** ${rec.usageRecommendation.toUpperCase().replace(/-/g, " ")}`);
      lines.push(`- **Placement:** ${rec.placementUse}`);
      lines.push(`- **Why:** ${rec.why}`);
      if (rec.productIds.length) {
        lines.push(`- **Products:** ${rec.productIds.join(", ")}`);
      }
      if (rec.supportingSourceHints.length) {
        lines.push(
          `- **Supporting sources:** ${rec.supportingSourceHints.join("; ")}`,
        );
      }
      if (rec.searchQueries.length) {
        lines.push(`- **Section search queries:**`);
        for (const q of rec.searchQueries) lines.push(`  - \`${q}\``);
      }
      if (rec.resolvesContentQualityIds.length) {
        lines.push(
          `- **Resolves:** ${rec.resolvesContentQualityIds.map((id) => `\`${id}\``).join(", ")}`,
        );
      }
      if (rec.requiresUsageReview) {
        lines.push(`- **Usage review required:** yes`);
      }
      lines.push("");
    }
  }

  lines.push("## Official assets found / recommended to seek");
  lines.push("");
  if (!audit.officialAssetsFound.length) {
    lines.push("_None prioritized — guide may be vendor-neutral._");
  } else {
    for (const a of audit.officialAssetsFound) lines.push(`- ${a}`);
  }
  lines.push("");

  lines.push("## Authoritative sources found / recommended");
  lines.push("");
  if (!audit.authoritativeSourcesFound.length) {
    lines.push("_None for this guide kind/sections._");
  } else {
    for (const a of audit.authoritativeSourcesFound) lines.push(`- ${a}`);
  }
  lines.push("");

  lines.push("## Original visual opportunities");
  lines.push("");
  for (const o of audit.originalVisualOpportunities) lines.push(`- ${o}`);
  lines.push("");

  lines.push("## Videos worth embedding");
  lines.push("");
  if (!audit.videosWorthEmbedding.length) {
    lines.push("_None at ADD NOW / STRONG with embed usage._");
  } else {
    for (const v of audit.videosWorthEmbedding) lines.push(`- ${v}`);
  }
  lines.push("");

  lines.push("## Images / screenshots / docs worth referencing");
  lines.push("");
  if (!audit.imagesWorthReferencing.length) {
    lines.push("_None flagged._");
  } else {
    for (const i of audit.imagesWorthReferencing) lines.push(`- ${i}`);
  }
  lines.push("");

  lines.push("## Assets requiring usage review");
  lines.push("");
  if (!audit.assetsRequiringUsageReview.length) {
    lines.push("_None._");
  } else {
    for (const a of audit.assetsRequiringUsageReview) lines.push(`- ${a}`);
  }
  lines.push("");

  lines.push("## Assets to avoid");
  lines.push("");
  for (const a of audit.assetsToAvoid) lines.push(`- ${a}`);
  lines.push("");

  lines.push("## Implementation priority");
  lines.push("");
  if (!audit.implementationPriority.length) {
    lines.push("_Coverage may already be adequate._");
  } else {
    audit.implementationPriority.forEach((step, idx) => {
      lines.push(`${idx + 1}. ${step}`);
    });
  }
  lines.push("");

  lines.push("## Notes");
  lines.push("");
  for (const n of audit.notes) lines.push(`- ${n}`);
  lines.push("");

  return `${lines.join("\n")}\n`;
}

export function formatGuideAssetMasterMarkdown(
  report: GuideAssetMasterReport,
): string {
  const lines: string[] = [];
  lines.push(`# Guide Asset Opportunities`);
  lines.push("");
  lines.push(
    `> Master report from **GuideAssetDiscoveryAgent** \`${report.agentVersion}\`. Recommendations only — does not edit guides.`,
  );
  lines.push("");
  lines.push(`- **Generated:** ${report.generatedAt}`);
  lines.push(`- **Guides audited:** ${report.guidesAudited}`);
  lines.push(
    `- **Totals:** videos ${report.totals.videoOpportunities} · screenshots ${report.totals.screenshotOpportunities} · diagrams ${report.totals.diagramOpportunities} · official sources ${report.totals.officialSourceOpportunities} · originals ${report.totals.originalVisualOpportunities} · authoritative ${report.totals.authoritativeSourceOpportunities} · ADD NOW ${report.totals.addNow} · Strong ${report.totals.strongOpportunity}`,
  );
  lines.push("");
  lines.push(
    `| Guide | Current visual quality | CQ visual | Video opportunities | Screenshot opportunities | Diagram opportunities | Official source opportunities | Original visual opportunities | Priority |`,
  );
  lines.push(
    `| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |`,
  );
  for (const row of report.rows) {
    lines.push(
      `| [${row.guideTitle}](./guides/${row.guideSlug}-asset-opportunities.md) | ${row.visualQuality} | ${row.contentQualityVisualScore ?? "—"} | ${row.videoOpportunities} | ${row.screenshotOpportunities} | ${row.diagramOpportunities} | ${row.officialSourceOpportunities} | ${row.originalVisualOpportunities} | ${row.priority} |`,
    );
  }
  lines.push("");

  lines.push("## Top 30 recommendations");
  lines.push("");
  report.topRecommendations.slice(0, 30).forEach((rec, idx) => {
    lines.push(
      `${idx + 1}. **${rec.title}** — \`${rec.sectionTitle}\` · ${recommendationLevelLabel(rec.recommendationLevel)} · ${rec.usageRecommendation}${
        rec.resolvesContentQualityIds.length
          ? ` · Resolves ${rec.resolvesContentQualityIds.join(", ")}`
          : ""
      }`,
    );
  });
  lines.push("");
  lines.push("## Notes");
  lines.push("");
  lines.push(
    "- Visual quality is qualitative — not a raw figure count.",
  );
  lines.push(
    "- CQ visual column is Content Quality `visual-media-support` (0–5) when evaluable.",
  );
  lines.push(
    "- Do not create duplicate disconnected recommendations when a CQ issue id is listed.",
  );
  lines.push("");
  return `${lines.join("\n")}\n`;
}
