import type {
  PageQualitySnapshot,
  PageQualitySnapshotInput,
} from "@/domain/schemas/content-quality";
import { PageQualitySnapshotSchema } from "@/domain/schemas/content-quality";

/**
 * Representative fixtures for Content Quality Evaluation.
 * Deterministic snapshots — not live content mutation.
 */

function fixture(input: PageQualitySnapshotInput) {
  return PageQualitySnapshotSchema.parse(input);
}

export const FIXTURE_EXCELLENT_GUIDE = fixture({
  contentId: "fixture:guide:excellent-crm-choose",
  route: "/guides/how-to-choose-crm/",
  pageType: "guide",
  title: "How to Choose a CRM",
  h1: "How to Choose a CRM",
  summary: "A decision framework for selecting CRM software.",
  primaryIntent: "informational",
  secondaryIntents: [],
  presentSections: [
    "quick-answer",
    "framework-or-steps",
    "examples",
    "tools-or-resources",
    "sources",
    "next-step",
    "faq",
  ],
  missingSections: [],
  depthSignals: [
    "workflow: requirements → shortlist → compare",
    "trade-off: simplicity vs customization",
    "example: 8-person sales team",
    "criteria: pipeline stages, integrations",
    "limitation: when spreadsheets still win",
    "edge-case: multi-entity billing",
  ],
  originalValueSignals: [
    "SoftwareGlimpse CRM selection framework",
    "Requirements Builder handoff",
    "Vendor scorecard link",
  ],
  evidenceSignals: {
    primarySourceCount: 2,
    officialDocCount: 1,
    pricingSourceCount: 0,
    screenshotCount: 0,
    officialVideoCount: 0,
    factRefCount: 3,
    verificationDatesPresent: true,
    unsupportedClaimFlags: 0,
  },
  freshness: {
    lastReviewedAt: "2026-08-01T00:00:00.000Z",
    sourcesVerifiedAt: "2026-08-01T00:00:00.000Z",
    withinPolicy: true,
    staleClaimFlags: 0,
    brokenSourceFlags: 0,
  },
  decisionSupportSignals: [
    "selection framework",
    "requirements checklist",
    "best-fit scenarios",
  ],
  actionSignals: [
    "open Requirements Builder",
    "download evaluation checklist",
    "open CRM Finder",
  ],
  structure: {
    hasQuickAnswer: true,
    headingCount: 8,
    hasLogicalSequence: true,
    usesTablesOrCards: true,
    bloatedIntro: false,
    excessiveFaqDuplication: false,
    repetitive: false,
  },
  media: {
    teachingVisualCount: 2,
    decorativeOnly: false,
    workflowDiagram: true,
    comparisonMatrix: false,
    checklistVisual: true,
    subjectNeedsVisuals: true,
  },
  linking: {
    parentHubLink: true,
    supportingContentLinks: 4,
    productLinks: 2,
    toolLinks: 2,
    resourceLinks: 1,
    nextStepLink: true,
    orphanRisk: false,
    lowQualityLinkSpam: false,
  },
  journey: {
    stage: "define-requirements",
    nextStepFitsStage: true,
    nextStepLabel: "Build your CRM requirements",
    missingNextStep: false,
  },
  trust: {
    authorOrEditorialOwnership: true,
    methodologyReferenced: true,
    updatedDateVisible: true,
    sourceTransparency: true,
    affiliateDisclosure: true,
    limitationsNoted: true,
    confidenceStated: false,
  },
  differentiation: {
    distinctPurpose: true,
    duplicateIntentRisk: false,
    genericCategoryCopy: false,
    onlyH1Changed: false,
    semanticOverlapWith: [],
  },
  pageTypeChecklist: {
    passed: [
      "direct-answer-decision-rule",
      "worked-example",
      "teaching-visual",
      "unique-hero",
      "anchor-supports",
      "checklist-or-framework",
    ],
    failed: [],
  },
  notes: [],
});

export const FIXTURE_THIN_GUIDE = fixture({
  contentId: "fixture:guide:thin-what-is-crm",
  route: "/guides/what-is-crm-thin/",
  pageType: "guide",
  title: "What Is CRM",
  h1: "What Is CRM",
  summary: "CRM means customer relationship management.",
  primaryIntent: "informational",
  secondaryIntents: ["commercial"],
  presentSections: ["explanation"],
  missingSections: [
    "quick-answer",
    "framework-or-steps",
    "examples",
    "tools-or-resources",
    "sources",
    "next-step",
    "faq",
  ],
  depthSignals: ["surface definition only"],
  originalValueSignals: ["generic paraphrase of vendor glossaries"],
  evidenceSignals: {
    primarySourceCount: 0,
    officialDocCount: 0,
    pricingSourceCount: 0,
    screenshotCount: 0,
    officialVideoCount: 0,
    factRefCount: 0,
    verificationDatesPresent: false,
    unsupportedClaimFlags: 0,
  },
  freshness: {
    staleClaimFlags: 0,
    brokenSourceFlags: 0,
  },
  decisionSupportSignals: [],
  actionSignals: [],
  structure: {
    hasQuickAnswer: false,
    headingCount: 1,
    hasLogicalSequence: true,
    usesTablesOrCards: false,
    bloatedIntro: true,
    excessiveFaqDuplication: false,
    repetitive: true,
  },
  media: {
    teachingVisualCount: 0,
    decorativeOnly: true,
    workflowDiagram: false,
    comparisonMatrix: false,
    checklistVisual: false,
    subjectNeedsVisuals: true,
  },
  linking: {
    parentHubLink: false,
    supportingContentLinks: 0,
    productLinks: 0,
    toolLinks: 0,
    resourceLinks: 0,
    nextStepLink: false,
    orphanRisk: true,
    lowQualityLinkSpam: false,
  },
  journey: {
    stage: "learn",
    missingNextStep: true,
  },
  trust: {
    authorOrEditorialOwnership: false,
    methodologyReferenced: false,
    updatedDateVisible: false,
    sourceTransparency: false,
    affiliateDisclosure: false,
    limitationsNoted: false,
    confidenceStated: false,
  },
  differentiation: {
    distinctPurpose: true,
    duplicateIntentRisk: false,
    genericCategoryCopy: false,
    onlyH1Changed: false,
    semanticOverlapWith: [],
  },
  pageTypeChecklist: {
    passed: [],
    failed: [
      "direct-answer-decision-rule",
      "worked-example",
      "teaching-visual",
      "unique-hero",
      "anchor-supports",
      "checklist-or-framework",
    ],
  },
  notes: ["Thin educational stub"],
});

export const FIXTURE_GOOD_PRODUCT_REVIEW = fixture({
  contentId: "fixture:review:good-pipedrive",
  route: "/software/pipedrive/",
  pageType: "product-review",
  title: "Pipedrive Review",
  h1: "Pipedrive Review",
  summary: "Sales CRM focused on pipeline visibility for small teams.",
  primaryIntent: "commercial",
  secondaryIntents: [],
  presentSections: [
    "verdict",
    "best-for",
    "not-for",
    "criteria",
    "features",
    "pricing",
    "pros-cons",
    "evidence",
    "alternatives",
    "methodology",
    "faq",
  ],
  missingSections: [],
  depthSignals: [
    "workflow: deal pipeline stages",
    "trade-off: sales focus vs marketing automation",
    "criteria: ease of use, reporting, integrations",
    "limitation: limited marketing suite",
    "example: SDR team of 12",
  ],
  originalValueSignals: [
    "SoftwareGlimpse criterion assessments",
    "editorial verdict",
    "best-for / not-for framing",
  ],
  evidenceSignals: {
    primarySourceCount: 4,
    officialDocCount: 3,
    pricingSourceCount: 2,
    screenshotCount: 3,
    officialVideoCount: 1,
    factRefCount: 12,
    verificationDatesPresent: true,
    unsupportedClaimFlags: 0,
  },
  freshness: {
    lastReviewedAt: "2026-07-15T00:00:00.000Z",
    sourcesVerifiedAt: "2026-07-15T00:00:00.000Z",
    pricingFresh: true,
    withinPolicy: true,
    staleClaimFlags: 0,
    brokenSourceFlags: 0,
  },
  decisionSupportSignals: [
    "criterion assessments",
    "best-for scenarios",
    "alternatives links",
    "comparison links",
  ],
  actionSignals: ["compare alternatives", "open pricing tab", "visit vendor CTA"],
  structure: {
    hasQuickAnswer: true,
    headingCount: 12,
    hasLogicalSequence: true,
    usesTablesOrCards: true,
    bloatedIntro: false,
    excessiveFaqDuplication: false,
    repetitive: false,
  },
  media: {
    teachingVisualCount: 3,
    decorativeOnly: false,
    workflowDiagram: false,
    comparisonMatrix: true,
    checklistVisual: false,
    subjectNeedsVisuals: true,
  },
  linking: {
    parentHubLink: true,
    supportingContentLinks: 3,
    productLinks: 0,
    toolLinks: 1,
    resourceLinks: 0,
    nextStepLink: true,
    orphanRisk: false,
    lowQualityLinkSpam: false,
  },
  journey: {
    stage: "research",
    nextStepFitsStage: true,
    nextStepLabel: "Compare Pipedrive vs HubSpot",
    missingNextStep: false,
  },
  trust: {
    authorOrEditorialOwnership: true,
    methodologyReferenced: true,
    updatedDateVisible: true,
    sourceTransparency: true,
    affiliateDisclosure: true,
    limitationsNoted: true,
    confidenceStated: true,
  },
  differentiation: {
    distinctPurpose: true,
    duplicateIntentRisk: false,
    genericCategoryCopy: false,
    onlyH1Changed: false,
    semanticOverlapWith: [],
  },
  pageTypeChecklist: {
    passed: [
      "approved-editorial",
      "criterion-rationales",
      "best-for-and-not-for",
      "pricing-summary",
      "alternative-or-comparison-links",
      "methodology-referenced",
      "fact-backed-claims",
    ],
    failed: [],
  },
  notes: [],
});

export const FIXTURE_THIN_INDUSTRY = fixture({
  contentId: "fixture:industry:thin-real-estate",
  route: "/industries/real-estate/",
  pageType: "industry",
  title: "CRM for Real Estate",
  h1: "CRM for Real Estate",
  summary: "Find the best CRM for real estate teams.",
  primaryIntent: "commercial",
  secondaryIntents: [],
  presentSections: ["intro"],
  missingSections: [
    "industry-priorities",
    "use-cases",
    "capabilities",
    "implementation-notes",
    "security-or-compliance",
    "next-step",
  ],
  depthSignals: ["generic category benefits restated"],
  originalValueSignals: [],
  evidenceSignals: {
    primarySourceCount: 0,
    officialDocCount: 0,
    pricingSourceCount: 0,
    screenshotCount: 0,
    officialVideoCount: 0,
    factRefCount: 0,
    verificationDatesPresent: false,
    unsupportedClaimFlags: 1,
  },
  freshness: {
    staleClaimFlags: 1,
    brokenSourceFlags: 0,
    withinPolicy: false,
  },
  decisionSupportSignals: [],
  actionSignals: [],
  structure: {
    hasQuickAnswer: false,
    headingCount: 2,
    hasLogicalSequence: true,
    usesTablesOrCards: false,
    bloatedIntro: true,
    excessiveFaqDuplication: false,
    repetitive: true,
  },
  media: {
    teachingVisualCount: 0,
    decorativeOnly: false,
    workflowDiagram: false,
    comparisonMatrix: false,
    checklistVisual: false,
    subjectNeedsVisuals: true,
  },
  linking: {
    parentHubLink: true,
    supportingContentLinks: 0,
    productLinks: 5,
    toolLinks: 0,
    resourceLinks: 0,
    nextStepLink: false,
    orphanRisk: false,
    lowQualityLinkSpam: true,
  },
  journey: {
    stage: "find",
    missingNextStep: true,
  },
  trust: {
    authorOrEditorialOwnership: false,
    methodologyReferenced: false,
    updatedDateVisible: false,
    sourceTransparency: false,
    affiliateDisclosure: false,
    limitationsNoted: false,
    confidenceStated: false,
  },
  differentiation: {
    distinctPurpose: false,
    duplicateIntentRisk: true,
    nearDuplicateOf: "content:category:crm",
    genericCategoryCopy: true,
    onlyH1Changed: false,
    semanticOverlapWith: ["content:category:crm"],
  },
  pageTypeChecklist: {
    passed: [],
    failed: [
      "industry-specific-priorities",
      "not-generic-category-copy",
      "use-case-links",
      "capability-or-feature-links",
      "buyer-questions",
    ],
  },
  notes: ["Generic category copy with industry H1"],
});

export const FIXTURE_DUPLICATE_ARTICLE = fixture({
  contentId: "fixture:article:duplicate-pipeline",
  route: "/guides/crm-pipeline-management-basics/",
  pageType: "article",
  title: "CRM Pipeline Management Basics",
  h1: "CRM Pipeline Management Basics",
  summary: "Learn pipeline management in CRM.",
  primaryIntent: "informational",
  secondaryIntents: [],
  presentSections: ["direct-answer", "explanation", "related"],
  missingSections: ["examples", "next-step"],
  depthSignals: ["example: basic stages"],
  originalValueSignals: [],
  evidenceSignals: {
    primarySourceCount: 0,
    officialDocCount: 0,
    pricingSourceCount: 0,
    screenshotCount: 0,
    officialVideoCount: 0,
    factRefCount: 0,
    verificationDatesPresent: false,
    unsupportedClaimFlags: 0,
  },
  freshness: {},
  decisionSupportSignals: [],
  actionSignals: [],
  structure: {
    hasQuickAnswer: true,
    headingCount: 4,
    hasLogicalSequence: true,
    usesTablesOrCards: false,
    bloatedIntro: false,
    excessiveFaqDuplication: false,
    repetitive: true,
  },
  media: {
    teachingVisualCount: 0,
    decorativeOnly: false,
    workflowDiagram: false,
    comparisonMatrix: false,
    checklistVisual: false,
    subjectNeedsVisuals: false,
  },
  linking: {
    parentHubLink: true,
    supportingContentLinks: 1,
    productLinks: 0,
    toolLinks: 0,
    resourceLinks: 0,
    nextStepLink: false,
    orphanRisk: false,
    lowQualityLinkSpam: false,
  },
  journey: {
    stage: "learn",
    missingNextStep: true,
  },
  trust: {
    updatedDateVisible: true,
    authorOrEditorialOwnership: false,
    methodologyReferenced: false,
    sourceTransparency: false,
    affiliateDisclosure: false,
    limitationsNoted: false,
    confidenceStated: false,
  },
  differentiation: {
    distinctPurpose: false,
    duplicateIntentRisk: true,
    nearDuplicateOf: "content:guide:what-is-sales-pipeline",
    genericCategoryCopy: false,
    onlyH1Changed: true,
    semanticOverlapWith: ["content:guide:what-is-sales-pipeline"],
  },
  pageTypeChecklist: {
    passed: ["answers-title-question"],
    failed: [
      "concrete-example",
      "supports-anchor",
      "no-product-ranking-half-page",
      "distinct-from-siblings",
    ],
  },
  notes: ["Near-duplicate of existing pipeline explainer"],
});

export const FIXTURE_FEATURE_MISSING_EVIDENCE = fixture({
  contentId: "fixture:feature:missing-evidence-automation",
  route: "/features/workflow-automation/",
  pageType: "feature",
  title: "Workflow Automation",
  h1: "Workflow Automation in CRM",
  summary: "Automate repetitive CRM tasks.",
  primaryIntent: "informational",
  secondaryIntents: [],
  presentSections: [
    "definition",
    "need-guidance",
    "workflow",
    "requirement-mappings",
    "product-support",
    "next-step",
  ],
  missingSections: ["evidence"],
  depthSignals: [
    "workflow: trigger → action → notify",
    "requirement: reduce manual data entry",
    "limitation: complex branching may need iPaaS",
  ],
  originalValueSignals: ["need-if / may-not-need-if guidance"],
  evidenceSignals: {
    primarySourceCount: 0,
    officialDocCount: 0,
    pricingSourceCount: 0,
    screenshotCount: 0,
    officialVideoCount: 0,
    factRefCount: 0,
    verificationDatesPresent: false,
    unsupportedClaimFlags: 3,
  },
  freshness: {
    withinPolicy: false,
    staleClaimFlags: 2,
    brokenSourceFlags: 0,
  },
  decisionSupportSignals: ["need-if guidance", "requirement mappings"],
  actionSignals: ["open related requirements"],
  structure: {
    hasQuickAnswer: true,
    headingCount: 6,
    hasLogicalSequence: true,
    usesTablesOrCards: true,
    bloatedIntro: false,
    excessiveFaqDuplication: false,
    repetitive: false,
  },
  media: {
    teachingVisualCount: 1,
    decorativeOnly: false,
    workflowDiagram: true,
    comparisonMatrix: false,
    checklistVisual: false,
    subjectNeedsVisuals: true,
  },
  linking: {
    parentHubLink: true,
    supportingContentLinks: 2,
    productLinks: 4,
    toolLinks: 0,
    resourceLinks: 0,
    nextStepLink: true,
    orphanRisk: false,
    lowQualityLinkSpam: false,
  },
  journey: {
    stage: "evaluate",
    nextStepFitsStage: true,
    nextStepLabel: "Map to requirements",
    missingNextStep: false,
  },
  trust: {
    authorOrEditorialOwnership: true,
    methodologyReferenced: false,
    updatedDateVisible: true,
    sourceTransparency: false,
    affiliateDisclosure: false,
    limitationsNoted: true,
    confidenceStated: false,
  },
  differentiation: {
    distinctPurpose: true,
    duplicateIntentRisk: false,
    genericCategoryCopy: false,
    onlyH1Changed: false,
    semanticOverlapWith: [],
  },
  pageTypeChecklist: {
    passed: [
      "definition",
      "need-if-guidance",
      "requirement-mappings",
      "teaching-visual-for-pillars",
    ],
    failed: ["support-evidence-not-invented"],
  },
  notes: [
    "Product support matrix claims exist without enrichment evidence",
  ],
});

export const FIXTURE_SNAPSHOTS: Record<string, PageQualitySnapshot> = {
  "excellent-guide": FIXTURE_EXCELLENT_GUIDE,
  "thin-guide": FIXTURE_THIN_GUIDE,
  "good-product-review": FIXTURE_GOOD_PRODUCT_REVIEW,
  "thin-industry": FIXTURE_THIN_INDUSTRY,
  "duplicate-article": FIXTURE_DUPLICATE_ARTICLE,
  "feature-missing-evidence": FIXTURE_FEATURE_MISSING_EVIDENCE,
};

export function getFixtureSnapshot(id: string): PageQualitySnapshot {
  const snap = FIXTURE_SNAPSHOTS[id];
  if (!snap) {
    throw new Error(
      `Unknown content-quality fixture "${id}". Known: ${Object.keys(FIXTURE_SNAPSHOTS).join(", ")}`,
    );
  }
  return snap;
}

export function listFixtureIds(): string[] {
  return Object.keys(FIXTURE_SNAPSHOTS);
}
