import fs from "node:fs";
import path from "node:path";
import { AUTHORITY_INTELLIGENCE_VERSION } from "@/domain/schemas/authority-intelligence";
import {
  PROMOTION_CHANNELS,
  PROMOTION_LIVE_QUERIES_RUN,
  assertPromotionChannelsPresent,
} from "./channels";
import { consumePromotionInputs } from "./consume-inputs";
import { buildPromotionPlans, buildToolLaunchPlans } from "./plans";
import { buildPriorityAssets } from "./priority-assets";
import { formatContentPromotionReport } from "./reports";
import { communityUnsafeRejects } from "./safety";
import {
  CONTENT_PROMOTION_AGENT,
  type ContentPromotionReport,
  type PromotionChannel,
} from "./types";

export { CONTENT_PROMOTION_AGENT };

const AUTHORITY_DIR = path.join(process.cwd(), "docs", "authority");
const MASTER_PATH = path.join(
  AUTHORITY_DIR,
  "PROMOTION-OPPORTUNITIES-LATEST.md",
);
const ARCHIVE_DIR = path.join(AUTHORITY_DIR, "archive");

export type ContentPromotionAgentOptions = {
  write?: boolean;
  archive?: boolean;
  topic?: string;
  generatedAt?: string;
  channels?: PromotionChannel[];
  requireChannels?: boolean;
};

export type ContentPromotionAgentResult = {
  agent: typeof CONTENT_PROMOTION_AGENT;
  report: ContentPromotionReport;
  paths: { master?: string; archive?: string };
  markdown: string;
};

/**
 * ContentPromotionOpportunityAgent
 *
 * For priority SG pages/tools/resources, identify realistic audience-fit
 * promotion channels, angles, and repurposing ideas.
 * Never posts. Never generates all creative assets. Community-safe.
 */
export function runContentPromotionOpportunityAgent(
  opts: ContentPromotionAgentOptions = {},
): ContentPromotionAgentResult {
  const generatedAt = opts.generatedAt ?? new Date().toISOString();
  const topic = opts.topic ?? "CRM / business software / RevOps";
  const write = opts.write !== false;
  const channels = opts.channels ?? PROMOTION_CHANNELS;

  if (opts.requireChannels !== false) {
    assertPromotionChannelsPresent(channels);
  }

  const consumedInputs = consumePromotionInputs();
  const assets = buildPriorityAssets();
  const plans = buildPromotionPlans(assets);
  const launchPlans = buildToolLaunchPlans();
  const rejectedTactics = communityUnsafeRejects();

  const report: ContentPromotionReport = {
    version: AUTHORITY_INTELLIGENCE_VERSION,
    generatedAt,
    topic,
    postsToChannels: false,
    generatesAssets: false,
    consumedInputs,
    channelsCatalogued: channels.length,
    plans,
    launchPlans,
    rejectedTactics,
    queriesRun: PROMOTION_LIVE_QUERIES_RUN,
    limitations: [
      "Report only — never posts to communities, never automates Reddit, never fabricates social proof.",
      "Repurposing ideas are recommendations only — assets are not generated by this agent.",
      "Channel fit is mandatory; weak channels are listed to discourage spray-and-pray.",
      "Cross-links to Partnerships / Paid / Digital PR are contextual — refresh those reports for current opportunities.",
      "Missing input reports are noted in Consumed inputs; agent still runs on registries.",
    ],
  };

  const markdown = formatContentPromotionReport(report);
  const paths: ContentPromotionAgentResult["paths"] = {};

  if (write) {
    fs.mkdirSync(AUTHORITY_DIR, { recursive: true });
    fs.mkdirSync(ARCHIVE_DIR, { recursive: true });
    fs.writeFileSync(MASTER_PATH, markdown, "utf8");
    paths.master = MASTER_PATH;
    if (opts.archive !== false) {
      const day = generatedAt.slice(0, 10);
      const archivePath = path.join(
        ARCHIVE_DIR,
        `${day}-promotion-opportunities.md`,
      );
      fs.writeFileSync(archivePath, markdown, "utf8");
      paths.archive = archivePath;
    }
  }

  return {
    agent: CONTENT_PROMOTION_AGENT,
    report,
    paths,
    markdown,
  };
}
