import type { PresenceLiveHit } from "./types";

export const PRESENCE_LIVE_VERIFIED_AT = "2026-08-15T09:45:00.000Z";
const V = PRESENCE_LIVE_VERIFIED_AT;

export const PRESENCE_LIVE_QUERIES_RUN: string[] = [
  "CRM software directory listing free G2 Capterra GetApp SaaSHub AlternativeTo",
  "Best SaaS directories 2026 Toolradar",
  "guaranteed dofollow SaaS directory submission",
];

export const PRESENCE_LIVE_HITS: PresenceLiveHit[] = [
  {
    url: "https://sell.g2.com/plans",
    domain: "g2.com",
    organization: "G2",
    kind: "REVIEW_DIRECTORY",
    opportunity: "Claim/create free vendor profile; collect reviews; optional paid plans for badges/analytics",
    audience: "B2B software buyers researching CRM/category peers",
    visibilityValue: "excellent",
    seoLinkPrimary: false,
    costNotes: "Free profile/reviews; paid plans for advanced features (published vendor pricing varies)",
    claimPath: "Vendor portal / sell.g2.com — company-domain email",
    whyWorthwhile: "Buyer-intent presence and trust signals — not a dofollow SEO purchase.",
    discoveryQuery: "CRM software directory listing free G2 Capterra GetApp SaaSHub AlternativeTo",
    verifiedAt: V,
    pageSummary: "G2 vendor plans page — free vs paid vendor capabilities.",
    provisionalDecision: "accept",
  },
  {
    url: "https://www.capterra.com/",
    domain: "capterra.com",
    organization: "Capterra (G2 Digital Markets ecosystem)",
    kind: "REVIEW_DIRECTORY",
    opportunity: "Claim free listing via GDM vendor cabinet; optional PPC for visibility",
    audience: "SMB software shoppers",
    visibilityValue: "excellent",
    seoLinkPrimary: false,
    costNotes: "Free listing; PPC optional (separate paid product)",
    claimPath: "G2 Digital Markets / Capterra vendor registration",
    whyWorthwhile: "SMB discovery channel complementary to G2; claim for presence.",
    discoveryQuery: "CRM software directory listing free G2 Capterra GetApp SaaSHub AlternativeTo",
    verifiedAt: V,
    pageSummary: "Capterra home — software comparison/directory for SMBs.",
    provisionalDecision: "accept",
  },
  {
    url: "https://www.getapp.com/",
    domain: "getapp.com",
    organization: "GetApp",
    kind: "REVIEW_DIRECTORY",
    opportunity: "Claim listing in GDM family (often with Capterra claim workflow)",
    audience: "SMB / mid-market software researchers",
    visibilityValue: "strong",
    seoLinkPrimary: false,
    costNotes: "Free claim; paid options via GDM cabinet",
    claimPath: "GDM vendor cabinet — claim GetApp profile",
    whyWorthwhile: "Additional buyer surface in same ecosystem as Capterra.",
    discoveryQuery: "CRM software directory listing free G2 Capterra GetApp SaaSHub AlternativeTo",
    verifiedAt: V,
    pageSummary: "GetApp software directory.",
    provisionalDecision: "accept",
  },
  {
    url: "https://www.softwareadvice.com/",
    domain: "softwareadvice.com",
    organization: "Software Advice",
    kind: "REVIEW_DIRECTORY",
    opportunity: "Claim listing; advisor-led intro model for some categories",
    audience: "Buyers seeking software advice / shortlists",
    visibilityValue: "strong",
    seoLinkPrimary: false,
    costNotes: "Free claim; lead products may be paid",
    claimPath: "GDM vendor cabinet",
    whyWorthwhile: "Presence where buyers request guided recommendations.",
    discoveryQuery: "CRM software directory listing free G2 Capterra GetApp SaaSHub AlternativeTo",
    verifiedAt: V,
    pageSummary: "Software Advice comparison/advice site.",
    provisionalDecision: "accept",
  },
  {
    url: "https://alternativeto.net/",
    domain: "alternativeto.net",
    organization: "AlternativeTo",
    kind: "ALTERNATIVES_DIRECTORY",
    opportunity: "List SoftwareGlimpse tools / research under CRM alternatives contexts",
    audience: "Users searching alternatives to incumbent CRMs",
    visibilityValue: "strong",
    seoLinkPrimary: false,
    costNotes: "Free submission; paid acceleration sometimes offered",
    claimPath: "Add product / alternatives lists on AlternativeTo",
    whyWorthwhile: "Captures alternatives-intent traffic; visibility over link schemes.",
    discoveryQuery: "Best SaaS directories 2026 Toolradar",
    verifiedAt: V,
    pageSummary: "Crowd-sourced alternatives directory.",
    provisionalDecision: "accept",
  },
  {
    url: "https://www.saashub.com/",
    domain: "saashub.com",
    organization: "SaaSHub",
    kind: "SAAS_DIRECTORY",
    opportunity: "Free SaaS listing for CRM tools/research properties",
    audience: "SaaS researchers / builders",
    visibilityValue: "good",
    seoLinkPrimary: false,
    costNotes: "Free listing; paid featured optional",
    claimPath: "Submit via SaaSHub",
    whyWorthwhile: "Low-cost presence; evaluate for referral quality before paying for features.",
    discoveryQuery: "Best SaaS directories 2026 Toolradar",
    verifiedAt: V,
    pageSummary: "SaaSHub directory of SaaS products.",
    provisionalDecision: "accept",
  },
  {
    url: "https://www.producthunt.com/",
    domain: "producthunt.com",
    organization: "Product Hunt",
    kind: "LAUNCH_PLATFORM",
    opportunity: "Launch interactive tools (Finder / Cost Calculator) with authentic engagement",
    audience: "Makers and early adopters",
    visibilityValue: "good",
    seoLinkPrimary: false,
    costNotes: "Free to launch",
    claimPath: "Product Hunt launch flow",
    whyWorthwhile: "Launch spike + credibility badge — see ContentPromotion launch plans.",
    discoveryQuery: "Best SaaS directories 2026 Toolradar",
    verifiedAt: V,
    pageSummary: "Product Hunt launch platform.",
    provisionalDecision: "accept",
  },
  {
    url: "https://sourceforge.net/",
    domain: "sourceforge.net",
    organization: "SourceForge",
    kind: "SAAS_DIRECTORY",
    opportunity: "Optional listing if serving more traditional software buyers",
    audience: "Technical / traditional software audiences",
    visibilityValue: "good",
    seoLinkPrimary: false,
    costNotes: "Free listing tiers available",
    claimPath: "SourceForge vendor/project listing",
    whyWorthwhile: "Secondary presence; prioritize G2/Capterra first.",
    discoveryQuery: "CRM software directory listing free G2 Capterra GetApp SaaSHub AlternativeTo",
    verifiedAt: V,
    pageSummary: "SourceForge software directory.",
    provisionalDecision: "accept",
  },
  {
    url: "https://thesaasdir.com/blog/saas-directory-submission-budget/",
    domain: "thesaasdir.com",
    organization: "The SaaS Dir (dofollow listing pitch)",
    kind: "SAAS_DIRECTORY",
    opportunity: "Paid dofollow directory submission framed as SEO backlink",
    audience: "SEO-motivated submitters",
    visibilityValue: "none",
    seoLinkPrimary: true,
    costNotes: "~$39 dofollow pitch (live coverage)",
    claimPath: "N/A — reject",
    whyWorthwhile: "N/A",
    discoveryQuery: "guaranteed dofollow SaaS directory submission",
    verifiedAt: V,
    pageSummary: "Promotes dofollow directory submission as SEO backlink buy.",
    provisionalDecision: "reject",
    rejectReason: "AVOID — LINK SCHEME RISK (paid dofollow SEO listing)",
  },
];

export function assertPresenceHitsPresent(hits: PresenceLiveHit[]): void {
  if (hits.filter((h) => h.provisionalDecision === "accept").length < 5) {
    throw new Error("PresenceOpportunityAgent requires live directory hits.");
  }
}
