/**
 * Live-verified earned-backlink search hits.
 * Base catalog verified 2026-08-15; refreshed 2026-08-20 for multi-category
 * inventory (CRM + SI + marketing + PM + HR + cross-category tools/resources).
 * Every URL was observed in live web search — do not invent hits.
 */

import type { LiveSearchHit } from "./types";

/** Latest full live-search refresh timestamp */
export const EARNED_LIVE_HITS_VERIFIED_AT = "2026-08-20T10:00:00.000Z";

/** Original CRM catalog verification (kept for historical evidence notes) */
const V0 = "2026-08-15T08:30:00.000Z";
/** Alias used by the 2026-08-15 catalog entries below */
const V = V0;

export const EARNED_LIVE_QUERIES_RUN: string[] = [
  "awesome CRM systems resources templates",
  "RevOps resources roundup toolkit",
  "Pulse RevOps knowledge library",
  "Revenue Operations Alliance community",
  "Revenue Enablement Society resources",
  "B2B sales operations playbook templates CRM",
  "CRM implementation checklist SMB",
  "CRM requirements checklist template",
  "CRM migration checklist data migration",
  "CRM buying checklist evaluation scorecard",
  "CRM vendor scorecard template",
  "how to choose CRM small business checklist",
  "best free CRM software 2026",
  "CRM cost calculator TCO",
  "RevOps playbook templates tech stack",
  "CRM implementation educational .edu OR site:.gov",
  "sample CRM requirements document academia",
  "softwareglimpse.com CRM mention",
  "CRM evaluation checklist complementary resources",
  "CRM deployment checklist HubSpot Pipedrive",
  // 2026-08-20 multi-category refresh
  "sales intelligence tools resources roundup checklist evaluation 2026",
  "how to choose a sales intelligence platform 2026",
  "project management software evaluation criteria scorecard",
  "marketing software evaluation checklist vendor scorecard",
  "SaaS vendor evaluation scorecard template",
  "HR software evaluation checklist OR RFP scorecard",
  "CRM business case template OR CRM ROI calculator resources",
  "CRM readiness assessment complementary resources",
];

export const EARNED_LIVE_HITS: LiveSearchHit[] = [
  // ── ACCEPT (56) ──────────────────────────────────────────────────────────
  {
    url: "https://resources.rework.com/libraries/awesome-business-resources/awesome-crm-systems",
    domain: "resources.rework.com",
    organization: "Rework",
    title: "Awesome CRM Systems — curated CRM resources",
    type: "RESOURCE_PAGE",
    discoveryQuery: "awesome CRM systems resources templates",
    verifiedAt: V,
    pageSummary:
      "Curated Awesome-style CRM resource list with a Templates section and an open Contributing invite (“Know a great CRM resource? Let us know”).",
    whyTheyMightLink:
      "Their Templates/resources section is built for complementary buyer utilities; SoftwareGlimpse’s CRM Finder and evaluation checklist fit as vendor-neutral selection aids alongside their existing CRM system links.",
    relevantSgPage: "/tools/crm-finder/",
    seoValue: "strong",
    referralValue: "strong",
    difficulty: "moderate",
    effort: "small",
    likelihood: "high",
    contactPath:
      "https://resources.rework.com/libraries/awesome-business-resources/awesome-crm-systems — use “Know a great CRM resource? Let us know” CTA",
    submissionPath:
      "Open https://resources.rework.com/libraries/awesome-business-resources/awesome-crm-systems → Contributing / “Know a great CRM resource?”",

    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: Templates section + explicit contribution invite observed.",
    ],
  },
  {
    url: "https://www.flowla.com/blog/resources-for-revops-professionals",
    domain: "flowla.com",
    organization: "Flowla",
    title: "Resources for RevOps professionals",
    type: "RESOURCE_PAGE",
    discoveryQuery: "RevOps resources roundup toolkit",
    verifiedAt: V,
    pageSummary:
      "RevOps resource roundup linking tools, playbooks, and learning resources for revenue operations practitioners.",
    whyTheyMightLink:
      "Roundup already aggregates RevOps-facing utilities; a vendor-neutral CRM Finder plus cost calculator helps readers shortlist and budget CRM stack choices without competing with Flowla’s deal-room product.",
    relevantSgPage: "/tools/crm-finder/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Live RevOps resources blog roundup verified 2026-08-15."],
  },
  {
    url: "https://pulserevops.com/knowledge",
    domain: "pulserevops.com",
    organization: "Pulse RevOps",
    title: "Pulse RevOps Knowledge Library",
    type: "RESOURCE_PAGE",
    discoveryQuery: "Pulse RevOps knowledge library",
    verifiedAt: V,
    pageSummary:
      "Knowledge library for RevOps practitioners covering process, tooling, and enablement topics.",
    whyTheyMightLink:
      "Library curates practical RevOps tooling; SoftwareGlimpse’s CRM requirements builder and vendor scorecard complement stack-evaluation content without selling a CRM.",
    relevantSgPage: "/tools/crm-vendor-scorecard/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "medium",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["Live knowledge hub verified 2026-08-15."],
  },
  {
    url: "https://www.revenueoperationsalliance.com/",
    domain: "revenueoperationsalliance.com",
    organization: "Revenue Operations Alliance",
    title: "Revenue Operations Alliance",
    type: "ASSOCIATION",
    discoveryQuery: "Revenue Operations Alliance community",
    verifiedAt: V,
    pageSummary:
      "Professional RevOps community / alliance site connecting practitioners and resources.",
    whyTheyMightLink:
      "Member education often needs free evaluation tooling; CRM Finder and evaluation checklist support members choosing or replacing CRM systems without vendor lock-in.",
    relevantSgPage: "/resources/crm-evaluation-checklist/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "hard",
    effort: "medium",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["Association homepage live-verified 2026-08-15."],
  },
  {
    url: "https://www.resociety.global/",
    domain: "resociety.global",
    organization: "Revenue Enablement Society",
    title: "Revenue Enablement Society",
    type: "ASSOCIATION",
    discoveryQuery: "Revenue Enablement Society resources",
    verifiedAt: V,
    pageSummary:
      "Global revenue enablement society with practitioner community and educational focus.",
    whyTheyMightLink:
      "Enablement audiences train sellers on systems adoption; a CRM training plan plus implementation checklist are natural free member resources alongside enablement curricula.",
    relevantSgPage: "/resources/crm-training-plan/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "hard",
    effort: "medium",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["Association site live-verified 2026-08-15."],
  },
  {
    url: "https://umbrex.com/resources/b2b-sales-operations-playbook/",
    domain: "umbrex.com",
    organization: "Umbrex",
    title: "B2B Sales Operations Playbook",
    type: "RESOURCE_PAGE",
    discoveryQuery: "B2B sales operations playbook templates CRM",
    verifiedAt: V,
    pageSummary:
      "Sales operations playbook with chapters covering process and templates relevant to CRM-backed ops.",
    whyTheyMightLink:
      "Playbook’s templates chapter covers sales ops tooling; SoftwareGlimpse’s CRM implementation planner and field-mapping template fill practical gaps for readers executing CRM-backed process changes.",
    relevantSgPage: "/tools/crm-implementation-planner/",
    seoValue: "strong",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Playbook page with templates chapter verified 2026-08-15."],
  },
  {
    url: "https://toolkitcafe.com/blog/sales-operations-playbook",
    domain: "toolkitcafe.com",
    organization: "Toolkit Cafe",
    title: "Sales Operations Playbook",
    type: "REFERENCE_LINK",
    discoveryQuery: "B2B sales operations playbook templates CRM",
    verifiedAt: V,
    pageSummary:
      "Sales operations playbook article that discusses CRM selection as part of ops foundation.",
    whyTheyMightLink:
      "Article already frames CRM selection as an ops step; linking CRM Finder and how-to-choose-CRM guide gives readers a concrete next step instead of stopping at high-level advice.",
    relevantSgPage: "/guides/how-to-choose-crm/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["Sales ops playbook blog verified 2026-08-15."],
  },
  {
    url: "https://toolkitcafe.com/blog/crm-implementation-checklist-for-smb",
    domain: "toolkitcafe.com",
    organization: "Toolkit Cafe",
    title: "CRM Implementation Checklist for SMB",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM implementation checklist SMB",
    verifiedAt: V,
    pageSummary:
      "SMB-focused CRM implementation checklist guide covering rollout steps and readiness.",
    whyTheyMightLink:
      "Guide teaches implementation sequencing and readiness; SoftwareGlimpse’s free CRM Readiness Assessment plus implementation checklist give SMB readers a scored prep step before rollout.",
    relevantSgPage: "/tools/crm-readiness-assessment/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "moderate",
    effort: "small",
    likelihood: "high",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["SMB implementation checklist post verified 2026-08-15."],
  },
  {
    url: "https://softwareinspect.com/blog/crm-implementation-checklist",
    domain: "softwareinspect.com",
    organization: "SoftwareInspect",
    title: "CRM Implementation Checklist",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM implementation checklist SMB",
    verifiedAt: V,
    pageSummary:
      "Implementation checklist article that stresses gathering requirements before engaging vendors.",
    whyTheyMightLink:
      "Piece explicitly pushes requirements work before vendor demos; CRM requirements builder and requirements template are direct companion tools for that pre-vendor step.",
    relevantSgPage: "/tools/crm-requirements-builder/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Article emphasizes requirements-before-vendors framing (2026-08-15).",
    ],
  },
  {
    url: "https://softwareinspect.com/blog/crm-requirements-checklist",
    domain: "softwareinspect.com",
    organization: "SoftwareInspect",
    title: "CRM Requirements Checklist",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM requirements checklist template",
    verifiedAt: V,
    pageSummary:
      "Guide walking through CRM requirements checklist items for buyer teams.",
    whyTheyMightLink:
      "Content is checklist-centric; SoftwareGlimpse’s CRM requirements template and builder give readers a fillable artifact instead of only reading checklist prose.",
    relevantSgPage: "/resources/crm-requirements-template/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "moderate",
    effort: "small",
    likelihood: "high",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Requirements checklist guide verified 2026-08-15."],
  },
  {
    url: "https://kynetto.com/crm-implementation-plan/",
    domain: "kynetto.com",
    organization: "Kynetto",
    title: "CRM Implementation Plan",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM implementation checklist SMB",
    verifiedAt: V,
    pageSummary:
      "CRM implementation plan overview covering phases, ownership, and rollout considerations.",
    whyTheyMightLink:
      "Plan narrative needs executable planning tools; CRM implementation planner and checklist let readers turn the article’s phases into a concrete project plan.",
    relevantSgPage: "/tools/crm-implementation-planner/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["Implementation plan page verified 2026-08-15."],
  },
  {
    url: "https://softabase.com/guides/crm-implementation-checklist",
    domain: "softabase.com",
    organization: "Softabase",
    title: "CRM Implementation Checklist",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM implementation checklist SMB",
    verifiedAt: V,
    pageSummary:
      "Guide-style CRM implementation checklist covering readiness through go-live.",
    whyTheyMightLink:
      "Checklist guide readers expect downloadable companions; SoftwareGlimpse’s implementation checklist and training plan cover go-live readiness gaps the guide outlines.",
    relevantSgPage: "/resources/crm-implementation-checklist/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Softabase implementation checklist verified 2026-08-15."],
  },
  {
    url: "https://www.empat.tech/blog/crm-implementation-guide-2026",
    domain: "empat.tech",
    organization: "Empat",
    title: "CRM Implementation Guide 2026",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM implementation checklist SMB",
    verifiedAt: V,
    pageSummary:
      "2026 CRM implementation guide covering planning, change management, and rollout.",
    whyTheyMightLink:
      "Guide readers planning 2026 rollouts benefit from a free implementation planner and demo checklist when comparing vendor pilots described in the article.",
    relevantSgPage: "/tools/crm-implementation-planner/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["2026 implementation guide verified 2026-08-15."],
  },
  {
    url: "https://maciejturek.com/resources/crm-implementation-checklist-2026.html",
    domain: "maciejturek.com",
    organization: "Maciej Turek",
    title: "CRM Implementation Checklist 2026",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM implementation checklist SMB",
    verifiedAt: V,
    pageSummary:
      "Standalone 2026 CRM implementation checklist resource page.",
    whyTheyMightLink:
      "Author publishes checklist resources; linking SoftwareGlimpse’s maintained implementation checklist and migration checklist expands the resource set for practitioners following the 2026 checklist.",
    relevantSgPage: "/resources/crm-implementation-checklist/",
    seoValue: "low",
    referralValue: "good",
    difficulty: "easy",
    effort: "trivial",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Personal checklist resource verified 2026-08-15."],
  },
  {
    url: "https://www.nextpageit.com/blog/crm-migration-checklist",
    domain: "nextpageit.com",
    organization: "Next Page IT",
    title: "CRM Migration Checklist",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM migration checklist data migration",
    verifiedAt: V,
    pageSummary:
      "Blog checklist covering CRM migration planning and cutover considerations.",
    whyTheyMightLink:
      "Migration checklist posts pair well with free field-mapping and data-migration templates; SoftwareGlimpse’s migration planner fills the planning-tool gap beside the article’s steps.",
    relevantSgPage: "/tools/crm-migration-planner/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Migration checklist blog verified 2026-08-15."],
  },
  {
    url: "https://blog.hubspot.com/marketing/crm-data-migration",
    domain: "blog.hubspot.com",
    organization: "HubSpot",
    title: "CRM Data Migration Guide",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM migration checklist data migration",
    verifiedAt: V,
    pageSummary:
      "HubSpot marketing blog guide to CRM data migration best practices and planning.",
    whyTheyMightLink:
      "Vendor education still benefits from vendor-neutral planning artifacts; SoftwareGlimpse’s data migration template and field-mapping template help readers prepare source data before any HubSpot (or other) migration.",
    relevantSgPage: "/resources/crm-data-migration-template/",
    seoValue: "excellent",
    referralValue: "strong",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: [
      "HubSpot migration guide live 2026-08-15; complementary vendor-neutral angle only.",
    ],
  },
  {
    url: "https://www.digitalapplied.com/blog/crm-data-migration-checklist-2026-zero-downtime-playbook",
    domain: "digitalapplied.com",
    organization: "Digital Applied",
    title: "CRM Data Migration Checklist 2026 — Zero-Downtime Playbook",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM migration checklist data migration",
    verifiedAt: V,
    pageSummary:
      "2026 CRM data migration checklist framed as a zero-downtime playbook.",
    whyTheyMightLink:
      "Playbook emphasizes cutover discipline; SoftwareGlimpse’s migration checklist and migration planner give readers operational worksheets aligned with zero-downtime sequencing.",
    relevantSgPage: "/resources/crm-migration-checklist/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Zero-downtime migration playbook verified 2026-08-15."],
  },
  {
    url: "https://www.migratetomonday.com/resources/blog/crm-migration-checklist/",
    domain: "migratetomonday.com",
    organization: "Migrate to Monday",
    title: "CRM Migration Checklist",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM migration checklist data migration",
    verifiedAt: V,
    pageSummary:
      "CRM migration checklist resource aimed at teams moving CRM data (including toward Monday.com).",
    whyTheyMightLink:
      "Even vendor-leaning migration content needs neutral prep tools; field-mapping and data-migration templates help readers inventory fields before any destination platform choice.",
    relevantSgPage: "/resources/crm-field-mapping-template/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Migrate-to-Monday checklist verified 2026-08-15."],
  },
  {
    url: "https://rivery.io/data-learning-center/complete-data-migration-checklist/",
    domain: "rivery.io",
    organization: "Rivery",
    title: "Complete Data Migration Checklist",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM migration checklist data migration",
    verifiedAt: V,
    pageSummary:
      "Data learning-center checklist covering end-to-end data migration practices (applicable to CRM moves).",
    whyTheyMightLink:
      "General migration checklist readers doing CRM cutovers benefit from CRM-specific field-mapping and migration planner tools that specialize Rivery’s broader data guidance.",
    relevantSgPage: "/tools/crm-migration-planner/",
    seoValue: "strong",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Rivery data migration checklist verified 2026-08-15; complementary CRM-specific angle.",
    ],
  },
  {
    url: "https://gain.io/blog/crm-buying-checklist-evaluation",
    domain: "gain.io",
    organization: "Gain",
    title: "CRM Buying Checklist / Evaluation",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM buying checklist evaluation scorecard",
    verifiedAt: V,
    pageSummary:
      "CRM buying checklist article that discusses evaluation criteria and weighted scorecard thinking.",
    whyTheyMightLink:
      "Article already mentions weighted scorecards; SoftwareGlimpse’s vendor scorecard tool and evaluation checklist are the interactive/downloadable counterparts to that advice.",
    relevantSgPage: "/tools/crm-vendor-scorecard/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "moderate",
    effort: "small",
    likelihood: "high",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Buying checklist mentions weighted scorecard framing (2026-08-15).",
    ],
  },
  {
    url: "https://topickz.com/guides/sales/how-to-evaluate-crm-software/",
    domain: "topickz.com",
    organization: "Topickz",
    title: "How to Evaluate CRM Software",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM buying checklist evaluation scorecard",
    verifiedAt: V,
    pageSummary:
      "Buyer guide on evaluating CRM software with scorecard-oriented evaluation framing.",
    whyTheyMightLink:
      "Evaluation guide readers need a place to score vendors; CRM vendor scorecard and evaluation checklist turn the guide’s criteria into a usable worksheet.",
    relevantSgPage: "/resources/crm-vendor-scorecard/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["CRM evaluation scorecard article verified 2026-08-15."],
  },
  {
    url: "https://complivex.com/checklists/crm-evaluation-checklist",
    domain: "complivex.com",
    organization: "Complivex",
    title: "CRM Evaluation Checklist",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM evaluation checklist complementary resources",
    verifiedAt: V,
    pageSummary:
      "Dedicated CRM evaluation checklist page for software selection teams.",
    whyTheyMightLink:
      "Checklist publishers routinely cite complementary free checklists; SoftwareGlimpse’s evaluation checklist and RFP template deepen the evaluation workflow beyond a single static list.",
    relevantSgPage: "/resources/crm-evaluation-checklist/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Complivex evaluation checklist verified 2026-08-15."],
  },
  {
    url: "https://officeatlas.org/software/crm-evaluation-template/",
    domain: "officeatlas.org",
    organization: "Office Atlas",
    title: "CRM Evaluation Template",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM vendor scorecard template",
    verifiedAt: V,
    pageSummary:
      "CRM evaluation template page aimed at teams documenting vendor comparisons.",
    whyTheyMightLink:
      "Template-oriented page can cite additional free evaluation assets; SoftwareGlimpse’s vendor scorecard and business-case template support the same evaluation documentation workflow.",
    relevantSgPage: "/resources/crm-vendor-scorecard/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Office Atlas evaluation template verified 2026-08-15."],
  },
  {
    url: "https://nex365.com/vendor-scorecard-template-rate-your-crm-and-micro-app-vendor",
    domain: "nex365.com",
    organization: "Nex365",
    title: "Vendor Scorecard Template — Rate Your CRM and Micro-App Vendor",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM vendor scorecard template",
    verifiedAt: V,
    pageSummary:
      "Vendor scorecard template article for rating CRM and related micro-app vendors.",
    whyTheyMightLink:
      "Scorecard article audiences want a CRM-specific interactive scorecard; SoftwareGlimpse’s CRM vendor scorecard tool specializes the generic vendor-rating advice for CRM selection.",
    relevantSgPage: "/tools/crm-vendor-scorecard/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "moderate",
    effort: "small",
    likelihood: "high",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Nex365 vendor scorecard template verified 2026-08-15."],
  },
  {
    url: "https://assembly.com/blog/crm-requirements",
    domain: "assembly.com",
    organization: "Assembly",
    title: "CRM Requirements",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM requirements checklist template",
    verifiedAt: V,
    pageSummary:
      "Article on capturing CRM requirements before purchasing or implementing a system.",
    whyTheyMightLink:
      "Requirements-focused editorial fits a free requirements template and builder so readers leave with a structured requirements pack rather than only narrative tips.",
    relevantSgPage: "/resources/crm-requirements-template/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["Assembly CRM requirements article verified 2026-08-15."],
  },
  {
    url: "https://www.insightly.com/blog/crm_needs_assessment/",
    domain: "insightly.com",
    organization: "Insightly",
    title: "CRM Needs Assessment",
    type: "REFERENCE_LINK",
    discoveryQuery: "how to choose CRM small business checklist",
    verifiedAt: V,
    pageSummary:
      "Vendor blog on CRM needs assessment for teams defining what they need before buying.",
    whyTheyMightLink:
      "Needs-assessment content is stronger when paired with vendor-neutral requirements tools; SoftwareGlimpse’s requirements builder helps readers document needs before any Insightly (or competitor) demo.",
    relevantSgPage: "/tools/crm-requirements-builder/",
    seoValue: "strong",
    referralValue: "good",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Needs assessment post verified 2026-08-15; complementary neutral-tools angle.",
    ],
  },
  {
    url: "https://www.bigcontacts.com/blog/how-to-choose-crm-small-business/",
    domain: "bigcontacts.com",
    organization: "BigContacts",
    title: "How to Choose a CRM for Small Business",
    type: "REFERENCE_LINK",
    discoveryQuery: "how to choose CRM small business checklist",
    verifiedAt: V,
    pageSummary:
      "SMB guide to choosing CRM software with practical selection advice.",
    whyTheyMightLink:
      "SMB choose-CRM guides pair naturally with CRM Finder and the how-to-choose-CRM guide so readers can filter options after reading the high-level criteria.",
    relevantSgPage: "/guides/how-to-choose-crm/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["SMB choose-CRM blog verified 2026-08-15."],
  },
  {
    url: "https://www.gestisoft.com/en/blog/crm-software-selection",
    domain: "gestisoft.com",
    organization: "Gestisoft",
    title: "CRM Software Selection",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM buying checklist evaluation scorecard",
    verifiedAt: V,
    pageSummary:
      "CRM software selection guide that discusses comparison matrices for vendor shortlists.",
    whyTheyMightLink:
      "Matrix-oriented selection advice maps directly to SoftwareGlimpse’s vendor scorecard and evaluation checklist as the worksheets behind the matrix discussion.",
    relevantSgPage: "/tools/crm-vendor-scorecard/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Selection guide mentions comparison matrix framing (2026-08-15).",
    ],
  },
  {
    url: "https://www.endurego.com.au/crm/",
    domain: "endurego.com.au",
    organization: "EndureGo",
    title: "CRM Guide for Australian SMBs",
    type: "REFERENCE_LINK",
    discoveryQuery: "how to choose CRM small business checklist",
    verifiedAt: V,
    pageSummary:
      "Australian SMB CRM guide including checklist-style tables for selection considerations.",
    whyTheyMightLink:
      "Checklist table audiences benefit from free evaluation checklist and cost calculator resources that extend the on-page table into reusable buyer tools.",
    relevantSgPage: "/resources/crm-evaluation-checklist/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Aussie SMB CRM page with checklist table verified 2026-08-15.",
    ],
  },
  {
    url: "https://www.wetechtalk.com/software-buying-guide-how-to-choose-the-right-software/",
    domain: "wetechtalk.com",
    organization: "We Tech Talk",
    title: "Software Buying Guide — How to Choose the Right Software",
    type: "REFERENCE_LINK",
    discoveryQuery: "how to choose CRM small business checklist",
    verifiedAt: V,
    pageSummary:
      "General software buying guide covering evaluation process for business software purchases.",
    whyTheyMightLink:
      "Buying-guide readers evaluating CRM specifically can be pointed to CRM Finder and the CRM RFP template as category-specific tools within a generic software-selection narrative.",
    relevantSgPage: "/tools/crm-finder/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["Software buying guide verified 2026-08-15."],
  },
  {
    url: "https://singleclic.com/crm-selection-checklist/",
    domain: "singleclic.com",
    organization: "Singleclic",
    title: "CRM Selection Checklist",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM buying checklist evaluation scorecard",
    verifiedAt: V,
    pageSummary:
      "CRM selection checklist that cites external resources for buyers.",
    whyTheyMightLink:
      "Page already cites external resources; SoftwareGlimpse’s evaluation checklist and vendor scorecard are natural additional citations for selection teams following the checklist.",
    relevantSgPage: "/resources/crm-evaluation-checklist/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "moderate",
    effort: "small",
    likelihood: "high",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Selection checklist cites external resources (2026-08-15).",
    ],
  },
  {
    url: "https://saascrmreview.com/best-free-crm-software/",
    domain: "saascrmreview.com",
    organization: "SaaS CRM Review",
    title: "Best Free CRM Software",
    type: "TOOL_CITATION",
    discoveryQuery: "best free CRM software 2026",
    verifiedAt: V,
    pageSummary:
      "Roundup of best free CRM software options for buyers comparing zero-cost tiers.",
    whyTheyMightLink:
      "Free-CRM lists help readers discover products but not evaluate fit; citing CRM Finder as an evaluation helper lets readers filter free options against requirements after reading the list.",
    relevantSgPage: "/tools/crm-finder/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["Free CRM roundup verified 2026-08-15."],
  },
  {
    url: "https://techverifiers.com/crm/best-free-crm-2026",
    domain: "techverifiers.com",
    organization: "Tech Verifiers",
    title: "Best Free CRM 2026",
    type: "TOOL_CITATION",
    discoveryQuery: "best free CRM software 2026",
    verifiedAt: V,
    pageSummary:
      "2026 best free CRM roundup comparing free-plan CRM products.",
    whyTheyMightLink:
      "Product roundups pair well with a cost calculator so readers estimate true cost when free tiers force paid upgrades—SoftwareGlimpse’s CRM cost calculator fills that gap.",
    relevantSgPage: "/tools/crm-cost-calculator/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["Best free CRM 2026 page verified 2026-08-15."],
  },
  {
    url: "https://usefulstack.com/best-free-crm-tools-in-2026-tested-with-real-clients/",
    domain: "usefulstack.com",
    organization: "Useful Stack",
    title: "Best Free CRM Tools in 2026 (Tested with Real Clients)",
    type: "TOOL_CITATION",
    discoveryQuery: "best free CRM software 2026",
    verifiedAt: V,
    pageSummary:
      "Hands-on 2026 free CRM tools roundup tested with real client scenarios.",
    whyTheyMightLink:
      "Client-tested roundups still leave readers to match tools to requirements; CRM Finder and demo checklist help readers structure their own trials after reading the tests.",
    relevantSgPage: "/tools/crm-finder/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["Useful Stack free CRM 2026 verified 2026-08-15."],
  },
  {
    url: "https://zapier.com/blog/best-free-crm/",
    domain: "zapier.com",
    organization: "Zapier",
    title: "Best Free CRM",
    type: "TOOL_CITATION",
    discoveryQuery: "best free CRM software 2026",
    verifiedAt: V,
    pageSummary:
      "Zapier editorial roundup of best free CRM tools with integration-oriented context.",
    whyTheyMightLink:
      "Zapier’s free-CRM roundup is product-centric; citing CRM Finder and cost calculator as complementary evaluation tools helps readers shortlist and budget beyond feature bullets.",
    relevantSgPage: "/tools/crm-finder/",
    seoValue: "excellent",
    referralValue: "excellent",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Zapier free CRM roundup verified 2026-08-15; complementary tool-citation angle.",
    ],
  },
  {
    url: "https://www.zdnet.com/article/best-free-crm-software/",
    domain: "zdnet.com",
    organization: "ZDNET",
    title: "Best Free CRM Software",
    type: "TOOL_CITATION",
    discoveryQuery: "best free CRM software 2026",
    verifiedAt: V,
    pageSummary:
      "ZDNET editorial comparing best free CRM software options for businesses.",
    whyTheyMightLink:
      "Journalist roundups often link practical buyer tools; CRM Finder and evaluation checklist give ZDNET readers a next step after product picks.",
    relevantSgPage: "/tools/crm-finder/",
    seoValue: "excellent",
    referralValue: "strong",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "accept",
    evidenceNotes: ["ZDNET free CRM article verified 2026-08-15."],
  },
  {
    url: "https://crmcalc.com/",
    domain: "crmcalc.com",
    organization: "CRMCalc",
    title: "CRM Calculators Hub",
    type: "COMPETITOR_LINK_GAP",
    discoveryQuery: "CRM cost calculator TCO",
    verifiedAt: V,
    pageSummary:
      "Hub of CRM calculators covering cost and related buyer math for CRM purchases.",
    whyTheyMightLink:
      "Competing calculator hubs sometimes cite alternative methodologies; SoftwareGlimpse’s cost calculator uses a distinct methodology that can sit as a complementary “compare approaches” link rather than a clone.",
    relevantSgPage: "/tools/crm-cost-calculator/",
    seoValue: "strong",
    referralValue: "good",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    competitorGapClass: "COMPLEMENTARY",
    competitorAssetUrl: "https://crmcalc.com/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "CRMCalc hub verified 2026-08-15; complementary distinct-methodology angle.",
    ],
  },
  {
    url: "https://crmcalc.com/calculators/tco",
    domain: "crmcalc.com",
    organization: "CRMCalc",
    title: "CRM TCO Calculator",
    type: "TOOL_CITATION",
    discoveryQuery: "CRM cost calculator TCO",
    verifiedAt: V,
    pageSummary:
      "Dedicated CRM total-cost-of-ownership calculator page on CRMCalc.",
    whyTheyMightLink:
      "TCO pages can reference alternate TCO models; SoftwareGlimpse’s CRM TCO calculator offers a second methodology for readers validating CRMCalc outputs.",
    relevantSgPage: "/tools/crm-tco-calculator/",
    seoValue: "strong",
    referralValue: "good",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    competitorGapClass: "COMPLEMENTARY",
    competitorAssetUrl: "https://crmcalc.com/calculators/tco",
    provisionalDecision: "accept",
    evidenceNotes: ["CRMCalc TCO page verified 2026-08-15."],
  },
  {
    url: "https://ecosire.com/tools/crm-cost-calculator",
    domain: "ecosire.com",
    organization: "Ecosire",
    title: "CRM Cost Calculator",
    type: "COMPETITOR_LINK_GAP",
    discoveryQuery: "CRM cost calculator TCO",
    verifiedAt: V,
    pageSummary:
      "Competitor CRM cost calculator tool page for estimating CRM spend.",
    whyTheyMightLink:
      "Complementary citation works when methodologies differ; SoftwareGlimpse’s cost calculator and TCO calculator give Ecosire readers a second estimate for cross-checking assumptions.",
    relevantSgPage: "/tools/crm-cost-calculator/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    competitorGapClass: "COMPLEMENTARY",
    competitorAssetUrl: "https://ecosire.com/tools/crm-cost-calculator",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Ecosire cost calculator verified 2026-08-15; complementary only.",
    ],
  },
  {
    url: "https://perimattic.com/tools/software/crm-calculator/",
    domain: "perimattic.com",
    organization: "Perimattic",
    title: "CRM Calculator",
    type: "TOOL_CITATION",
    discoveryQuery: "CRM cost calculator TCO",
    verifiedAt: V,
    pageSummary:
      "Software CRM calculator tool for estimating CRM-related costs.",
    whyTheyMightLink:
      "Calculator pages often list related tools; SoftwareGlimpse’s cost and TCO calculators are complementary estimator options with different input models.",
    relevantSgPage: "/tools/crm-cost-calculator/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    competitorAssetUrl: "https://perimattic.com/tools/software/crm-calculator/",
    provisionalDecision: "accept",
    evidenceNotes: ["Perimattic CRM calculator verified 2026-08-15."],
  },
  {
    url: "https://thespinnakergroupinc.com/crm-implementation-total-cost-calculator/",
    domain: "thespinnakergroupinc.com",
    organization: "The Spinnaker Group",
    title: "CRM Implementation Total Cost Calculator",
    type: "TOOL_CITATION",
    discoveryQuery: "CRM cost calculator TCO",
    verifiedAt: V,
    pageSummary:
      "Implementation-focused total cost calculator for CRM rollout budgeting.",
    whyTheyMightLink:
      "Implementation cost calculators pair with SoftwareGlimpse’s TCO calculator and implementation planner so readers connect dollar estimates to a phased rollout plan.",
    relevantSgPage: "/tools/crm-tco-calculator/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Spinnaker implementation cost calculator verified 2026-08-15.",
    ],
  },
  {
    url: "https://www.thegtmadvisor.com/blog/revops-playbook-templates",
    domain: "thegtmadvisor.com",
    organization: "The GTM Advisor",
    title: "RevOps Playbook Templates",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "RevOps playbook templates tech stack",
    verifiedAt: V,
    pageSummary:
      "RevOps SOP / playbook templates article that mentions tech stack evaluation.",
    whyTheyMightLink:
      "Tech-stack evaluation SOPs need CRM selection tooling; vendor scorecard and CRM Finder help RevOps teams evaluate CRM within the broader stack playbooks described.",
    relevantSgPage: "/tools/crm-vendor-scorecard/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: [
      "RevOps playbook templates mention tech stack evaluation (2026-08-15).",
    ],
  },
  {
    url: "https://www.revenueopsllc.com/best-revops-toolkit/",
    domain: "revenueopsllc.com",
    organization: "RevenueOps LLC",
    title: "Best RevOps Toolkit",
    type: "RESOURCE_PAGE",
    discoveryQuery: "RevOps playbook templates tech stack",
    verifiedAt: V,
    pageSummary:
      "RevOps toolkit roundup highlighting templates and operational resources.",
    whyTheyMightLink:
      "Toolkit pages curate practical assets; SoftwareGlimpse’s requirements template and evaluation checklist fit as free CRM-selection toolkit items for RevOps operators.",
    relevantSgPage: "/resources/crm-requirements-template/",
    seoValue: "good",
    referralValue: "strong",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["RevOps toolkit page verified 2026-08-15."],
  },
  {
    url: "https://github.com/shubham1502-hue/revops-infrastructure-playbook",
    domain: "github.com",
    organization: "GitHub (community playbook)",
    title: "RevOps Infrastructure Playbook",
    type: "COMMUNITY",
    discoveryQuery: "RevOps playbook templates tech stack",
    verifiedAt: V,
    pageSummary:
      "Open RevOps infrastructure playbook covering CRM hygiene and related ops practices.",
    whyTheyMightLink:
      "Open playbook covering CRM hygiene can reference free evaluation and implementation checklists as companion docs for teams improving CRM data quality and process.",
    relevantSgPage: "/resources/crm-implementation-checklist/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "easy",
    effort: "small",
    likelihood: "medium",
    contactPath:
      "https://github.com/shubham1502-hue/revops-infrastructure-playbook/issues — or open a Pull Request",
    submissionPath:
      "Open https://github.com/shubham1502-hue/revops-infrastructure-playbook → Issues or PR adding a Resources link in the README",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Public GitHub RevOps playbook with CRM hygiene verified 2026-08-15.",
    ],
  },
  {
    url: "https://www.score.org/twincities/event/growing-your-business-a-crm-14",
    domain: "score.org",
    organization: "SCORE Twin Cities",
    title: "Growing Your Business: A CRM (SCORE webinar)",
    type: "ACADEMIC_EDUCATIONAL",
    discoveryQuery: "CRM implementation educational .edu OR site:.gov",
    verifiedAt: V,
    pageSummary:
      "SCORE educational webinar event page on growing a business with CRM for small businesses.",
    whyTheyMightLink:
      "SCORE education pages often list free attendee resources; what-is-CRM guide and evaluation checklist are appropriate post-webinar handouts for SMB owners.",
    relevantSgPage: "/guides/what-is-crm/",
    seoValue: "strong",
    referralValue: "strong",
    difficulty: "hard",
    effort: "medium",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: ["SCORE Twin Cities CRM webinar page verified 2026-08-15."],
  },
  {
    url: "https://www.sba.gov/blog/3-biggest-problems-implementing-crm-system-what-do-about-them",
    domain: "sba.gov",
    organization: "U.S. Small Business Administration",
    title: "3 Biggest Problems Implementing a CRM System — and What to Do About Them",
    type: "ACADEMIC_EDUCATIONAL",
    discoveryQuery: "CRM implementation educational .edu OR site:.gov",
    verifiedAt: V,
    pageSummary:
      "SBA educational blog on common CRM implementation problems and practical remedies for small businesses.",
    whyTheyMightLink:
      "SBA implementation advice can cite free implementation checklist and training plan resources so small-business readers leave with actionable worksheets.",
    relevantSgPage: "/resources/crm-implementation-checklist/",
    seoValue: "excellent",
    referralValue: "excellent",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "accept",
    evidenceNotes: ["SBA CRM implementation blog verified 2026-08-15."],
  },
  {
    url: "https://www.excelsior.edu/article/what-is-a-crm-system/",
    domain: "excelsior.edu",
    organization: "Excelsior University",
    title: "What Is a CRM System?",
    type: "ACADEMIC_EDUCATIONAL",
    discoveryQuery: "CRM implementation educational .edu OR site:.gov",
    verifiedAt: V,
    pageSummary:
      "Educational .edu explainer defining CRM systems for learners and career audiences.",
    whyTheyMightLink:
      "Introductory CRM explainers often link glossary and further-reading guides; SoftwareGlimpse’s what-is-CRM guide and CRM glossary extend the article for students needing deeper definitions.",
    relevantSgPage: "/guides/what-is-crm/",
    seoValue: "strong",
    referralValue: "good",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    provisionalDecision: "accept",
    evidenceNotes: ["Excelsior.edu CRM explainer verified 2026-08-15."],
  },
  {
    url: "https://www.calbright.edu/programs/crm/",
    domain: "calbright.edu",
    organization: "Calbright College",
    title: "Calbright CRM Program",
    type: "ACADEMIC_EDUCATIONAL",
    discoveryQuery: "CRM implementation educational .edu OR site:.gov",
    verifiedAt: V,
    pageSummary:
      "Calbright educational program page related to CRM skills and career pathways.",
    whyTheyMightLink:
      "Program pages can point learners to free practice tools; CRM glossary and evaluation checklist support coursework on CRM concepts and selection basics.",
    relevantSgPage: "/guides/crm-glossary/",
    seoValue: "strong",
    referralValue: "good",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    provisionalDecision: "accept",
    evidenceNotes: ["Calbright CRM program page verified 2026-08-15."],
  },
  {
    url: "https://www.academia.edu/33654314/Sample_CRM_Requirements_Document",
    domain: "academia.edu",
    organization: "Academia.edu",
    title: "Sample CRM Requirements Document",
    type: "ACADEMIC_EDUCATIONAL",
    discoveryQuery: "sample CRM requirements document academia",
    verifiedAt: V,
    pageSummary:
      "Academic upload of a sample CRM requirements document for research/education use.",
    whyTheyMightLink:
      "Sample requirements docs are stronger with a modern fillable template; SoftwareGlimpse’s CRM requirements template and builder give students an updated companion to the sample document.",
    relevantSgPage: "/resources/crm-requirements-template/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "low",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Academia.edu sample CRM requirements document verified 2026-08-15.",
    ],
  },
  {
    url: "https://notes.io/qXt2q",
    domain: "notes.io",
    organization: "Notes.io",
    title: "Notes.io page mentioning softwareglimpse.com",
    type: "UNLINKED_MENTION",
    discoveryQuery: "softwareglimpse.com CRM mention",
    verifiedAt: V,
    pageSummary:
      "Public notes page that mentions softwareglimpse.com without a proper contextual resource link set.",
    whyTheyMightLink:
      "Unlinked brand mention can be upgraded to a contextual link to CRM Finder or how-to-choose-CRM where the note discusses CRM evaluation—turning a mention into an editorial citation.",
    relevantSgPage: "/tools/crm-finder/",
    seoValue: "low",
    referralValue: "low",
    difficulty: "easy",
    effort: "trivial",
    likelihood: "medium",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Unlinked mention of softwareglimpse.com observed live 2026-08-15.",
    ],
  },
  {
    url: "https://www.spotsaas.com/resources/crm-software/setup-checklist",
    domain: "spotsaas.com",
    organization: "SpotSaaS",
    title: "CRM Software Setup Checklist",
    type: "RESOURCE_PAGE",
    discoveryQuery: "CRM evaluation checklist complementary resources",
    verifiedAt: V,
    pageSummary:
      "CRM setup checklist resource with related CRM resources navigation for buyers.",
    whyTheyMightLink:
      "Related-resources nav can include complementary evaluation tools; SoftwareGlimpse’s evaluation checklist and implementation checklist extend setup content into selection and rollout.",
    relevantSgPage: "/resources/crm-evaluation-checklist/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: [
      "SpotSaaS setup checklist with related CRM resources nav verified 2026-08-15.",
    ],
  },
  {
    url: "https://checklist.com/crm-checklist",
    domain: "checklist.com",
    organization: "Checklist.com",
    title: "CRM Checklist",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM evaluation checklist complementary resources",
    verifiedAt: V,
    pageSummary:
      "Generic CRM checklist page covering common CRM-related task lists.",
    whyTheyMightLink:
      "Generic CRM checklists benefit from linking a specialized evaluation checklist so buyers who land on ops checklists can also run a structured vendor evaluation.",
    relevantSgPage: "/resources/crm-evaluation-checklist/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "moderate",
    effort: "small",
    likelihood: "medium",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: ["Checklist.com CRM checklist verified 2026-08-15."],
  },
  {
    url: "https://hellogrowthcrm.com/templates/audit/crm-migration-checklist",
    domain: "hellogrowthcrm.com",
    organization: "Hello Growth CRM",
    title: "CRM Migration Checklist Template",
    type: "COMPETITOR_LINK_GAP",
    discoveryQuery: "CRM migration checklist data migration",
    verifiedAt: V,
    pageSummary:
      "Competitor CRM migration checklist template aimed at migration audits.",
    whyTheyMightLink:
      "Complementary citation: SoftwareGlimpse’s migration checklist and field-mapping template cover adjacent artifacts (mapping + planner) rather than duplicating the same downloadable checklist.",
    relevantSgPage: "/resources/crm-field-mapping-template/",
    seoValue: "good",
    referralValue: "good",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    competitorGapClass: "COMPLEMENTARY",
    competitorAssetUrl:
      "https://hellogrowthcrm.com/templates/audit/crm-migration-checklist",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Hello Growth migration template verified 2026-08-15; complementary adjacent assets only.",
    ],
  },
  {
    url: "https://www.vtiger.com/blog/crm-checklist/",
    domain: "vtiger.com",
    organization: "Vtiger",
    title: "CRM Checklist",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM evaluation checklist complementary resources",
    verifiedAt: V,
    pageSummary:
      "Vtiger CRM checklist blog including an evaluation checklist section among other CRM checklists.",
    whyTheyMightLink:
      "Evaluation checklist section can cite a vendor-neutral evaluation checklist and demo checklist so readers prepare for any vendor demo—not only Vtiger’s.",
    relevantSgPage: "/resources/crm-evaluation-checklist/",
    seoValue: "strong",
    referralValue: "good",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Vtiger checklist post with evaluation section verified 2026-08-15.",
    ],
  },
  {
    url: "https://www.pipedrive.com/en/crm/resources/crm-checklist",
    domain: "pipedrive.com",
    organization: "Pipedrive",
    title: "CRM Checklist (Pipedrive resources)",
    type: "RESOURCE_PAGE",
    discoveryQuery: "CRM deployment checklist HubSpot Pipedrive",
    verifiedAt: V,
    pageSummary:
      "Pipedrive CRM checklist resource for buyers and implementers within Pipedrive’s resource hub.",
    whyTheyMightLink:
      "Vendor resource hubs sometimes link vendor-neutral planning tools; SoftwareGlimpse’s CRM Readiness Assessment and evaluation checklist help readers prepare before committing to any CRM—including Pipedrive.",
    relevantSgPage: "/tools/crm-readiness-assessment/",
    seoValue: "excellent",
    referralValue: "strong",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Pipedrive CRM checklist resource verified 2026-08-15; complementary neutral tools only.",
    ],
  },
  {
    url: "https://blog.hubspot.com/marketing/crm-deployment",
    domain: "blog.hubspot.com",
    organization: "HubSpot",
    title: "CRM Deployment Guide",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM deployment checklist HubSpot Pipedrive",
    verifiedAt: V,
    pageSummary:
      "HubSpot CRM deployment guide with a templates section for deployment planning.",
    whyTheyMightLink:
      "Templates section is a natural home for complementary vendor-neutral implementation checklist and training plan links that help any CRM deployment—not only HubSpot’s stack.",
    relevantSgPage: "/resources/crm-implementation-checklist/",
    seoValue: "excellent",
    referralValue: "strong",
    difficulty: "hard",
    effort: "medium",
    likelihood: "low",
    competitorGapClass: "COMPLEMENTARY",
    provisionalDecision: "accept",
    evidenceNotes: [
      "HubSpot deployment guide templates section verified 2026-08-15.",
    ],
  },

  // ── REJECT (18) ──────────────────────────────────────────────────────────
  {
    url: "https://flevy.com/browse/marketplace/100-revops-revenue-operations-sops-12008",
    domain: "flevy.com",
    organization: "Flevy",
    title: "100 RevOps / Revenue Operations SOPs (marketplace)",
    type: "PAID_CONTENT_DISTRIBUTION",
    discoveryQuery: "RevOps playbook templates tech stack",
    verifiedAt: V,
    pageSummary:
      "Paid marketplace listing selling a RevOps SOP pack — commercial content marketplace, not editorial resource curation.",
    whyTheyMightLink:
      "Not a fit: paid document marketplace monetizes downloads rather than editorially citing free complementary buyer tools.",
    seoValue: "low",
    referralValue: "none",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Paid link scheme",
    rejectNotes: "Paid marketplace / paid content distribution — not earned editorial.",
    evidenceNotes: ["Flevy marketplace listing verified 2026-08-15."],
  },
  {
    url: "https://matthew.iws.edu/templates/crm-evaluation-template.html",
    domain: "matthew.iws.edu",
    organization: "matthew.iws.edu (template farm)",
    title: "CRM Evaluation Template (thin SEO template page)",
    type: "TEMPLATE_CITATION",
    discoveryQuery: "CRM vendor scorecard template",
    verifiedAt: V,
    pageSummary:
      "Thin, spammy template-farm page aggregating keyword-stuffed CRM evaluation template copy with low editorial quality.",
    whyTheyMightLink:
      "Rejected: low-quality SEO farm; no trustworthy editorial path for a SoftwareGlimpse citation.",
    seoValue: "none",
    referralValue: "none",
    difficulty: "easy",
    effort: "trivial",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Spammy",
    rejectNotes: "Low-quality SEO template farm — do not pursue.",
    evidenceNotes: [
      "matthew.iws.edu CRM evaluation template page verified 2026-08-15 as spammy/low quality.",
    ],
  },
  {
    url: "https://www.spotsaas.com/resources/crm-software/scorecard",
    domain: "spotsaas.com",
    organization: "SpotSaaS",
    title: "CRM Software Scorecard (SpotSaaS)",
    type: "COMPETITOR_LINK_GAP",
    discoveryQuery: "CRM vendor scorecard template",
    verifiedAt: V,
    pageSummary:
      "SpotSaaS hosts its own CRM scorecard resource competing directly with SoftwareGlimpse’s vendor scorecard artifact.",
    whyTheyMightLink:
      "Rejected: direct competitor selling/publishing the same scorecard artifact — not complementary.",
    relevantSgPage: "/tools/crm-vendor-scorecard/",
    seoValue: "good",
    referralValue: "low",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    competitorGapClass: "NOT_RELEVANT",
    competitorAssetUrl:
      "https://www.spotsaas.com/resources/crm-software/scorecard",
    provisionalDecision: "reject",
    rejectReason: "Direct competitor selling same artifact",
    rejectNotes: "Own CRM scorecard — not a complementary citation target.",
    evidenceNotes: ["SpotSaaS scorecard page verified 2026-08-15."],
  },
  {
    url: "https://www.netsuite.com/portal/resource/articles/crm/crm-requirements.shtml",
    domain: "netsuite.com",
    organization: "Oracle NetSuite",
    title: "CRM Requirements (NetSuite)",
    type: "VENDOR_ECOSYSTEM",
    discoveryQuery: "CRM requirements checklist template",
    verifiedAt: V,
    pageSummary:
      "NetSuite vendor resource on CRM requirements locked to Oracle NetSuite buying journey.",
    whyTheyMightLink:
      "Rejected: vendor-locked competitor asset promoting NetSuite, not open editorial resource linking.",
    seoValue: "strong",
    referralValue: "low",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    competitorGapClass: "NOT_RELEVANT",
    provisionalDecision: "reject",
    rejectReason: "Vendor-locked competitor asset",
    rejectNotes: "NetSuite-owned requirements content — not earned third-party editorial.",
    evidenceNotes: ["NetSuite CRM requirements article verified 2026-08-15."],
  },
  {
    url: "https://www.salesforce.com/crm/crm-template/",
    domain: "salesforce.com",
    organization: "Salesforce",
    title: "CRM Template (Salesforce)",
    type: "VENDOR_ECOSYSTEM",
    discoveryQuery: "CRM requirements checklist template",
    verifiedAt: V,
    pageSummary:
      "Salesforce CRM template resource promoting Salesforce product ecosystem.",
    whyTheyMightLink:
      "Rejected: vendor-locked Salesforce template property — not a third-party resource list.",
    seoValue: "excellent",
    referralValue: "low",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    competitorGapClass: "NOT_RELEVANT",
    provisionalDecision: "reject",
    rejectReason: "Vendor-locked competitor asset",
    rejectNotes: "Salesforce product template — vendor-locked.",
    evidenceNotes: ["Salesforce CRM template page verified 2026-08-15."],
  },
  {
    url: "https://www.airtable.com/templates/sales-crm/expaRDyCNa7YNZQoO",
    domain: "airtable.com",
    organization: "Airtable",
    title: "Sales CRM Template (Airtable)",
    type: "VENDOR_ECOSYSTEM",
    discoveryQuery: "CRM requirements checklist template",
    verifiedAt: V,
    pageSummary:
      "Airtable product template for a sales CRM base — marketplace product template, not an editorial resource list.",
    whyTheyMightLink:
      "Rejected: vendor-locked product template in Airtable’s template gallery, not an editorial citation opportunity.",
    seoValue: "strong",
    referralValue: "none",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Vendor-locked competitor asset",
    rejectNotes: "Airtable product template — not editorial resource curation.",
    evidenceNotes: ["Airtable sales CRM template verified 2026-08-15."],
  },
  {
    url: "https://www.insightly.com/blog/crm-templates/",
    domain: "insightly.com",
    organization: "Insightly",
    title: "CRM Templates (Insightly blog)",
    type: "VENDOR_ECOSYSTEM",
    discoveryQuery: "CRM requirements checklist template",
    verifiedAt: V,
    pageSummary:
      "Insightly blog promoting CRM templates in service of Insightly’s product.",
    whyTheyMightLink:
      "Rejected: vendor-locked content promoting Insightly templates — not a neutral resource list.",
    seoValue: "good",
    referralValue: "low",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Vendor-locked competitor asset",
    rejectNotes: "Insightly-promoting templates blog — vendor-locked.",
    evidenceNotes: ["Insightly CRM templates blog verified 2026-08-15."],
  },
  {
    url: "https://medium.com/@software_glimpse/pipedrive-crm-review-and-ratings-2023-softwareglimpse-com-bdc4f53654be",
    domain: "medium.com",
    organization: "Software Glimpse (own Medium)",
    title: "Pipedrive CRM Review — softwareglimpse.com (Medium)",
    type: "EARNED_EDITORIAL_LINK",
    discoveryQuery: "softwareglimpse.com CRM mention",
    verifiedAt: V,
    pageSummary:
      "Medium republication under @software_glimpse — SoftwareGlimpse’s own property, not a third-party earned opportunity.",
    whyTheyMightLink:
      "Rejected: own Medium publication / not third-party earned media.",
    seoValue: "none",
    referralValue: "none",
    difficulty: "easy",
    effort: "trivial",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Own property / not third-party",
    rejectNotes: "Owned Medium account @software_glimpse.",
    evidenceNotes: ["Own Medium post verified 2026-08-15."],
  },
  {
    url: "https://www.softwareglimpse.com/",
    domain: "softwareglimpse.com",
    organization: "SoftwareGlimpse",
    title: "SoftwareGlimpse homepage",
    type: "EARNED_EDITORIAL_LINK",
    discoveryQuery: "softwareglimpse.com CRM mention",
    verifiedAt: V,
    pageSummary: "SoftwareGlimpse’s own website — not a third-party opportunity.",
    whyTheyMightLink:
      "Rejected: own property; earned discovery must target third-party sites.",
    seoValue: "none",
    referralValue: "none",
    difficulty: "easy",
    effort: "trivial",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Own property / not third-party",
    rejectNotes: "Primary own domain.",
    evidenceNotes: ["Own homepage excluded 2026-08-15."],
  },
  {
    url: "https://www.tryglimpse.com/",
    domain: "tryglimpse.com",
    organization: "Glimpse (unrelated)",
    title: "Glimpse (tryglimpse.com)",
    type: "EARNED_EDITORIAL_LINK",
    discoveryQuery: "softwareglimpse.com CRM mention",
    verifiedAt: V,
    pageSummary:
      "Unrelated company brand “Glimpse” — not SoftwareGlimpse and not a CRM evaluation resource publisher.",
    whyTheyMightLink:
      "Rejected: irrelevant brand collision; different product/company entirely.",
    seoValue: "none",
    referralValue: "none",
    difficulty: "easy",
    effort: "trivial",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Irrelevant",
    rejectNotes: "Different company (Glimpse) — not CRM editorial fit.",
    evidenceNotes: ["tryglimpse.com verified as unrelated 2026-08-15."],
  },
  {
    url: "https://www.technologyevaluation.com/selection-tools/rfp/56986/crm-requirements-checklist",
    domain: "technologyevaluation.com",
    organization: "Technology Evaluation Centers (TEC)",
    title: "CRM Requirements Checklist (TEC)",
    type: "PAID_DIRECTORY",
    discoveryQuery: "CRM requirements checklist template",
    verifiedAt: V,
    pageSummary:
      "TEC gated / lead-gen selection tool for CRM requirements — paid/commercial research model.",
    whyTheyMightLink:
      "Rejected: paid/gated lead-gen selection tool, not free earned editorial placement.",
    seoValue: "good",
    referralValue: "none",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Paid link scheme",
    rejectNotes: "TEC paid/gated lead-gen — not earned free citation path.",
    evidenceNotes: ["TEC CRM requirements checklist verified 2026-08-15."],
  },
  {
    url: "https://www.linkedin.com/pulse/crm-evaluation-checklist-what-look-software-sugarcrm-u5lff",
    domain: "linkedin.com",
    organization: "SugarCRM (LinkedIn Pulse)",
    title: "CRM Evaluation Checklist — SugarCRM Pulse",
    type: "VENDOR_ECOSYSTEM",
    discoveryQuery: "CRM buying checklist evaluation scorecard",
    verifiedAt: V,
    pageSummary:
      "LinkedIn Pulse article from SugarCRM framing evaluation checklist around SugarCRM messaging.",
    whyTheyMightLink:
      "Rejected: vendor-locked SugarCRM content, not neutral third-party resource curation.",
    seoValue: "good",
    referralValue: "low",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Vendor-locked competitor asset",
    rejectNotes: "SugarCRM Pulse article — vendor-locked.",
    evidenceNotes: ["LinkedIn SugarCRM evaluation checklist verified 2026-08-15."],
  },
  {
    url: "https://norex.growthzoneapp.com/ap/CloudFile/Download/zLwMKN0p",
    domain: "norex.growthzoneapp.com",
    organization: "NOREX / GrowthZone",
    title: "Members-only CloudFile download",
    type: "DIRECTORY",
    discoveryQuery: "CRM evaluation checklist complementary resources",
    verifiedAt: V,
    pageSummary:
      "Members-only file download dump with no public editorial page or citation context.",
    whyTheyMightLink:
      "Rejected: no public editorial surface or submission route — opaque download endpoint.",
    seoValue: "none",
    referralValue: "none",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "No editorial value",
    rejectNotes: "Members-only download dump — no editorial page to cite from.",
    evidenceNotes: ["GrowthZone CloudFile download verified 2026-08-15."],
  },
  {
    url: "https://documentation.suse.com/sle-ha/12-SP5/html/SLE-HA-all/cha-ha-manual-config.html",
    domain: "documentation.suse.com",
    organization: "SUSE",
    title: "Configuring Cluster Resources (CRM Shell) — SLE HA",
    type: "REFERENCE_LINK",
    discoveryQuery: "CRM implementation educational .edu OR site:.gov",
    verifiedAt: V,
    pageSummary:
      "SUSE Linux High Availability docs for Cluster Resource Manager (crmsh) — Linux HA, not Customer Relationship Management.",
    whyTheyMightLink:
      "Rejected: homonym CRM (Cluster Resource Manager) — irrelevant to SoftwareGlimpse CRM buyer tools.",
    seoValue: "strong",
    referralValue: "none",
    difficulty: "easy",
    effort: "trivial",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Irrelevant",
    rejectNotes: "Linux HA CRM shell documentation — wrong CRM meaning.",
    evidenceNotes: [
      "SUSE SLE-HA cha-ha-manual-config.html verified 2026-08-15 as HA CRM, not SaaS CRM.",
    ],
  },
  {
    url: "https://www.sba.gov/document/report-customer-relationship-management-crm",
    domain: "sba.gov",
    organization: "U.S. Small Business Administration",
    title: "SBA CRM Privacy Impact Assessment document",
    type: "ACADEMIC_EDUCATIONAL",
    discoveryQuery: "CRM implementation educational .edu OR site:.gov",
    verifiedAt: V,
    pageSummary:
      "SBA internal Privacy Impact Assessment / report document about SBA’s own CRM system — not an educational buyer resource.",
    whyTheyMightLink:
      "Rejected: internal SBA PIA/report document, not educational content for CRM software buyers.",
    seoValue: "low",
    referralValue: "none",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Irrelevant",
    rejectNotes: "SBA internal CRM PIA/report — not educational buyer guidance.",
    evidenceNotes: ["SBA CRM document page verified 2026-08-15."],
  },
  {
    url: "https://cbinsights.com/company/american-association-of-inside-sales-professionals",
    domain: "cbinsights.com",
    organization: "CB Insights",
    title: "AA-ISP company profile (CB Insights)",
    type: "DIRECTORY",
    discoveryQuery: "Revenue Operations Alliance community",
    verifiedAt: V,
    pageSummary:
      "Thin CB Insights directory profile of an association — no member resource library or submission route for tool citations.",
    whyTheyMightLink:
      "Rejected: directory profile only; no editorial resource list or submission path.",
    seoValue: "low",
    referralValue: "none",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "No actual submission route",
    rejectNotes: "CB Insights company profile — no submission/editorial route.",
    evidenceNotes: ["CB Insights AA-ISP profile verified 2026-08-15."],
  },
  {
    url: "https://jobstars.com/professional-associations/emblaze/",
    domain: "jobstars.com",
    organization: "JobStars",
    title: "Emblaze association listing (JobStars)",
    type: "DIRECTORY",
    discoveryQuery: "Revenue Enablement Society resources",
    verifiedAt: V,
    pageSummary:
      "Thin professional-association listing page with minimal content and no resource curation.",
    whyTheyMightLink:
      "Rejected: low-quality thin directory page without editorial depth or clear contact path for resource citations.",
    seoValue: "none",
    referralValue: "none",
    difficulty: "easy",
    effort: "trivial",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Low quality",
    rejectNotes: "Thin association listing — insufficient editorial quality.",
    evidenceNotes: ["JobStars Emblaze page verified 2026-08-15."],
  },
  {
    url: "https://www.notion.com/templates/sales-operations-crm",
    domain: "notion.com",
    organization: "Notion",
    title: "Sales Operations CRM Template (Notion)",
    type: "VENDOR_ECOSYSTEM",
    discoveryQuery: "RevOps playbook templates tech stack",
    verifiedAt: V,
    pageSummary:
      "Notion template marketplace listing for a sales operations CRM template — product marketplace, not editorial.",
    whyTheyMightLink:
      "Rejected: vendor-locked Notion marketplace template, not a third-party editorial resource list.",
    seoValue: "strong",
    referralValue: "none",
    difficulty: "very-hard",
    effort: "large",
    likelihood: "very-low",
    provisionalDecision: "reject",
    rejectReason: "Vendor-locked competitor asset",
    rejectNotes: "Notion marketplace template — vendor-locked product surface.",
    evidenceNotes: ["Notion sales ops CRM template verified 2026-08-15."],
  },
];

export function assertLiveHitsPresent(hits: LiveSearchHit[]): void {
  if (hits.length === 0) {
    throw new Error(
      "Earned live hits are empty — live web search verification is required before qualifying opportunities.",
    );
  }
}
