import type { CrmDecisionProfile } from "@/domain";
import {
  BUDGET_OPTIONS,
  COMPANY_SIZE_OPTIONS,
  INTEGRATION_OPTIONS,
  labelForOption,
} from "@/components/finder/crm-finder-questions";
import {
  listSelectableCapabilitiesForProfile,
  listSelectableUseCasesForProfile,
  profileTitleForExport,
  resolveRequirementMetaForProfile,
  usersLabelForProfile,
} from "./category-helpers";
import { buildProfileCompleteness } from "./completeness";

function featureLabel(slug: string): string {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export function profileToPlainTextSummary(profile: CrmDecisionProfile): string {
  const lines: string[] = [profileTitleForExport(profile), ""];
  const usersLabel = usersLabelForProfile(profile);

  const bc = profile.businessContext;
  lines.push("BUSINESS");
  if (bc.industrySlug) lines.push(`Industry: ${bc.industrySlug}`);
  if (bc.companySizeSlug) {
    lines.push(
      `Company size: ${labelForOption(COMPANY_SIZE_OPTIONS, bc.companySizeSlug)}`,
    );
  }
  if (bc.crmUserCount != null) lines.push(`${usersLabel}: ${bc.crmUserCount}`);
  if (bc.teamIds.length) lines.push(`Primary teams: ${bc.teamIds.join(", ")}`);
  if (bc.currentState) lines.push(`Current state: ${bc.currentState}`);
  lines.push("");

  const useCases = listSelectableUseCasesForProfile(profile);
  lines.push("USE CASES");
  for (const u of profile.useCases) {
    const name = useCases.find((x) => x.slug === u.id)?.name ?? u.id;
    lines.push(`- [${u.priority}] ${name}`);
  }
  lines.push("");

  const caps = listSelectableCapabilitiesForProfile(profile);
  lines.push("CAPABILITIES");
  for (const c of profile.capabilities) {
    const name = caps.find((x) => x.slug === c.id)?.name ?? c.id;
    lines.push(`- [${c.priority}] ${name}`);
  }
  lines.push("");

  lines.push("REQUIREMENTS");
  for (const group of ["must-have", "important", "nice-to-have"] as const) {
    const items = profile.requirements.filter((r) => r.priority === group);
    if (!items.length) continue;
    lines.push(group.toUpperCase());
    for (const r of items) {
      const meta = resolveRequirementMetaForProfile(profile, r.id);
      lines.push(`- ${meta?.name ?? r.id}`);
    }
  }
  lines.push("");

  lines.push("FEATURES");
  for (const group of ["must-have", "important", "nice-to-have"] as const) {
    const items = profile.features.filter((f) => f.priority === group);
    if (!items.length) continue;
    lines.push(group.toUpperCase());
    for (const f of items) {
      lines.push(`- ${featureLabel(f.id)}`);
    }
  }
  lines.push("");

  if (profile.integrations.length) {
    lines.push("INTEGRATIONS");
    for (const i of profile.integrations) {
      lines.push(
        `- [${i.priority}] ${labelForOption(INTEGRATION_OPTIONS, i.id) || i.id}`,
      );
    }
    lines.push("");
  }

  lines.push("CONSTRAINTS");
  if (profile.budget.band) {
    lines.push(
      `Budget: ${labelForOption(BUDGET_OPTIONS, profile.budget.band)}`,
    );
  }
  if (profile.budget.billingPreference) {
    lines.push(`Billing: ${profile.budget.billingPreference}`);
  }
  if (profile.implementation.complexity) {
    lines.push(`Implementation: ${profile.implementation.complexity}`);
  }
  if (profile.implementation.migrationComplexity) {
    lines.push(`Migration: ${profile.implementation.migrationComplexity}`);
  }

  const completeness = buildProfileCompleteness(profile);
  lines.push("");
  lines.push("COMPLETENESS");
  for (const s of completeness.sections) {
    lines.push(`- ${s.label}: ${s.status}`);
  }

  lines.push("");
  if (profile.categorySlug === "sales-intelligence") {
    lines.push(
      "Generated by SoftwareGlimpse Sales Intelligence Requirements Builder",
    );
  } else {
    lines.push("Generated by SoftwareGlimpse CRM Requirements Builder");
  }
  lines.push("Affiliate relationships do not influence this profile.");

  return lines.join("\n");
}

export function profileToJsonExport(profile: CrmDecisionProfile): string {
  return JSON.stringify(profile, null, 2);
}

export function profileToCsvChecklist(profile: CrmDecisionProfile): string {
  const rows = [["type", "id", "name", "priority", "source"]];
  for (const r of profile.requirements) {
    if (r.priority === "not-needed") continue;
    const meta = resolveRequirementMetaForProfile(profile, r.id);
    rows.push([
      "requirement",
      r.id,
      meta?.name ?? r.id,
      r.priority,
      r.source,
    ]);
  }
  for (const f of profile.features) {
    rows.push([
      "feature",
      f.id,
      featureLabel(f.id),
      f.priority,
      f.source,
    ]);
  }
  for (const i of profile.integrations) {
    rows.push([
      "integration",
      i.id,
      labelForOption(INTEGRATION_OPTIONS, i.id) || i.id,
      i.priority,
      "user-selected",
    ]);
  }
  return rows
    .map((row) =>
      row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(","),
    )
    .join("\n");
}
