import {
  WorkflowDefinitionSchema,
  type WorkflowDefinition,
} from "@/domain";

export const categoryContentWorkflow: WorkflowDefinition =
  WorkflowDefinitionSchema.parse({
    id: "category-onboarding-content",
    version: "1.0.0",
    name: "Category Onboarding Content",
    targetType: "category",
    completionPolicy: {
      requireAllRequired: true,
      allowOptionalBlocked: true,
      stopAfterApproval: true,
      publishAfterApproval: false,
    },
    steps: [
      {
        id: "category-onboarding",
        handler: "category-onboarding",
        required: true,
        failurePolicy: "block-workflow",
        priority: "critical",
        label: "Category onboarding",
        config: {},
      },
      {
        id: "category-hub",
        handler: "agent-run",
        dependsOn: ["category-onboarding"],
        required: true,
        failurePolicy: "block-workflow",
        priority: "high",
        label: "Category Hub",
        approval: { type: "editorial", required: true },
        config: { agentId: "category-hub-agent", maxAutomaticRevisions: 1 },
      },
      {
        id: "best-software",
        handler: "agent-run",
        dependsOn: ["category-onboarding"],
        required: false,
        failurePolicy: "continue-with-warning",
        priority: "normal",
        label: "Best Software",
        approval: { type: "editorial", required: true },
        config: {
          agentId: "best-software-agent",
          optionalWhenBlocked: true,
          maxAutomaticRevisions: 1,
        },
      },
      {
        id: "use-cases",
        handler: "agent-run",
        dependsOn: ["category-onboarding"],
        required: false,
        failurePolicy: "continue-with-warning",
        priority: "low",
        label: "Use-Case Pages",
        config: {
          agentId: "use-case-page-agent",
          expandKind: "use-cases",
          optionalWhenBlocked: true,
        },
      },
      {
        id: "internal-links",
        handler: "internal-link",
        dependsOn: ["category-hub"],
        required: false,
        failurePolicy: "continue-with-warning",
        priority: "low",
        label: "Internal Link Plan",
        config: { agentId: "internal-link-agent" },
      },
      {
        id: "editorial-approval",
        handler: "approval-check",
        dependsOn: ["category-hub"],
        required: true,
        failurePolicy: "manual-review",
        priority: "critical",
        label: "Editorial approval",
        approval: { type: "editorial", required: true },
        config: { approvalType: "editorial", stopAfterApproval: true },
      },
    ],
  });
