import {
  WorkflowDefinitionSchema,
  type WorkflowDefinition,
} from "@/domain";

/**
 * Software onboarding → content generation workflow v1.
 * Publication remains approval-controlled (stopAfterApproval default).
 */
export const softwareOnboardingContentWorkflow: WorkflowDefinition =
  WorkflowDefinitionSchema.parse({
    id: "software-onboarding-content",
    version: "1.0.0",
    name: "Software Onboarding Content",
    targetType: "software",
    maxAgentTasksPerRun: 10,
    completionPolicy: {
      requireAllRequired: true,
      allowOptionalBlocked: true,
      stopAfterApproval: true,
      scheduleAfterApproval: false,
      publishAfterApproval: false,
    },
    steps: [
      {
        id: "software-onboarding",
        handler: "software-onboarding",
        required: true,
        failurePolicy: "block-workflow",
        priority: "critical",
        label: "Software onboarding",
        config: {},
      },
      {
        id: "content-plan",
        handler: "content-plan",
        dependsOn: ["software-onboarding"],
        required: true,
        failurePolicy: "block-workflow",
        priority: "high",
        label: "Content plan",
        config: {},
      },
      {
        id: "software-review",
        handler: "agent-run",
        dependsOn: ["content-plan"],
        required: true,
        failurePolicy: "block-workflow",
        priority: "high",
        label: "Software Review",
        approval: { type: "editorial", required: true },
        config: {
          agentId: "software-review-agent",
          maxAutomaticRevisions: 1,
        },
      },
      {
        id: "pricing-page",
        handler: "agent-run",
        dependsOn: ["content-plan"],
        required: false,
        failurePolicy: "continue-with-warning",
        priority: "normal",
        label: "Pricing Page",
        approval: { type: "editorial", required: true },
        config: {
          agentId: "pricing-page-agent",
          optionalWhenBlocked: true,
          maxAutomaticRevisions: 1,
        },
      },
      {
        id: "alternatives",
        handler: "agent-run",
        dependsOn: ["content-plan"],
        required: false,
        failurePolicy: "continue-with-warning",
        priority: "normal",
        label: "Alternatives",
        approval: { type: "editorial", required: true },
        config: {
          agentId: "alternatives-agent",
          optionalWhenBlocked: true,
          maxAutomaticRevisions: 1,
        },
      },
      {
        id: "comparisons",
        handler: "agent-run",
        dependsOn: ["content-plan"],
        required: false,
        failurePolicy: "continue-with-warning",
        priority: "normal",
        label: "Comparisons",
        approval: { type: "editorial", required: true },
        config: {
          agentId: "comparison-agent",
          expandKind: "comparisons",
          expandFromContentPlan: true,
          optionalWhenBlocked: true,
          maxAutomaticRevisions: 1,
        },
      },
      {
        id: "internal-links",
        handler: "internal-link",
        dependsOn: ["software-review"],
        required: false,
        failurePolicy: "continue-with-warning",
        priority: "low",
        label: "Internal Link Plan",
        config: {
          agentId: "internal-link-agent",
        },
      },
      {
        id: "finder-readiness",
        handler: "update-recommendation-readiness",
        dependsOn: ["content-plan"],
        required: false,
        failurePolicy: "continue",
        priority: "low",
        label: "Finder readiness",
        config: {},
      },
      {
        id: "editorial-approval",
        handler: "approval-check",
        dependsOn: ["software-review"],
        required: true,
        failurePolicy: "manual-review",
        priority: "critical",
        label: "Editorial approval",
        approval: { type: "editorial", required: true },
        config: {
          approvalType: "editorial",
          stopAfterApproval: true,
        },
      },
      {
        id: "pre-publish-validation",
        handler: "pre-publish-validation",
        dependsOn: ["editorial-approval"],
        required: true,
        failurePolicy: "block-workflow",
        priority: "critical",
        label: "Pre-publish validation",
        config: {},
      },
    ],
  });
