import type {
  SoftwareAssetMasterReport,
  SoftwareProductAssetAudit,
} from "@/domain/schemas/asset-discovery";
import { recommendationLevelLabel } from "./rating";

function sectionHeading(title: string): string {
  return `## ${title}\n`;
}

function renderAsset(
  asset: SoftwareProductAssetAudit["recommendations"][number],
  index: number,
): string {
  const lines: string[] = [];
  lines.push(`### Asset ${index}: ${asset.title}`);
  lines.push("");
  lines.push(`- **Type:** ${asset.assetType}`);
  lines.push(
    `- **Priority:** ${recommendationLevelLabel(asset.recommendationLevel)}`,
  );
  lines.push(
    `- **Official source:** ${asset.officialSource ? "yes (verified)" : "pending / search required"}`,
  );
  lines.push(`- **URL:** ${asset.sourceUrl ?? "_none yet — run search tasks; do not invent_"}`);
  lines.push(
    `- **What it shows:** ${asset.whatItShows.length ? asset.whatItShows.join("; ") : "_TBD after discovery_"}`,
  );
  lines.push(`- **Freshness:** ${asset.freshnessStatus}`);
  lines.push(`- **Embed status:** ${asset.embedStatus}`);
  lines.push(
    `- **Usage recommendation:** ${asset.usageRecommendation ?? "n/a"}`,
  );
  if (asset.placement) {
    lines.push(
      `- **Recommended placement:** \`${asset.placement.pageRoute}\` → **${asset.placement.sectionTitle}**${asset.placement.subsection ? ` → ${asset.placement.subsection}` : ""}`,
    );
    lines.push(`- **Recommended use:** ${asset.placement.recommendedUse}`);
    lines.push(`- **Why:** ${asset.placement.why}`);
  }
  if (asset.featureIds.length) {
    lines.push(`- **Related Feature(s):** ${asset.featureIds.join(", ")}`);
  }
  if (asset.capabilityIds.length) {
    lines.push(`- **Related Capability(ies):** ${asset.capabilityIds.join(", ")}`);
  }
  if (asset.requirementIds.length) {
    lines.push(
      `- **Related Requirement(s):** ${asset.requirementIds.join(", ")}`,
    );
  }
  if (asset.useCaseIds.length) {
    lines.push(`- **Related Use Case(s):** ${asset.useCaseIds.join(", ")}`);
  }
  if (asset.industryIds.length) {
    lines.push(`- **Related Industry(ies):** ${asset.industryIds.join(", ")}`);
  }
  if (asset.reuseOfMediaId) {
    lines.push(`- **Reuse ResearchMedia id:** \`${asset.reuseOfMediaId}\``);
  }
  if (asset.searchQueries.length) {
    lines.push(`- **Search queries:**`);
    for (const q of asset.searchQueries) {
      lines.push(`  - \`${q}\``);
    }
  }
  lines.push(`- **Reason:** ${asset.reason}`);
  lines.push("");
  return lines.join("\n");
}

/**
 * Per-product markdown for docs/content-assets/software/[slug]-asset-opportunities.md
 */
export function formatSoftwareProductAssetMarkdown(
  audit: SoftwareProductAssetAudit,
): string {
  const lines: string[] = [];
  lines.push(`# ${audit.productName} Asset Opportunities`);
  lines.push("");
  lines.push(
    `> Generated by **SoftwareAssetDiscoveryAgent** \`${audit.agentVersion}\` — recommendations only. Does **not** edit product pages.`,
  );
  lines.push("");
  lines.push(`- **Product:** \`${audit.productSlug}\``);
  lines.push(`- **Route:** ${audit.route}`);
  lines.push(`- **Generated:** ${audit.generatedAt}`);
  lines.push(
    `- **Media coverage rating:** **${audit.coverageRating}** — ${audit.coverageReason}`,
  );
  lines.push("");
  lines.push("## Current media coverage");
  lines.push("");
  lines.push(
    `| Official videos | Screenshots | Official sources | Reuse | ADD NOW | Strong | Stale |`,
  );
  lines.push(`| ---: | ---: | ---: | ---: | ---: | ---: | ---: |`);
  lines.push(
    `| ${audit.currentOfficialVideoCount} | ${audit.currentScreenshotCount} | ${audit.currentOfficialSourceCount} | ${audit.summary.reuseExisting} | ${audit.summary.addNow} | ${audit.summary.strongOpportunity} | ${audit.summary.staleCount} |`,
  );
  lines.push("");
  if (audit.currentMedia.length) {
    lines.push("### Existing ResearchMedia (reuse — do not duplicate)");
    lines.push("");
    for (const m of audit.currentMedia) {
      lines.push(
        `- **${m.title}** (\`${m.mediaId}\`) — ${m.type}; placements: ${m.placements.join(", ") || "—"}; features: ${m.featureIds.join(", ") || "—"}${m.sourceUrl ? `; ${m.sourceUrl}` : ""}`,
      );
    }
    lines.push("");
  } else {
    lines.push("_No active official ResearchMedia on enrichment._");
    lines.push("");
  }

  lines.push(
    `### Major features searched`,
  );
  lines.push(
    audit.majorFeaturesSearched.length
      ? audit.majorFeaturesSearched.map((f) => `\`${f}\``).join(", ")
      : "_none_",
  );
  lines.push("");
  lines.push(`### Use cases searched`);
  lines.push(
    audit.useCasesSearched.length
      ? audit.useCasesSearched.map((u) => `\`${u}\``).join(", ")
      : "_none_",
  );
  lines.push("");
  lines.push(`### Industries searched`);
  lines.push(
    audit.industriesSearched.length
      ? audit.industriesSearched.map((i) => `\`${i}\``).join(", ")
      : "_none (do not force industry media)_",
  );
  lines.push("");

  for (const section of audit.sections) {
    lines.push(sectionHeading(section.sectionTitle));
    lines.push("**Current:**");
    lines.push("");
    if (section.current.length) {
      for (const c of section.current) lines.push(`- ${c}`);
    } else {
      lines.push("- _Nothing recorded_");
    }
    lines.push("");
    lines.push("**Gaps / opportunities:**");
    lines.push("");
    if (section.gaps.length) {
      for (const g of section.gaps) lines.push(`- ${g}`);
    } else {
      lines.push("- _No critical gaps flagged_");
    }
    lines.push("");
    let i = 1;
    for (const opp of section.opportunities) {
      lines.push(renderAsset(opp, i++));
    }
  }

  lines.push("## Assets to avoid");
  lines.push("");
  for (const a of audit.assetsToAvoid) {
    lines.push(`- **${a.title}** — ${a.reason}`);
  }
  lines.push("");

  lines.push("## Original SoftwareGlimpse visuals worth creating");
  lines.push("");
  if (!audit.originalVisualOpportunities.length) {
    lines.push("_None flagged._");
  } else {
    for (const o of audit.originalVisualOpportunities) {
      lines.push(`### ${o.title}`);
      lines.push("");
      lines.push(`- **Priority:** ${o.priority}`);
      lines.push(`- **Description:** ${o.description}`);
      if (o.basedOnSourceHint) {
        lines.push(`- **Ground in:** ${o.basedOnSourceHint}`);
      }
      if (o.relatedFeatureIds.length) {
        lines.push(`- **Features:** ${o.relatedFeatureIds.join(", ")}`);
      }
      if (o.relatedUseCaseIds.length) {
        lines.push(`- **Use cases:** ${o.relatedUseCaseIds.join(", ")}`);
      }
      lines.push("");
    }
  }

  if (audit.staleAssets.length) {
    lines.push("## Stale media (refresh)");
    lines.push("");
    for (const s of audit.staleAssets) {
      lines.push(
        `- **${s.title}** (\`${s.mediaId}\`) — ${s.kind}: ${s.detail}`,
      );
      lines.push(`  - Refresh: ${s.refreshRecommendation}`);
    }
    lines.push("");
  }

  lines.push("## Recommended implementation order");
  lines.push("");
  if (!audit.implementationOrder.length) {
    lines.push("_No prioritized actions — coverage may already be adequate._");
  } else {
    audit.implementationOrder.forEach((step, idx) => {
      lines.push(`${idx + 1}. ${step}`);
    });
  }
  lines.push("");

  lines.push("## Open search tasks");
  lines.push("");
  lines.push(
    "_Queries only — prefer vendor site / docs / help / academy / official YouTube. Do not prioritize third-party review sites. Do not invent URLs._",
  );
  lines.push("");
  for (const t of audit.searchTasks.slice(0, 40)) {
    lines.push(`- \`${t.query}\``);
  }
  if (audit.searchTasks.length > 40) {
    lines.push(`- _…and ${audit.searchTasks.length - 40} more_`);
  }
  lines.push("");

  lines.push("## Notes");
  lines.push("");
  for (const n of audit.notes) lines.push(`- ${n}`);
  lines.push("");

  return `${lines.join("\n")}\n`;
}

export function formatSoftwareAssetMasterMarkdown(
  report: SoftwareAssetMasterReport,
): string {
  const lines: string[] = [];
  lines.push(`# Software Asset Opportunities`);
  lines.push("");
  lines.push(
    `> Master report from **SoftwareAssetDiscoveryAgent** \`${report.agentVersion}\`. Recommendations only — does not edit product pages.`,
  );
  lines.push("");
  lines.push(`- **Generated:** ${report.generatedAt}`);
  lines.push(`- **Products audited:** ${report.productsAudited}`);
  lines.push(
    `- **Totals:** ADD NOW ${report.totals.addNow} · Strong ${report.totals.strongOpportunity} · Reuse ${report.totals.reuseExisting} · Stale ${report.totals.staleAssets} · Original visuals ${report.totals.originalVisualOpportunities} · Official videos catalogued ${report.totals.officialVideosCatalogued}`,
  );
  lines.push("");
  lines.push(
    `| Product | Current media score | Official videos found | Screenshot opportunities | Product-tour opportunities | Implementation media | Industry media | Priority opportunities | Stale assets | Recommended next action |`,
  );
  lines.push(
    `| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |`,
  );
  for (const row of report.rows) {
    lines.push(
      `| [${row.productName}](./software/${row.productSlug}-asset-opportunities.md) | ${row.coverageRating} | ${row.officialVideosFound} | ${row.screenshotOpportunities} | ${row.productTourOpportunities} | ${row.implementationMedia} | ${row.industryMedia} | ${row.priorityOpportunities} | ${row.staleAssets} | ${row.recommendedNextAction} |`,
    );
  }
  lines.push("");
  lines.push("## Rating guide");
  lines.push("");
  lines.push(
    "Coverage is **qualitative** (excellent / strong / adequate / weak / very-weak) — not a raw asset count.",
  );
  lines.push("");
  lines.push("## Next steps");
  lines.push("");
  lines.push(
    "1. Open per-product reports under `docs/content-assets/software/`",
  );
  lines.push(
    "2. Execute ADD NOW search tasks against official vendor sources only",
  );
  lines.push(
    "3. Bridge verified videos into ResearchMedia lifecycle (never auto-publish)",
  );
  lines.push(
    "4. Create original SoftwareGlimpse diagrams where usage rights advise against rehosting",
  );
  lines.push("");
  return `${lines.join("\n")}\n`;
}
