import type { CrmImplementationPlan } from "@/domain";
import { ROLE_LABELS } from "./risks";
import { planCompletionPercent, openRiskCount } from "./persistence";

export function planToPlainText(plan: CrmImplementationPlan): string {
  const lines: string[] = [];
  lines.push("CRM IMPLEMENTATION PLAN — SoftwareGlimpse");
  lines.push("=".repeat(48));
  lines.push(
    plan.productName
      ? `CRM: ${plan.productName}`
      : plan.vendorNeutral
        ? "CRM: Vendor-neutral plan"
        : "CRM: Not selected",
  );
  if (plan.targetGoLive) lines.push(`Target go-live: ${plan.targetGoLive}`);
  if (plan.planningDurationWeeks) {
    lines.push(
      `Estimated planning duration: approximately ${plan.planningDurationWeeks} weeks (planning model based on entered scope — not a vendor-certified estimate)`,
    );
  }
  if (plan.scope.users) lines.push(`Users: ${plan.scope.users}`);
  if (plan.complexity) lines.push(`Complexity: ${plan.complexity.level}`);
  lines.push(`Phases: ${plan.phases.filter((p) => p.included).length}`);
  lines.push(`Tasks: ${plan.tasks.length}`);
  lines.push(`Completed: ${planCompletionPercent(plan)}%`);
  lines.push(`Open risks: ${openRiskCount(plan)}`);
  lines.push("");

  if (plan.assumptions.length) {
    lines.push("ASSUMPTIONS");
    for (const a of plan.assumptions) lines.push(`- ${a}`);
    lines.push("");
  }

  lines.push("PHASES & TASKS");
  for (const phase of plan.phases.filter((p) => p.included)) {
    lines.push("");
    lines.push(
      `${phase.order + 1}. ${phase.name} (≈ ${phase.durationWeeks} week(s), weeks ${phase.startWeek}–${phase.endWeek})`,
    );
    const tasks = plan.tasks.filter((t) => t.phaseId === phase.id);
    for (const t of tasks) {
      const owner = t.ownerRole ? ROLE_LABELS[t.ownerRole] : "Unassigned";
      lines.push(
        `  [${t.status}] ${t.title} — ${owner}${t.criticalPath ? " [critical]" : ""}`,
      );
      if (t.reason) lines.push(`    Why: ${t.reason}`);
    }
  }

  if (plan.risks.length) {
    lines.push("");
    lines.push("RISKS");
    for (const r of plan.risks) {
      lines.push(`- [${r.severity}/${r.status}] ${r.title}`);
      lines.push(`  ${r.reason}`);
      lines.push(`  Action: ${r.recommendedAction}`);
    }
  }

  if (plan.goLiveChecklist.length) {
    lines.push("");
    lines.push("GO-LIVE CHECKLIST");
    for (const item of plan.goLiveChecklist) {
      const mark =
        item.status === "done" ? "[x]" : item.status === "not-applicable" ? "[-]" : "[ ]";
      lines.push(`${mark} ${item.label}`);
    }
  }

  if (plan.uatItems.length) {
    lines.push("");
    lines.push("UAT CHECKLIST (must-have requirements)");
    for (const u of plan.uatItems) {
      lines.push(`- [${u.status}] ${u.requirementLabel}`);
      lines.push(`  Scenario: ${u.scenario}`);
      lines.push(`  Expected: ${u.expectedResult}`);
    }
  }

  lines.push("");
  lines.push("Generated by SoftwareGlimpse CRM Implementation Planner");
  lines.push("Affiliate status does not influence this plan.");
  return lines.join("\n");
}

export function planToChecklistCsv(plan: CrmImplementationPlan): string {
  const rows: string[][] = [
    ["section", "id", "title", "status", "owner", "phase", "priority", "source"],
  ];
  for (const phase of plan.phases.filter((p) => p.included)) {
    for (const t of plan.tasks.filter((task) => task.phaseId === phase.id)) {
      rows.push([
        "task",
        t.id,
        t.title,
        t.status,
        t.ownerRole ? ROLE_LABELS[t.ownerRole] : "",
        phase.name,
        t.priority,
        t.sourceType,
      ]);
    }
  }
  for (const item of plan.goLiveChecklist) {
    rows.push([
      "go-live",
      item.id,
      item.label,
      item.status,
      "",
      "Go-Live",
      "",
      "checklist",
    ]);
  }
  for (const r of plan.risks) {
    rows.push([
      "risk",
      r.id,
      r.title,
      r.status,
      r.ownerRole ? ROLE_LABELS[r.ownerRole] : "",
      "",
      r.severity,
      "risk",
    ]);
  }
  return rows
    .map((cols) =>
      cols.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(","),
    )
    .join("\n");
}

export function downloadTextFile(
  filename: string,
  content: string,
  mime = "text/plain;charset=utf-8",
): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
