// Auto-generated by scripts/onboard-affiliate-new-2026-08-26-batch.mjs
// Append via: node scripts/patch-software-seed-affiliate-new-2026-08-26.mjs

  soft({
    id: "soft-turbotic",
    slug: "turbotic",
    name: "Turbotic",
    company: "Turbotic",
    website: "https://turbotic.com",
    logo: { src: "/brands/turbotic.png", alt: "Turbotic logo" },
    shortDescription:
      "Automation AI platform — Free tier; Basic from $14.99/mo annual; Pro from $79.99/mo annual.",
    aliases: ["Turbotic Automation AI"],
    primaryCategorySlug: "ai",
    subcategorySlugs: [],
    useCaseSlugs: ["ai-automation"],
    teamTypeSlugs: ["operations","engineering","marketing"],
    businessSizeSlugs: ["small-business","mid-market","enterprise"],
    competitorSlugs: ["zapier","n8n"],
    alternativeSlugs: ["zapier","n8n"],
    comparableSlugs: ["zapier","n8n"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-26T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
