// Auto-generated by scripts/onboard-affiliate-new-2026-08-26-batch.mjs
// Append via: node scripts/patch-software-seed-affiliate-new-2026-08-26.mjs

  soft({
    id: "soft-cometchat",
    slug: "cometchat",
    name: "CometChat",
    company: "CometChat",
    website: "https://www.cometchat.com",
    logo: { src: "/brands/cometchat.png", alt: "CometChat logo" },
    shortDescription:
      "In-app chat SDK/API with UI kits — Build free (100 MAU); Basic from ~$239/mo annual at 1k MAU tier.",
    aliases: ["Comet Chat"],
    primaryCategorySlug: "live-chat",
    secondaryCategorySlugs: ["customer-service","it-development"],
    subcategorySlugs: [],
    useCaseSlugs: ["live-chat-support","ai-customer-service"],
    teamTypeSlugs: ["engineering","product","customer-success"],
    businessSizeSlugs: ["small-business","mid-market","enterprise"],
    competitorSlugs: ["tidio","intercom","freshchat","livechat"],
    alternativeSlugs: ["tidio","intercom","freshchat"],
    comparableSlugs: ["tidio","freshchat"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-26T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
