// Auto-generated by scripts/onboard-ai-priority3-batch.mjs
// Append via: node scripts/patch-software-seed-ai-priority3.mjs
// AI Priority-3: synthesia, fireflies.

  soft({
    id: "soft-synthesia",
    slug: "synthesia",
    name: "Synthesia",
    company: "Synthesia Ltd.",
    website: "https://www.synthesia.io",
    logo: { src: "/brands/synthesia.png", alt: "Synthesia logo" },
    shortDescription:
      "AI avatar video studio — Basic free (watermark, no MP4); Starter $18/mo annual ($29 monthly); Creator $64/mo annual ($89 monthly); Enterprise quote.",
    aliases: ["Synthesia AI","Synthesia avatars"],
    primaryCategorySlug: "ai",
    subcategorySlugs: [],
    useCaseSlugs: ["ai-video"],
    teamTypeSlugs: ["operations","marketing"],
    businessSizeSlugs: ["small-business","mid-market","enterprise"],
    competitorSlugs: ["runway"],
    alternativeSlugs: ["runway","midjourney"],
    comparableSlugs: ["runway"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-18T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-fireflies",
    slug: "fireflies",
    name: "Fireflies.ai",
    company: "Fireflies.ai",
    website: "https://fireflies.ai",
    logo: { src: "/brands/fireflies.png", alt: "Fireflies.ai logo" },
    shortDescription:
      "AI meeting notes — Free $0 (400 min storage); Pro $10/seat/mo annual ($18 monthly); Business $19 annual ($29 monthly); Enterprise $39 annual-only.",
    aliases: ["Fireflies","Fireflies AI","AskFred"],
    primaryCategorySlug: "ai",
    subcategorySlugs: [],
    useCaseSlugs: ["ai-meeting"],
    teamTypeSlugs: ["operations","sales"],
    businessSizeSlugs: ["solo","small-business","mid-market","enterprise"],
    competitorSlugs: ["otter-ai"],
    alternativeSlugs: ["otter-ai","microsoft-copilot"],
    comparableSlugs: ["otter-ai"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-18T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
