// Auto-generated by scripts/onboard-ai-automation-overlay-batch.mjs
// Append via: node scripts/patch-software-seed-ai-automation-overlay.mjs
// AI automation overlay: zapier, n8n.

  soft({
    id: "soft-zapier",
    slug: "zapier",
    name: "Zapier",
    company: "Zapier, Inc.",
    website: "https://zapier.com",
    logo: { src: "/brands/zapier.png", alt: "Zapier logo" },
    shortDescription:
      "Automation + AI — Free 100 tasks; Pro from $19.99/mo annual (750 tasks); Team from 2,000 tasks; Agents add-on separate.",
    aliases: ["Zapier AI","Zapier Agents","Zaps"],
    primaryCategorySlug: "ai",
    subcategorySlugs: [],
    useCaseSlugs: ["ai-automation"],
    teamTypeSlugs: ["operations","marketing","engineering"],
    businessSizeSlugs: ["solo","micro","small-business","mid-market","enterprise"],
    competitorSlugs: ["n8n","mindstudio"],
    alternativeSlugs: ["n8n","mindstudio"],
    comparableSlugs: ["n8n"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-18T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-n8n",
    slug: "n8n",
    name: "n8n",
    company: "n8n GmbH",
    website: "https://n8n.io",
    logo: { src: "/brands/n8n.png", alt: "n8n logo" },
    shortDescription:
      "Workflow automation — Community self-host free; Cloud Starter €20/mo annual (2.5k executions + AI credits); Pro €50; Business €667; Enterprise quote.",
    aliases: ["n8n Cloud","n8n Community Edition","n8n AI"],
    primaryCategorySlug: "ai",
    subcategorySlugs: [],
    useCaseSlugs: ["ai-automation"],
    teamTypeSlugs: ["engineering","operations"],
    businessSizeSlugs: ["solo","small-business","mid-market","enterprise"],
    competitorSlugs: ["zapier","mindstudio"],
    alternativeSlugs: ["zapier","mindstudio"],
    comparableSlugs: ["zapier"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-18T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
