// Auto-generated by scripts/onboard-ecommerce-priority2b-batch.mjs
// Append into src/data/seed/software.ts via:
//   node scripts/patch-software-seed-ecommerce-priority2b.mjs
// Ecommerce Priority-2b: webflow, lightspeed-retail.

  soft({
    id: "soft-webflow",
    slug: "webflow",
    name: "Webflow",
    company: "Webflow",
    website: "https://webflow.com/",
    logo: { src: "/brands/webflow.png", alt: "Webflow logo" },
    shortDescription:
      "Design-led website platform with Ecommerce — Standard $29/mo (500 items, 2% fee), Plus $74 highlighted (5,000 items, 0% fee), Advanced $212 (15,000 items); requires a Site plan in addition.",
    aliases: ["Webflow Ecommerce","Webflow CMS"],
    primaryCategorySlug: "ecommerce",
    subcategorySlugs: [],
    useCaseSlugs: ["website-builder-commerce","online-storefront"],
    teamTypeSlugs: ["marketing","operations"],
    businessSizeSlugs: ["solo","micro","small-business"],
    competitorSlugs: ["wix","squarespace","shopify"],
    alternativeSlugs: ["wix","squarespace","shopify"],
    comparableSlugs: ["wix","squarespace","shopify"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-18T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-lightspeed-retail",
    slug: "lightspeed-retail",
    name: "Lightspeed Retail",
    company: "Lightspeed",
    website: "https://www.lightspeedhq.com/pos/retail/",
    logo: { src: "/brands/lightspeed-retail.png", alt: "Lightspeed Retail logo" },
    shortDescription:
      "Retail POS + omnichannel — Basic $89/mo, Core $149 highlighted, Plus $289/mo USD; Lightspeed Payments ~1.5% card-present; eCommerce on higher tiers. Distinct from Ecwid.",
    aliases: ["Lightspeed Retail POS","Lightspeed X-Series","Lightspeed POS"],
    primaryCategorySlug: "ecommerce",
    subcategorySlugs: [],
    useCaseSlugs: ["omnichannel-retail","online-storefront"],
    teamTypeSlugs: ["operations","marketing"],
    businessSizeSlugs: ["small-business","mid-market"],
    competitorSlugs: ["square-online","shopify","ecwid"],
    alternativeSlugs: ["square-online","shopify","ecwid"],
    comparableSlugs: ["square-online","shopify","ecwid"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-18T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
