// Auto-generated by scripts/onboard-it-priority3-batch.mjs
// Append via: node scripts/patch-software-seed-it-priority3.mjs
// IT Priority-3: dynatrace, azure-devops.

  soft({
    id: "soft-dynatrace",
    slug: "dynatrace",
    name: "Dynatrace",
    company: "Dynatrace, Inc.",
    website: "https://www.dynatrace.com",
    logo: { src: "/brands/dynatrace.png", alt: "Dynatrace logo" },
    shortDescription:
      "Enterprise observability — Dynatrace Platform Subscription (DPS) annual commit + rate card. Full-Stack list unit ~$58/mo per 8 GiB host; 15-day trial. No per-seat SKU.",
    aliases: ["Dynatrace DPS","Davis AI","Dynatrace Platform"],
    primaryCategorySlug: "it-development",
    subcategorySlugs: [],
    useCaseSlugs: ["observability-monitoring"],
    teamTypeSlugs: ["it-ops","engineering"],
    businessSizeSlugs: ["mid-market","enterprise"],
    competitorSlugs: ["datadog","new-relic","grafana-cloud"],
    alternativeSlugs: ["datadog","new-relic"],
    comparableSlugs: ["datadog","new-relic"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-18T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-azure-devops",
    slug: "azure-devops",
    name: "Azure DevOps",
    company: "Microsoft",
    website: "https://azure.microsoft.com/products/devops/",
    logo: { src: "/brands/azure-devops.png", alt: "Azure DevOps logo" },
    shortDescription:
      "Azure Repos/Boards/Pipelines — first 5 Basic users free, then $6/user/mo; Basic + Test Plans $52/user/mo; Artifacts 2 GiB free.",
    aliases: ["Azure DevOps Services","ADO","Visual Studio Team Services","VSTS"],
    primaryCategorySlug: "it-development",
    subcategorySlugs: [],
    useCaseSlugs: ["source-control-devops"],
    teamTypeSlugs: ["engineering","it-ops"],
    businessSizeSlugs: ["small-business","mid-market","enterprise"],
    competitorSlugs: ["github","gitlab","bitbucket"],
    alternativeSlugs: ["github","gitlab"],
    comparableSlugs: ["github","gitlab"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-18T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
