// Auto-generated by scripts/onboard-it-hosting-providers-batch.mjs
// Append via: node scripts/patch-software-seed-it-hosting-providers.mjs
// IT hosting providers: cloudways, wp-engine.

  soft({
    id: "soft-cloudways",
    slug: "cloudways",
    name: "Cloudways",
    company: "Cloudways Ltd. (DigitalOcean company)",
    website: "https://www.cloudways.com",
    logo: { src: "/brands/cloudways.png", alt: "Cloudways logo" },
    shortDescription:
      "Managed cloud hosting — Flexible from $11/mo DigitalOcean Standard; Autonomous WordPress autoscaling separate line.",
    aliases: ["Cloudways Hosting","Cloudways Autonomous"],
    primaryCategorySlug: "it-development",
    subcategorySlugs: [],
    useCaseSlugs: ["hosting-providers"],
    teamTypeSlugs: ["operations","engineering"],
    businessSizeSlugs: ["micro","small-business","mid-market"],
    competitorSlugs: ["wp-engine","plesk","cpanel"],
    alternativeSlugs: ["wp-engine","plesk"],
    comparableSlugs: ["wp-engine"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-18T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-wp-engine",
    slug: "wp-engine",
    name: "WP Engine",
    company: "WP Engine, Inc.",
    website: "https://wpengine.com",
    logo: { src: "/brands/wp-engine.png", alt: "WP Engine logo" },
    shortDescription:
      "Managed WordPress hosting — Essential Startup from $30/mo annual first-year; Core from $400/mo; Enterprise custom.",
    aliases: ["WPEngine","WP Engine Hosting","WP Engine Core"],
    primaryCategorySlug: "it-development",
    subcategorySlugs: [],
    useCaseSlugs: ["hosting-providers"],
    teamTypeSlugs: ["operations","engineering"],
    businessSizeSlugs: ["small-business","mid-market","enterprise"],
    competitorSlugs: ["cloudways","plesk","cpanel"],
    alternativeSlugs: ["cloudways","plesk"],
    comparableSlugs: ["cloudways"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-18T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
