// Auto-generated SI seed snippet (SI Priority-4 onboarding 2026-08-17)
// Append into src/data/seed/software.ts before the closing ]; of softwareSeed.

  soft({
    id: "soft-adapt-io",
    slug: "adapt-io",
    name: "Adapt.io",
    company: "Adapt.io",
    website: "https://www.adapt.io",
    logo: { src: "/brands/adapt-io.png", alt: "Adapt.io logo" },
    shortDescription:
      "Regional B2B contact database with credit plans — Free; Starter $49/mo; Basic $99/mo; Custom contact sales; 7-day trial.",
    aliases: ["Adapt","Adapt.io"],
    primaryCategorySlug: "sales-intelligence",
    subcategorySlugs: ["contact-data","prospecting"],
    useCaseSlugs: ["prospecting","data-enrichment","contact-management"],
    teamTypeSlugs: ["sales","revops"],
    businessSizeSlugs: ["micro","small-business","mid-market"],
    competitorSlugs: ["uplead","hunter","apollo","lusha","bookyourdata"],
    alternativeSlugs: ["uplead","hunter","apollo","lusha"],
    comparableSlugs: ["uplead","hunter"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-17T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-outreach",
    slug: "outreach",
    name: "Outreach",
    company: "Outreach",
    website: "https://www.outreach.io",
    logo: { src: "/brands/outreach.png", alt: "Outreach logo" },
    shortDescription:
      "Enterprise sales engagement / AI revenue platform — Amplify Essentials/Core/Plus/Pro packages; request pricing (seat + AI credits).",
    aliases: ["Outreach.io","Outreach AI"],
    primaryCategorySlug: "sales-intelligence",
    subcategorySlugs: ["prospecting"],
    useCaseSlugs: ["sales-engagement","prospecting","lead-management"],
    teamTypeSlugs: ["sales","revops"],
    businessSizeSlugs: ["mid-market","enterprise"],
    competitorSlugs: ["salesloft","apollo","reply","gong"],
    alternativeSlugs: ["salesloft","apollo","reply","instantly"],
    comparableSlugs: ["salesloft","apollo"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-17T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-salesloft",
    slug: "salesloft",
    name: "Salesloft",
    company: "Salesloft",
    website: "https://salesloft.com",
    logo: { src: "/brands/salesloft.png", alt: "Salesloft logo" },
    shortDescription:
      "Enterprise sales engagement / revenue generation platform — bi-directional CRM sync, sequencing, coaching; talk-to-sales pricing.",
    primaryCategorySlug: "sales-intelligence",
    subcategorySlugs: ["prospecting"],
    useCaseSlugs: ["sales-engagement","prospecting","lead-management"],
    teamTypeSlugs: ["sales","revops"],
    businessSizeSlugs: ["mid-market","enterprise"],
    competitorSlugs: ["outreach","apollo","reply","gong"],
    alternativeSlugs: ["outreach","apollo","reply","instantly"],
    comparableSlugs: ["outreach","apollo"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-17T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-instantly",
    slug: "instantly",
    name: "Instantly",
    company: "Instantly",
    website: "https://instantly.ai",
    logo: { src: "/brands/instantly.png", alt: "Instantly logo" },
    shortDescription:
      "Cold-email outreach infrastructure — Growth from $47/mo; Hypergrowth $97; Light Speed $358; bundles/credits add-ons; Enterprise custom.",
    aliases: ["Instantly.ai"],
    primaryCategorySlug: "sales-intelligence",
    subcategorySlugs: ["prospecting"],
    useCaseSlugs: ["sales-engagement","prospecting"],
    teamTypeSlugs: ["sales","marketing"],
    businessSizeSlugs: ["micro","small-business","mid-market"],
    competitorSlugs: ["lemlist","smartlead","apollo","outreach"],
    alternativeSlugs: ["lemlist","smartlead","apollo","hunter"],
    comparableSlugs: ["lemlist","smartlead"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-17T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-gong",
    slug: "gong",
    name: "Gong",
    company: "Gong",
    website: "https://www.gong.io",
    logo: { src: "/brands/gong.png", alt: "Gong logo" },
    shortDescription:
      "Conversation intelligence / revenue AI — per-user licenses + platform fee; custom proposal only (no public dollar list).",
    aliases: ["Gong.io","Gong Revenue AI"],
    primaryCategorySlug: "sales-intelligence",
    subcategorySlugs: ["prospecting"],
    useCaseSlugs: ["sales-engagement","lead-management"],
    teamTypeSlugs: ["sales","revops"],
    businessSizeSlugs: ["mid-market","enterprise"],
    competitorSlugs: ["outreach","salesloft","apollo"],
    alternativeSlugs: ["outreach","salesloft","apollo","zoominfo"],
    comparableSlugs: ["outreach","salesloft"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-17T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-lemlist",
    slug: "lemlist",
    name: "Lemlist",
    company: "lemlist",
    website: "https://www.lemlist.com",
    logo: { src: "/brands/lemlist.png", alt: "Lemlist logo" },
    shortDescription:
      "Multichannel cold outreach — Email from $55/user/mo yearly; Multichannel from $87/user/mo yearly; Enterprise custom; 14-day trial.",
    aliases: ["lemlist","Lem List"],
    primaryCategorySlug: "sales-intelligence",
    subcategorySlugs: ["prospecting"],
    useCaseSlugs: ["sales-engagement","prospecting"],
    teamTypeSlugs: ["sales","marketing"],
    businessSizeSlugs: ["micro","small-business","mid-market"],
    competitorSlugs: ["instantly","smartlead","apollo","outreach"],
    alternativeSlugs: ["instantly","smartlead","apollo","hunter"],
    comparableSlugs: ["instantly","smartlead"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-17T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
  soft({
    id: "soft-smartlead",
    slug: "smartlead",
    name: "Smartlead",
    company: "Smartlead",
    website: "https://www.smartlead.ai",
    logo: { src: "/brands/smartlead.png", alt: "Smartlead logo" },
    shortDescription:
      "Cold-email outreach infra — Base from $59/mo ($39/mo yearly headline) with send/verified-email bands; higher tiers scale volume.",
    aliases: ["Smartlead.ai","Smart Lead"],
    primaryCategorySlug: "sales-intelligence",
    subcategorySlugs: ["prospecting"],
    useCaseSlugs: ["sales-engagement","prospecting"],
    teamTypeSlugs: ["sales","marketing"],
    businessSizeSlugs: ["micro","small-business","mid-market"],
    competitorSlugs: ["instantly","lemlist","apollo","outreach"],
    alternativeSlugs: ["instantly","lemlist","apollo","hunter"],
    comparableSlugs: ["instantly","lemlist"],
    metadata: {
      status: "published",
      publishedAt: "2026-08-17T00:00:00.000Z",
      researchStatus: "complete",
    },
  }),
