/**
 * ResourceEcosystemAgent (CLI)
 * Identifies missing/overlapping CRM resources and journey gaps.
 * Does NOT create resources automatically.
 *
 * npm run resources:ecosystem
 *
 * Writes: docs/content-ecosystem/resources/RESOURCE-OPPORTUNITIES.md (refresh stamp + live inventory)
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { getAllResourcesUnfiltered } from "@/data";
import { getResourceHubProfile } from "@/data/resource-hub";

const TARGET_BACKLOG = [
  { stage: "DEFINE", name: "CRM Stakeholder Interview Questions", prefer: "optional" },
  { stage: "DEFINE", name: "CRM Current-State Process Worksheet", prefer: "optional — may fold into Requirements" },
  { stage: "DEFINE", name: "CRM Data & Integration Inventory", prefer: "optional — overlap Data Migration Template" },
  { stage: "SHORTLIST", name: "CRM Shortlisting Checklist", prefer: "skip — CRM Finder tool" },
  { stage: "EVALUATE", name: "CRM Trial Test Script", prefer: "optional — fold into Demo Checklist" },
  { stage: "EVALUATE", name: "CRM Vendor Questions Checklist", prefer: "skip — RFP + Demo cover" },
  { stage: "VALIDATE", name: "CRM Integration Checklist", prefer: "optional" },
  { stage: "VALIDATE", name: "CRM Reference Call Questions", prefer: "optional" },
  { stage: "BUY", name: "CRM TCO Worksheet", prefer: "skip — Cost Calculator tool; Business Case owns narrative" },
  { stage: "BUY", name: "CRM Negotiation Checklist", prefer: "optional later" },
  { stage: "DECIDE", name: "CRM Decision Matrix", prefer: "rename/restructure Comparison Worksheet" },
  { stage: "IMPLEMENT", name: "CRM Adoption Plan", prefer: "optional — Training Plan adjacent" },
  { stage: "OPTIMIZE", name: "CRM Health Check", prefer: "rename Optimization Checklist later" },
  { stage: "OPTIMIZE", name: "CRM Renewal Checklist", prefer: "optional later" },
];

function main() {
  const resources = getAllResourcesUnfiltered();
  const outPath = join(
    process.cwd(),
    "docs/content-ecosystem/resources/RESOURCE-OPPORTUNITIES.md",
  );

  const inventory = resources
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .map((r) => {
      const p = getResourceHubProfile(r.slug);
      return {
        name: r.name,
        slug: r.slug,
        type: r.resourceType ?? r.kind,
        stage: r.buyingStage ?? r.stage,
        jtbd: r.jobToBeDone ?? "",
        useBefore: p?.useBefore ?? [],
        useNext: p?.useNext ?? [],
        journey: p?.journeySlugs ?? [],
      };
    });

  const missingJourney = inventory.filter(
    (r) => r.useBefore.length === 0 && r.useNext.length === 0 && r.journey.length === 0,
  );

  const stamp = [
    "",
    "---",
    "",
    `## Live inventory stamp (${new Date().toISOString().slice(0, 10)})`,
    "",
    "Generated by ResourceEcosystemAgent. Canonical recommendations remain Option A (separate resources). Do not auto-create.",
    "",
    "| Resource | Type | Stage | JTBD | Journey wired? |",
    "| --- | --- | --- | --- | --- |",
    ...inventory.map((r) => {
      const wired =
        r.useBefore.length || r.useNext.length || r.journey.length
          ? "yes"
          : "partial/default";
      return `| ${r.name} | ${r.type} | ${r.stage} | ${r.jtbd || "—"} | ${wired} |`;
    }),
    "",
    "### Journey gaps (no useBefore/useNext/journeySlugs on profile)",
    "",
    ...(missingJourney.length
      ? missingJourney.map((r) => `- ${r.name} (\`${r.slug}\`)`)
      : ["- None — defaults may still apply in hub model."]),
    "",
    "### Backlog (do not auto-create)",
    "",
    ...TARGET_BACKLOG.map(
      (t) => `- **${t.stage}** · ${t.name} — ${t.prefer}`,
    ),
    "",
  ].join("\n");

  if (existsSync(outPath)) {
    const existing = readFileSync(outPath, "utf8");
    const cut = existing.split("\n---\n")[0]?.trimEnd() ?? existing.trimEnd();
    writeFileSync(outPath, `${cut}\n${stamp}`);
  } else {
    writeFileSync(
      outPath,
      `# Resource Opportunities\n\nSee RESOURCE-AUDIT.md for actions.\n${stamp}`,
    );
  }

  console.log(`Updated ${outPath}`);
  console.log(
    `Inventory ${inventory.length}; journey gaps ${missingJourney.length}`,
  );
}

main();
