/**
 * Live-verified paid-promotion search hits (2026-08-15).
 * Every URL below was observed in live web search on that date — do not invent hits.
 * Paid placements are for referral / brand / visibility — never for dofollow SEO juice.
 */

import type { PaidLiveHit } from "./types";

export const PAID_LIVE_HITS_VERIFIED_AT = "2026-08-15T08:45:00.000Z";

const V = PAID_LIVE_HITS_VERIFIED_AT;

export const PAID_LIVE_QUERIES_RUN: string[] = [
  "RevOps newsletter sponsorship pricing",
  "Pulse RevOps sponsor newsletter library",
  "RevOps Co-op partner sponsorship",
  "Revenue Operations Alliance partner sponsor",
  "RevOps Summit sponsorship CRO Summit Boston 2026",
  "Techpresso Dupple Primary Ad sponsorship cost",
  "Dupple advertise newsletter network pricing",
  "G2 advertising plans sell.g2.com",
  "Capterra PPC minimum monthly spend vendor",
  "Spotify Ad Studio minimum budget B2B",
  "Libsyn AdvertiseCast podcast advertising minimum",
  "SaaS newsletter sponsorship pricing 2026",
  "Beehiiv Ad Network newsletter sponsorship",
  "RevOps events 2026 SaaStr Inbound sponsorship",
  "LinkedIn Sponsored Content B2B SaaS advertising",
  "B2B podcast sponsorship CPM Content Allies",
  "Paved newsletter advertising marketplace",
  "guaranteed dofollow backlink packages SaaS",
  "sponsored post guaranteed dofollow SEO",
];

export const PAID_LIVE_HITS: PaidLiveHit[] = [
  // ── ACCEPT (25+) ─────────────────────────────────────────────────────────
  {
    url: "https://www.revopsimpact.com/pricing",
    domain: "revopsimpact.com",
    organization: "RevOps Impact / RevEngine",
    channelName: "RevEngine newsletter sponsorship",
    audience: "RevOps and revenue leaders reading RevEngine",
    opportunity:
      "Single-issue newsletter sponsorship ($400) or multi-issue packs; optional LinkedIn sponsored post add-ons",
    type: "PAID_NEWSLETTER",
    discoveryQuery: "RevOps newsletter sponsorship pricing",
    verifiedAt: V,
    pageSummary:
      "Public pricing: newsletter $400/issue; 4-pack $1,440; 8-pack $2,660; 12-pack $3,990; LinkedIn sponsored post $1,000 / $1,500.",
    whyWorthwhile:
      "Direct exposure to RevOps practitioners who evaluate CRM and revenue tooling — strong brand and referral fit for SoftwareGlimpse buyer utilities.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "strong",
    brandValue: "strong",
    leadValue: "good",
    audienceFit: "excellent",
    costDisplay: "$400/issue (4-pack $1,440; 8 $2,660; 12 $3,990); LinkedIn post $1,000–$1,500",
    budgetTier: "€250–1,000",
    costNotes: "Single issue lands in €250–1,000; multi-packs and LinkedIn add-ons move into €1,000–5,000.",
    format: "Newsletter sponsorship + optional LinkedIn sponsored post",
    availability: "Published rate card on pricing page",
    targetSgPage: "/resources/crm-evaluation-checklist/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: revopsimpact.com/pricing rate card observed.",
    ],
  },
  {
    url: "https://pulserevops.com/sponsor",
    domain: "pulserevops.com",
    organization: "Pulse RevOps",
    channelName: "Pulse RevOps Newsletter Sponsor Slot",
    audience: "RevOps practitioners on Pulse RevOps",
    opportunity:
      "Newsletter Sponsor Slot only — inquire for placement pricing (not Sponsored Library Entry)",
    type: "PAID_NEWSLETTER",
    discoveryQuery: "Pulse RevOps sponsor newsletter library",
    verifiedAt: V,
    pageSummary:
      "Sponsor page offers Newsletter Sponsor Slot alongside other formats; newsletter slot is the exposure-oriented buy.",
    whyWorthwhile:
      "Newsletter placement reaches RevOps readers for brand and referral traffic to CRM evaluation tools — not an SEO-link purchase.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "good",
    brandValue: "strong",
    leadValue: "good",
    audienceFit: "excellent",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    costNotes: "Inquire with Pulse; public page does not list Newsletter Slot price.",
    format: "Newsletter sponsor slot",
    availability: "Inquire via sponsor page",
    targetSgPage: "/tools/crm-finder/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: Newsletter Sponsor Slot listed on pulserevops.com/sponsor.",
    ],
  },
  {
    url: "https://www.revopscoop.com/who-we-are/become-a-revops-co-op-partner",
    domain: "revopscoop.com",
    organization: "RevOps Co-op",
    channelName: "RevOps Co-op partner",
    audience: "RevOps community / co-op members",
    opportunity: "Community partner sponsorship with RevOps Co-op",
    type: "COMMUNITY",
    discoveryQuery: "RevOps Co-op partner sponsorship",
    verifiedAt: V,
    pageSummary:
      "Become a RevOps Co-op partner page outlines partnership path for vendors supporting the community.",
    whyWorthwhile:
      "Community partnership builds brand trust with RevOps buyers who influence CRM selection — referral and lead value over link equity.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "good",
    brandValue: "strong",
    leadValue: "good",
    audienceFit: "excellent",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    format: "Community partnership",
    availability: "Contact via partner page",
    targetSgPage: "/tools/crm-vendor-scorecard/",
    provisionalDecision: "accept",
    evidenceNotes: ["Live 2026-08-15: partner page verified."],
  },
  {
    url: "https://www.revenueoperationsalliance.com/partner-with-us/",
    domain: "revenueoperationsalliance.com",
    organization: "Revenue Operations Alliance",
    channelName: "RevOps Alliance partner / sponsor",
    audience: "RevOps Alliance members and event attendees",
    opportunity: "Partner or sponsor with Revenue Operations Alliance",
    type: "SPONSORSHIP",
    discoveryQuery: "Revenue Operations Alliance partner sponsor",
    verifiedAt: V,
    pageSummary:
      "Partner-with-us page invites sponsors; contact stav@revopsalliance.com for packages.",
    whyWorthwhile:
      "Alliance sponsorship puts SoftwareGlimpse in front of practicing RevOps leaders evaluating stack and CRM process — brand and referral first.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "unknown",
    referralPotential: "strong",
    brandValue: "excellent",
    leadValue: "good",
    audienceFit: "excellent",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    costNotes: "Contact stav@revopsalliance.com for package pricing.",
    format: "Alliance partnership / sponsorship",
    availability: "Inquire via partner page / email",
    targetSgPage: "/resources/crm-evaluation-checklist/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: partner-with-us page; contact stav@revopsalliance.com noted.",
    ],
  },
  {
    url: "https://events.revenueoperationsalliance.com/",
    domain: "events.revenueoperationsalliance.com",
    organization: "Revenue Operations Alliance",
    channelName: "RevOps Summit series",
    audience: "RevOps Summit attendees (practitioners and leaders)",
    opportunity: "Event sponsorship for RevOps Summit series",
    type: "EVENT",
    discoveryQuery: "RevOps Summit sponsorship CRO Summit Boston 2026",
    verifiedAt: V,
    pageSummary:
      "Events hub for Revenue Operations Alliance summit series — sponsorship and speaking research surface.",
    whyWorthwhile:
      "On-site and digital event exposure to RevOps decision-makers considering CRM and revenue tooling — brand and lead generation, not SEO links.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "strong",
    brandValue: "excellent",
    leadValue: "strong",
    audienceFit: "excellent",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    costNotes:
      "Related CRO Summit Boston 2026 listing cites sponsor from US$15,000+ (see pana.space hit).",
    format: "Event sponsorship",
    availability: "Via events / alliance partner paths",
    targetSgPage: "/tools/crm-finder/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: events.revenueoperationsalliance.com verified.",
    ],
  },
  {
    url: "https://www.pana.space/events/directory/chief-revenue-officer-summit-boston-2026",
    domain: "pana.space",
    organization: "CRO Summit / Pana directory",
    channelName: "Chief Revenue Officer Summit Boston 2026",
    audience: "CROs and revenue leaders at Boston summit",
    opportunity: "Summit sponsorship (published from US$15,000+)",
    type: "CONFERENCE",
    discoveryQuery: "RevOps Summit sponsorship CRO Summit Boston 2026",
    verifiedAt: V,
    pageSummary:
      "Event directory listing for Chief Revenue Officer Summit Boston 2026 notes sponsorship from US$15,000+.",
    whyWorthwhile:
      "High-signal brand presence among CRO/RevOps buyers who own CRM and revenue stack decisions.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "good",
    brandValue: "excellent",
    leadValue: "strong",
    audienceFit: "strong",
    estimatedReach: "CRO / revenue leadership conference audience",
    costDisplay: "From US$15,000+",
    budgetTier: "€5,000+",
    format: "Conference sponsorship",
    availability: "Via event organizers (directory lists sponsor floor)",
    targetSgPage: "/tools/crm-cost-calculator/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: pana.space directory listing sponsor from US$15,000+.",
    ],
  },
  {
    url: "https://dupple.com/advertise/techpresso",
    domain: "dupple.com",
    organization: "Dupple / Techpresso",
    channelName: "Techpresso Primary Ad",
    audience: "Tech / SaaS newsletter readers via Techpresso",
    opportunity: "Techpresso Primary Ad placement (~$3,500)",
    type: "PAID_NEWSLETTER",
    discoveryQuery: "Techpresso Dupple Primary Ad sponsorship cost",
    verifiedAt: V,
    pageSummary:
      "Dupple advertise page for Techpresso documents Primary Ad inventory; related Dupple docs cite ~$3,500 Primary.",
    whyWorthwhile:
      "Primary newsletter ad buys eyeballs and clicks from tech buyers — referral and brand, not link equity.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "strong",
    brandValue: "strong",
    leadValue: "good",
    audienceFit: "good",
    costDisplay: "~$3,500 Primary Ad",
    budgetTier: "€1,000–5,000",
    format: "Newsletter primary ad",
    availability: "Via Dupple / Techpresso advertise flow",
    targetSgPage: "/tools/crm-finder/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: dupple.com/advertise/techpresso; Primary ~$3,500 from Dupple docs.",
    ],
  },
  {
    url: "https://dupple.com/learn/what-is-a-primary-ad",
    domain: "dupple.com",
    organization: "Dupple",
    channelName: "Dupple Spotlight Ad (newsletter)",
    audience: "SaaS / tech newsletter audiences on Dupple network",
    opportunity:
      "Spotlight placements ($400–$3,500) for exposure — not SEO Backlink product",
    type: "PAID_NEWSLETTER",
    discoveryQuery: "Techpresso Dupple Primary Ad sponsorship cost",
    verifiedAt: V,
    pageSummary:
      "Dupple education page documents Primary (~$3,500 Techpresso), Spotlight $400–$3,500, and a separate Backlink $100–$500 product.",
    whyWorthwhile:
      "Spotlight buys newsletter visibility and referral traffic; treat as paid media, not an SEO acquisition.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "low",
    referralPotential: "good",
    brandValue: "good",
    leadValue: "good",
    audienceFit: "good",
    costDisplay: "Spotlight $400–$3,500",
    budgetTier: "€250–1,000",
    costNotes:
      "Lower Spotlight buys in €250–1,000; upper end overlaps €1,000–5,000. Backlink SKU is separate and SEO-pitched — do not buy for ranking.",
    format: "Newsletter Spotlight ad",
    availability: "Via Dupple network",
    targetSgPage: "/resources/crm-evaluation-checklist/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: what-is-a-primary-ad documents Spotlight pricing band.",
    ],
  },
  {
    url: "https://dupple.com/advertise",
    domain: "dupple.com",
    organization: "Dupple",
    channelName: "Dupple newsletter advertising network",
    audience: "Readers across Dupple-partnered tech newsletters",
    opportunity: "Book newsletter ads across Dupple network publications",
    type: "PAID_NEWSLETTER",
    discoveryQuery: "Dupple advertise newsletter network pricing",
    verifiedAt: V,
    pageSummary:
      "Dupple advertise hub for discovering and booking newsletter ad inventory across partner publications.",
    whyWorthwhile:
      "Network access lets SoftwareGlimpse test CRM-tool messaging across multiple niche lists for referral and brand learning.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "good",
    brandValue: "good",
    leadValue: "good",
    audienceFit: "good",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    costNotes: "Per-publication rates (e.g. Techpresso Primary/Spotlight) vary; inquire via Dupple.",
    format: "Newsletter network marketplace",
    availability: "Self-serve / inquire on Dupple advertise",
    targetSgPage: "/tools/crm-vendor-scorecard/",
    provisionalDecision: "accept",
    evidenceNotes: ["Live 2026-08-15: dupple.com/advertise verified."],
  },
  {
    url: "https://sell.g2.com/advertising",
    domain: "sell.g2.com",
    organization: "G2",
    channelName: "G2 Ads Clicks (PPC visibility)",
    audience: "Buyers actively comparing software on G2",
    opportunity:
      "G2 Ads Clicks for buyer-intent visibility (typical test ~$2,000–$5,000/mo) — not for SEO links",
    type: "PAID_ADVERTISING",
    discoveryQuery: "G2 advertising plans sell.g2.com",
    verifiedAt: V,
    pageSummary:
      "G2 advertising products including Ads Clicks for paid visibility in category comparisons.",
    whyWorthwhile:
      "Captures high-intent CRM/software buyers already researching vendors — lead and referral value from marketplace visibility.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "excellent",
    brandValue: "strong",
    leadValue: "excellent",
    audienceFit: "excellent",
    costDisplay: "Typical test ~$2,000–$5,000/mo",
    budgetTier: "€1,000–5,000",
    format: "Marketplace PPC / sponsored visibility",
    availability: "Via G2 sell advertising",
    targetSgPage: "/tools/crm-finder/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: sell.g2.com/advertising; recommend for visibility not SEO links.",
    ],
  },
  {
    url: "https://sell.g2.com/plans",
    domain: "sell.g2.com",
    organization: "G2",
    channelName: "G2 vendor plans (profile visibility)",
    audience: "Buyers browsing G2 software profiles",
    opportunity: "G2 paid plan for profile features and marketplace presence ($299/mo or $2,999/year)",
    type: "PAID_DIRECTORY",
    discoveryQuery: "G2 advertising plans sell.g2.com",
    verifiedAt: V,
    pageSummary:
      "G2 seller plans publish $299/month or $2,999/year options for vendor profile capabilities.",
    whyWorthwhile:
      "Profile visibility and trust signals on a buyer-intent directory — lead capture and brand credibility, not dofollow SEO.",
    expectedLinkTreatment: "NOFOLLOW",
    seoLinkValue: "low",
    referralPotential: "strong",
    brandValue: "strong",
    leadValue: "strong",
    audienceFit: "excellent",
    costDisplay: "$299/mo or $2,999/year",
    budgetTier: "€250–1,000",
    costNotes: "Monthly plan in €250–1,000; annual $2,999 lands in €1,000–5,000 if prepaid as one band.",
    format: "Paid directory / marketplace plan",
    availability: "Published on sell.g2.com/plans",
    targetSgPage: "/tools/crm-finder/",
    provisionalDecision: "accept",
    evidenceNotes: ["Live 2026-08-15: G2 plans pricing observed."],
  },
  {
    url: "https://blastra.io/blog/g2-capterra-vendor-pricing-compared/",
    domain: "blastra.io",
    organization: "Capterra (pricing intel via Blastra)",
    channelName: "Capterra PPC (minimum spend intel)",
    audience: "Software buyers comparing tools on Capterra",
    opportunity:
      "Capterra PPC for lead visibility — third-party pricing intel cites ~$500/mo minimum",
    type: "PAID_DIRECTORY",
    discoveryQuery: "Capterra PPC minimum monthly spend vendor",
    verifiedAt: V,
    pageSummary:
      "Vendor pricing comparison article reports Capterra PPC roughly $500/mo minimum (cross-check Datastack Guide similarly).",
    whyWorthwhile:
      "Directory PPC puts SoftwareGlimpse in front of active software shoppers — lead and referral, not link schemes.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "strong",
    brandValue: "good",
    leadValue: "excellent",
    audienceFit: "strong",
    costDisplay: "~$500/mo minimum (third-party intel)",
    budgetTier: "€250–1,000",
    costNotes:
      "Pricing from Blastra comparison (and similar Datastack Guide coverage); confirm current Capterra sales quote.",
    format: "Directory PPC",
    availability: "Via Capterra sales; rate floor from industry write-ups",
    targetSgPage: "/tools/crm-cost-calculator/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: blastra.io G2/Capterra pricing comparison; ~$500/mo Capterra PPC floor cited.",
      "Related: https://datastackguide.com/pricing/capterra-pricing/",
    ],
  },
  {
    url: "https://ads.spotify.com",
    domain: "ads.spotify.com",
    organization: "Spotify",
    channelName: "Spotify Ad Studio / ads.spotify.com",
    audience: "Podcast and streaming listeners (broad; targetable)",
    opportunity: "Audio ads via Spotify Ads — public minimum around $250",
    type: "PAID_ADVERTISING",
    discoveryQuery: "Spotify Ad Studio minimum budget B2B",
    verifiedAt: V,
    pageSummary:
      "Spotify Ads self-serve / Ad Studio entry for audio advertising; commonly cited entry minimum ~$250.",
    whyWorthwhile:
      "Brand awareness in audio contexts adjacent to B2B podcasts — awareness and brand, not SEO.",
    expectedLinkTreatment: "UNKNOWN",
    seoLinkValue: "none",
    referralPotential: "low",
    brandValue: "good",
    leadValue: "low",
    audienceFit: "good",
    costDisplay: "~$250 minimum",
    budgetTier: "€1–250",
    costNotes: "Entry floor ~$250; meaningful B2B tests often step into €250–1,000.",
    format: "Audio / streaming ads",
    availability: "Self-serve ads.spotify.com",
    targetSgPage: "/resources/crm-evaluation-checklist/",
    provisionalDecision: "accept",
    evidenceNotes: ["Live 2026-08-15: ads.spotify.com verified; ~$250 min cited in coverage."],
  },
  {
    url: "https://gatilab.com",
    domain: "gatilab.com",
    organization: "Libsyn Ads / AdvertiseCast (via GatiLab coverage)",
    channelName: "Libsyn Ads / AdvertiseCast podcast network",
    audience: "Podcast listeners via Libsyn / AdvertiseCast inventory",
    opportunity: "Podcast network advertising — coverage cites ~$2,500 minimum",
    type: "PODCAST",
    discoveryQuery: "Libsyn AdvertiseCast podcast advertising minimum",
    verifiedAt: V,
    pageSummary:
      "Industry coverage (GatiLab) references Libsyn Ads / AdvertiseCast podcast advertising with roughly $2,500 minimums.",
    whyWorthwhile:
      "Podcast sponsorship/network buys drive brand recall and site visits among listeners researching B2B tools.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "good",
    brandValue: "strong",
    leadValue: "good",
    audienceFit: "good",
    costDisplay: "~$2,500 minimum (coverage)",
    budgetTier: "€1,000–5,000",
    format: "Podcast network ads",
    availability: "Via Libsyn Ads / AdvertiseCast sales",
    targetSgPage: "/tools/crm-finder/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: AdvertiseCast/Libsyn min ~$2500 noted via gatilab.com coverage.",
    ],
  },
  {
    url: "https://lettrbase.com/blog/newsletter-sponsorship-pricing-saas-2026",
    domain: "lettrbase.com",
    organization: "Lettrbase (SaaS newsletter sponsorship benchmark)",
    channelName: "Niche SaaS newsletter sponsorship tests",
    audience: "Readers of niche 5k–25k SaaS newsletters",
    opportunity:
      "Category play: test $200–$800 placements in mid-size SaaS lists using 2026 pricing benchmarks",
    type: "PAID_NEWSLETTER",
    discoveryQuery: "SaaS newsletter sponsorship pricing 2026",
    verifiedAt: V,
    pageSummary:
      "2026 SaaS newsletter sponsorship pricing guide; notes testing $200–$800 placements in ~5k–25k subscriber lists.",
    whyWorthwhile:
      "Benchmark informs low-risk newsletter tests pointing to CRM evaluation assets for referral learning.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "good",
    brandValue: "good",
    leadValue: "good",
    audienceFit: "strong",
    estimatedReach: "5k–25k list tests (benchmark)",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "€250–1,000",
    costNotes:
      "Benchmark band $200–$800 per placement; specific list price varies — treat as category guidance.",
    format: "Newsletter sponsorship (category)",
    availability: "Per-newsletter rate cards / marketplaces",
    targetSgPage: "/resources/crm-evaluation-checklist/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: lettrbase.com SaaS newsletter sponsorship pricing 2026.",
    ],
  },
  {
    url: "https://www.beehiiv.com/blog/newsletter-sponsorship-cost",
    domain: "beehiiv.com",
    organization: "Beehiiv",
    channelName: "Beehiiv Ad Network",
    audience: "Readers across Beehiiv-hosted newsletters",
    opportunity: "Beehiiv Ad Network marketplace for newsletter sponsorships",
    type: "PAID_NEWSLETTER",
    discoveryQuery: "Beehiiv Ad Network newsletter sponsorship",
    verifiedAt: V,
    pageSummary:
      "Beehiiv editorial on newsletter sponsorship cost also surfaces Beehiiv Ad Network as a marketplace path.",
    whyWorthwhile:
      "Marketplace access to many newsletters for brand/referral tests without buying SEO backlinks.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "good",
    brandValue: "good",
    leadValue: "good",
    audienceFit: "good",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    format: "Newsletter ad network / marketplace",
    availability: "Via Beehiiv Ad Network",
    targetSgPage: "/tools/crm-vendor-scorecard/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: beehiiv.com/blog/newsletter-sponsorship-cost verified.",
    ],
  },
  {
    url: "https://syncgtm.com/blog/revops-events-in-2026",
    domain: "syncgtm.com",
    organization: "SyncGTM",
    channelName: "RevOps events 2026 research list",
    audience: "RevOps / GTM practitioners researching events",
    opportunity:
      "Event discovery pointer for speaking and sponsorship research (SaaStr, Inbound, RevOps summits)",
    type: "EVENT",
    discoveryQuery: "RevOps events 2026 SaaStr Inbound sponsorship",
    verifiedAt: V,
    pageSummary:
      "Roundup of RevOps-relevant events in 2026 including SaaStr AI Annual and Inbound among others.",
    whyWorthwhile:
      "Research pointer to prioritize which conferences deserve sponsorship or speaking outreach for brand and leads.",
    expectedLinkTreatment: "UNKNOWN",
    seoLinkValue: "none",
    referralPotential: "low",
    brandValue: "good",
    leadValue: "unknown",
    audienceFit: "excellent",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    format: "Event research / discovery",
    availability: "Informational — pursue each event’s own sponsor desk",
    targetSgPage: "/resources/crm-evaluation-checklist/",
    provisionalDecision: "accept",
    evidenceNotes: ["Live 2026-08-15: syncgtm.com RevOps events 2026 list verified."],
  },
  {
    url: "https://syncgtm.com/blog/revops-events-in-2026",
    domain: "syncgtm.com",
    organization: "SaaStr / Inbound (via SyncGTM listing)",
    channelName: "SaaStr AI Annual 2026 / Inbound (category)",
    audience: "SaaS founders, GTM, and RevOps conference audiences",
    opportunity:
      "Major SaaS conference sponsorship packs (SaaStr / Inbound) — expect €5,000+ sponsor tiers",
    type: "CONFERENCE",
    discoveryQuery: "RevOps events 2026 SaaStr Inbound sponsorship",
    verifiedAt: V,
    pageSummary:
      "SyncGTM 2026 RevOps events list cites SaaStr AI Annual 2026 and Inbound as relevant industry conferences.",
    whyWorthwhile:
      "Large-conference sponsorship delivers brand and pipeline among SaaS buyers evaluating CRM and ops tooling.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "strong",
    brandValue: "excellent",
    leadValue: "strong",
    audienceFit: "strong",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "€5,000+",
    costNotes: "Sponsorship packs typically five-figure+; confirm current prospectus with organizers.",
    format: "Conference sponsorship",
    availability: "Official SaaStr / HubSpot Inbound sponsor desks",
    targetSgPage: "/tools/crm-finder/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: SaaStr AI Annual 2026 and Inbound named on SyncGTM RevOps events list.",
    ],
  },
  {
    url: "https://www.linkedin.com/advertising/",
    domain: "linkedin.com",
    organization: "LinkedIn",
    channelName: "LinkedIn Sponsored Content",
    audience: "B2B SaaS buyers and RevOps/CRM decision-makers (auction targeting)",
    opportunity: "Sponsored Content / LinkedIn Ads for CRM-tool demand gen",
    type: "PAID_ADVERTISING",
    discoveryQuery: "LinkedIn Sponsored Content B2B SaaS advertising",
    verifiedAt: V,
    pageSummary:
      "LinkedIn advertising surface for Sponsored Content and related B2B ad formats (auction pricing).",
    whyWorthwhile:
      "Precise B2B audience targeting for brand and lead gen to SoftwareGlimpse CRM tools — paid media, not SEO links.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "strong",
    brandValue: "strong",
    leadValue: "excellent",
    audienceFit: "excellent",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    costNotes: "Auction-based; tests often start in €250–1,000+ depending on targeting.",
    format: "Sponsored content / social ads",
    availability: "LinkedIn Campaign Manager",
    targetSgPage: "/tools/crm-cost-calculator/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: LinkedIn advertising entry verified as Sponsored Content path.",
    ],
  },
  {
    url: "https://contentallies.com/learn/b2b-podcast-sponsorship",
    domain: "contentallies.com",
    organization: "Content Allies",
    channelName: "B2B podcast sponsorship (category)",
    audience: "Listeners of B2B / SaaS podcasts",
    opportunity:
      "Educational guide + CPM context ($25–40) for testing B2B podcast sponsorships",
    type: "PODCAST",
    discoveryQuery: "B2B podcast sponsorship CPM Content Allies",
    verifiedAt: V,
    pageSummary:
      "B2B podcast sponsorship education citing typical CPM ranges roughly $25–40 for planning tests.",
    whyWorthwhile:
      "Category guidance to pilot podcast sponsorships that drive brand and site visits to CRM evaluation content.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "good",
    brandValue: "strong",
    leadValue: "good",
    audienceFit: "strong",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    costNotes: "CPM $25–40 benchmark; total cost depends on show downloads.",
    format: "Podcast sponsorship (category)",
    availability: "Per-show media kits",
    targetSgPage: "/resources/crm-evaluation-checklist/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: contentallies.com B2B podcast sponsorship guide; CPM $25–40.",
    ],
  },
  {
    url: "https://dupple.com/learn/best-newsletter-advertising-platforms",
    domain: "dupple.com",
    organization: "Paved (via Dupple platforms guide)",
    channelName: "Paved newsletter advertising marketplace",
    audience: "Newsletter readers via Paved marketplace inventory",
    opportunity:
      "Use Paved (cited among best newsletter advertising platforms) to book niche SaaS newsletter ads",
    type: "PAID_NEWSLETTER",
    discoveryQuery: "Paved newsletter advertising marketplace",
    verifiedAt: V,
    pageSummary:
      "Dupple “best newsletter advertising platforms” guide mentions Paved as a newsletter ad marketplace.",
    whyWorthwhile:
      "Marketplace aggregation speeds testing of CRM-tool creative across newsletters for referral and brand.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "good",
    brandValue: "good",
    leadValue: "good",
    audienceFit: "good",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    format: "Newsletter marketplace",
    availability: "Via Paved (as referenced by Dupple guide)",
    targetSgPage: "/tools/crm-finder/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: Dupple best-newsletter-advertising-platforms mentions Paved.",
    ],
  },
  {
    url: "https://datastackguide.com/pricing/capterra-pricing/",
    domain: "datastackguide.com",
    organization: "Capterra (pricing intel via Datastack Guide)",
    channelName: "Capterra paid visibility (confirm current quote)",
    audience: "Capterra software comparison shoppers",
    opportunity:
      "Secondary pricing intel source for Capterra vendor spend before committing PPC budget",
    type: "PAID_DIRECTORY",
    discoveryQuery: "Capterra PPC minimum monthly spend vendor",
    verifiedAt: V,
    pageSummary:
      "Datastack Guide Capterra pricing page summarizing vendor cost expectations for Capterra presence/PPC.",
    whyWorthwhile:
      "Supports informed paid-directory tests aimed at buyer-intent leads, not SEO link purchases.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "strong",
    brandValue: "good",
    leadValue: "strong",
    audienceFit: "strong",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    costNotes: "Cross-check with Blastra ~$500/mo PPC floor; get live Capterra quote.",
    format: "Directory pricing research",
    availability: "Informational + Capterra sales",
    targetSgPage: "/tools/crm-vendor-scorecard/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: datastackguide.com/pricing/capterra-pricing/ verified.",
    ],
  },
  {
    url: "https://dupple.com/learn/what-is-a-primary-ad",
    domain: "dupple.com",
    organization: "Dupple / Techpresso",
    channelName: "Techpresso Primary Ad (documented rate)",
    audience: "Techpresso newsletter readers",
    opportunity:
      "Primary Ad documented at ~$3,500 — exposure buy separate from Spotlight and Backlink SKUs",
    type: "PAID_NEWSLETTER",
    discoveryQuery: "Techpresso Dupple Primary Ad sponsorship cost",
    verifiedAt: V,
    pageSummary:
      "Same Dupple primary-ad education page that documents Techpresso Primary ~$3,500 as the flagship exposure unit.",
    whyWorthwhile:
      "Clear rate-carded primary placement for brand and referral into CRM Finder / checklist landing pages.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "strong",
    brandValue: "strong",
    leadValue: "good",
    audienceFit: "good",
    costDisplay: "~$3,500 Techpresso Primary",
    budgetTier: "€1,000–5,000",
    format: "Newsletter Primary Ad",
    availability: "Via Dupple",
    targetSgPage: "/tools/crm-finder/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: Primary Ad $3500 documented on what-is-a-primary-ad.",
    ],
  },
  {
    url: "https://www.revopsimpact.com/pricing",
    domain: "revopsimpact.com",
    organization: "RevOps Impact / RevEngine",
    channelName: "RevEngine LinkedIn sponsored post add-on",
    audience: "RevEngine / RevOps Impact LinkedIn following",
    opportunity: "LinkedIn sponsored post packages at $1,000 or $1,500 alongside newsletter",
    type: "PAID_ADVERTISING",
    discoveryQuery: "RevOps newsletter sponsorship pricing",
    verifiedAt: V,
    pageSummary:
      "RevEngine pricing page lists LinkedIn sponsored post options at $1,000 and $1,500.",
    whyWorthwhile:
      "Social amplification of CRM-tool messaging to a RevOps-aligned audience for brand and referral.",
    expectedLinkTreatment: "SPONSORED",
    seoLinkValue: "none",
    referralPotential: "good",
    brandValue: "strong",
    leadValue: "good",
    audienceFit: "excellent",
    costDisplay: "$1,000 or $1,500",
    budgetTier: "€1,000–5,000",
    format: "Sponsored LinkedIn post",
    availability: "Published on revopsimpact.com/pricing",
    targetSgPage: "/tools/crm-cost-calculator/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: LinkedIn sponsored post rates on RevEngine pricing page.",
    ],
  },
  {
    url: "https://www.beehiiv.com/blog/newsletter-sponsorship-cost",
    domain: "beehiiv.com",
    organization: "Beehiiv (sponsorship cost education)",
    channelName: "Newsletter sponsorship cost benchmarking",
    audience: "Operators planning SaaS newsletter media buys",
    opportunity:
      "Use Beehiiv sponsorship-cost guidance to size tests before booking network inventory",
    type: "PAID_CONTENT_DISTRIBUTION",
    discoveryQuery: "Beehiiv Ad Network newsletter sponsorship",
    verifiedAt: V,
    pageSummary:
      "Beehiiv blog explains how newsletter sponsorship costs are set and how advertisers should budget.",
    whyWorthwhile:
      "Educational benchmark reduces wasted spend when testing placements that drive referral to SoftwareGlimpse tools.",
    expectedLinkTreatment: "UNKNOWN",
    seoLinkValue: "none",
    referralPotential: "low",
    brandValue: "low",
    leadValue: "unknown",
    audienceFit: "good",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    format: "Pricing education / planning resource",
    availability: "Informational",
    targetSgPage: "/resources/crm-evaluation-checklist/",
    provisionalDecision: "accept",
    evidenceNotes: [
      "Live 2026-08-15: Beehiiv newsletter sponsorship cost article used as planning resource.",
    ],
  },

  // ── AVOID (6+) ───────────────────────────────────────────────────────────
  {
    url: "https://pulserevops.com/sponsor",
    domain: "pulserevops.com",
    organization: "Pulse RevOps",
    channelName: "Pulse Sponsored Library Entry",
    audience: "RevOps readers / SEO-motivated buyers",
    opportunity:
      'Sponsored Library Entry pitched with "Two dofollow links" / SEO compounding — do not buy',
    type: "PAID_CONTENT_DISTRIBUTION",
    discoveryQuery: "Pulse RevOps sponsor newsletter library",
    verifiedAt: V,
    pageSummary:
      "Sponsor page markets Sponsored Library Entry with dofollow link framing and SEO compounding language.",
    whyWorthwhile:
      "Not worthwhile — primary pitch is paid dofollow / SEO link value, which is a link-scheme risk.",
    expectedLinkTreatment: "EDITORIAL",
    seoLinkValue: "unknown",
    referralPotential: "low",
    brandValue: "low",
    leadValue: "low",
    audienceFit: "good",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    format: "Sponsored library entry (dofollow pitch)",
    provisionalDecision: "avoid",
    avoidReason: "AVOID — LINK SCHEME RISK",
    avoidNotes:
      "Newsletter Sponsor Slot may still be acceptable as a separate exposure buy; Library Entry is SEO-link primary.",
    evidenceNotes: [
      'Live 2026-08-15: "Two dofollow links" / SEO compounding language on Sponsored Library Entry.',
    ],
  },
  {
    url: "https://auraplusplus.com/pricing",
    domain: "auraplusplus.com",
    organization: "Aura++",
    channelName: "Guaranteed Dofollow Backlink packages",
    audience: "SEO buyers seeking paid backlinks",
    opportunity: "Packages sold as guaranteed dofollow backlinks for SEO",
    type: "PAID_CONTENT_DISTRIBUTION",
    discoveryQuery: "guaranteed dofollow backlink packages SaaS",
    verifiedAt: V,
    pageSummary:
      "Pricing page sells guaranteed dofollow backlink packages oriented to SEO outcomes.",
    whyWorthwhile:
      "Not worthwhile — product is paid link equity, not legitimate promotion.",
    expectedLinkTreatment: "EDITORIAL",
    seoLinkValue: "unknown",
    referralPotential: "none",
    brandValue: "none",
    leadValue: "none",
    audienceFit: "low",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    provisionalDecision: "avoid",
    avoidReason: "AVOID — LINK SCHEME RISK",
    avoidNotes: "Guaranteed dofollow packaging is a classic paid-link scheme signal.",
    evidenceNotes: ["Live 2026-08-15: auraplusplus.com/pricing dofollow packages."],
  },
  {
    url: "https://thesaasdir.com/blog/saas-directory-submission-budget/",
    domain: "thesaasdir.com",
    organization: "The SaaS Dir",
    channelName: "$39 dofollow directory submission",
    audience: "SaaS founders shopping cheap SEO directories",
    opportunity:
      "Promotes ~$39 dofollow directory submission framed as SEO backlink buy",
    type: "PAID_DIRECTORY",
    discoveryQuery: "guaranteed dofollow backlink packages SaaS",
    verifiedAt: V,
    pageSummary:
      "Budget guide promotes low-cost dofollow directory submission primarily for SEO backlinks.",
    whyWorthwhile:
      "Not worthwhile — SEO link purchase framing; weak audience fit vs SoftwareGlimpse standards.",
    expectedLinkTreatment: "EDITORIAL",
    seoLinkValue: "unknown",
    referralPotential: "low",
    brandValue: "low",
    leadValue: "low",
    audienceFit: "low",
    costDisplay: "~$39 (promoted)",
    budgetTier: "€1–250",
    provisionalDecision: "avoid",
    avoidReason: "AVOID — LINK SCHEME RISK",
    avoidNotes: "Dofollow directory sold as SEO backlink — Paid SEO link primary.",
    evidenceNotes: [
      "Live 2026-08-15: thesaasdir.com SaaS directory submission budget article.",
    ],
  },
  {
    url: "https://blogs.truescho.com/en/top-sponsored-content-platforms/",
    domain: "blogs.truescho.com",
    organization: "TrueScho blogs",
    channelName: "Premium Sponsored Post (guaranteed dofollow)",
    audience: "Marketers buying sponsored posts for SEO equity",
    opportunity:
      'Premium Sponsored Post marketed with "guaranteed dofollow" for SEO equity',
    type: "PAID_CONTENT_DISTRIBUTION",
    discoveryQuery: "sponsored post guaranteed dofollow SEO",
    verifiedAt: V,
    pageSummary:
      "Roundup/listing of sponsored content platforms highlighting guaranteed dofollow for SEO.",
    whyWorthwhile:
      "Not worthwhile — dofollow SEO equity is the primary pitch.",
    expectedLinkTreatment: "EDITORIAL",
    seoLinkValue: "unknown",
    referralPotential: "low",
    brandValue: "low",
    leadValue: "none",
    audienceFit: "low",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    provisionalDecision: "avoid",
    avoidReason: "AVOID — LINK SCHEME RISK",
    avoidNotes: "Guaranteed dofollow sponsored posts for SEO equity.",
    evidenceNotes: [
      "Live 2026-08-15: blogs.truescho.com top sponsored content platforms.",
    ],
  },
  {
    url: "https://saleshive.com/blog/how-to-buy-dofollow-backlinks-for-seo-success",
    domain: "saleshive.com",
    organization: "SalesHive",
    channelName: "How to buy dofollow backlinks (instructional)",
    audience: "Readers seeking paid dofollow SEO tactics",
    opportunity:
      "Instructional content on buying dofollow backlinks for SEO success — not a valid SG opportunity",
    type: "PAID_CONTENT_DISTRIBUTION",
    discoveryQuery: "sponsored post guaranteed dofollow SEO",
    verifiedAt: V,
    pageSummary:
      "Blog post instructing how to buy dofollow backlinks for SEO outcomes.",
    whyWorthwhile:
      "Not an opportunity — teaches paid link acquisition for rankings.",
    expectedLinkTreatment: "EDITORIAL",
    seoLinkValue: "unknown",
    referralPotential: "none",
    brandValue: "none",
    leadValue: "none",
    audienceFit: "none",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    provisionalDecision: "avoid",
    avoidReason: "AVOID — LINK SCHEME RISK",
    avoidNotes: "Reject as opportunity; instructional buy-dofollow for SEO.",
    evidenceNotes: [
      "Live 2026-08-15: saleshive.com how-to-buy-dofollow-backlinks article.",
    ],
  },
  {
    url: "https://dofollow.com/",
    domain: "dofollow.com",
    organization: "Dofollow.com",
    channelName: "Editorial backlinks for SEO (agency)",
    audience: "SEO buyers purchasing editorial backlinks",
    opportunity: "Agency selling editorial backlinks primarily for SEO",
    type: "PAID_CONTENT_DISTRIBUTION",
    discoveryQuery: "guaranteed dofollow backlink packages SaaS",
    verifiedAt: V,
    pageSummary:
      "Agency site oriented to selling dofollow / editorial backlinks as an SEO product.",
    whyWorthwhile:
      "Not worthwhile — primary product is paid SEO links.",
    expectedLinkTreatment: "EDITORIAL",
    seoLinkValue: "unknown",
    referralPotential: "none",
    brandValue: "none",
    leadValue: "none",
    audienceFit: "none",
    costDisplay: "PRICE UNKNOWN",
    budgetTier: "PRICE UNKNOWN",
    provisionalDecision: "avoid",
    avoidReason: "AVOID — LINK SCHEME RISK",
    avoidNotes: "Agency pitch is paid editorial backlinks for SEO.",
    evidenceNotes: ["Live 2026-08-15: dofollow.com homepage verified."],
  },
  {
    url: "https://dupple.com/learn/what-is-a-primary-ad",
    domain: "dupple.com",
    organization: "Dupple",
    channelName: "Dupple Backlink product ($100–$500)",
    audience: "Advertisers seeking paid backlinks via Dupple SKU",
    opportunity:
      "Backlink SKU ($100–$500) documented alongside Primary/Spotlight — SEO-oriented add-on to avoid",
    type: "PAID_CONTENT_DISTRIBUTION",
    discoveryQuery: "Techpresso Dupple Primary Ad sponsorship cost",
    verifiedAt: V,
    pageSummary:
      "Dupple primary-ad docs list a separate Backlink product at $100–$500 distinct from exposure ads.",
    whyWorthwhile:
      "Not worthwhile when the pitch is a paid backlink rather than newsletter exposure.",
    expectedLinkTreatment: "UNKNOWN",
    seoLinkValue: "unknown",
    referralPotential: "low",
    brandValue: "low",
    leadValue: "none",
    audienceFit: "low",
    costDisplay: "$100–$500",
    budgetTier: "€1–250",
    provisionalDecision: "avoid",
    avoidReason: "Paid SEO link primary",
    avoidNotes:
      "Accept Primary/Spotlight for exposure only; avoid Backlink SKU when sold for SEO.",
    evidenceNotes: [
      "Live 2026-08-15: Backlink $100–$500 listed on Dupple what-is-a-primary-ad.",
    ],
  },
];

export function assertPaidLiveHitsPresent(hits: PaidLiveHit[]): void {
  if (hits.length === 0) {
    throw new Error(
      "Paid live hits are empty — live web search verification is required before qualifying paid promotion opportunities.",
    );
  }
}
