import type { CrmMigrationPlan } from "@/domain";
import { complexityLevelLabel } from "./complexity";
import {
  fieldMappingProgress,
  openMigrationRiskCount,
  totalRecordEstimate,
  userMappingProgress,
} from "./persistence";

function csvEscape(value: string): string {
  return `"${String(value).replace(/"/g, '""')}"`;
}

export function migrationPlanToPlainText(plan: CrmMigrationPlan): string {
  const lines: string[] = [];
  const progress = fieldMappingProgress(plan);
  const users = userMappingProgress(plan);
  const records = totalRecordEstimate(plan);

  lines.push("CRM MIGRATION PLAN — SoftwareGlimpse");
  lines.push("=".repeat(48));
  lines.push(
    plan.targetProductName
      ? `Target CRM: ${plan.targetProductName}`
      : plan.vendorNeutral
        ? "Target CRM: Vendor-neutral plan"
        : "Target CRM: Not selected",
  );
  if (plan.targetPlanLabel) lines.push(`Target plan: ${plan.targetPlanLabel}`);
  lines.push(`Sources: ${plan.sourceSystems.length}`);
  lines.push(`Objects: ${plan.objects.length}`);
  if (records !== null) lines.push(`Est. records: ~${records.toLocaleString()}`);
  if (progress.percentMapped !== null) {
    lines.push(
      `Fields mapped: ${progress.mapped} / ${progress.total} (${progress.percentMapped}%)`,
    );
  }
  lines.push(`Users mapped: ${users.mapped} / ${users.total}`);
  if (plan.complexity) {
    lines.push(`Complexity: ${complexityLevelLabel(plan.complexity.level)}`);
    for (const d of plan.complexity.drivers) {
      lines.push(`  - ${d.label}`);
    }
  }
  lines.push(`Open risks: ${openMigrationRiskCount(plan)}`);
  if (plan.targetGoLive) lines.push(`Target go-live: ${plan.targetGoLive}`);
  lines.push("");
  lines.push(
    "SoftwareGlimpse helps plan the migration but does not execute the migration itself.",
  );
  lines.push("");

  lines.push("SOURCE SYSTEMS");
  for (const s of plan.sourceSystems) {
    lines.push(
      `- ${s.name} (${s.type}) export:${s.exportAvailable} api:${s.apiAvailable}`,
    );
  }
  lines.push("");

  lines.push("OBJECT INVENTORY");
  for (const o of plan.objects) {
    lines.push(
      `- ${o.sourceObjectLabel} → ${o.targetObjectLabel ?? "?"} [${o.priority}] ${o.recordCount ?? "count unknown"}`,
    );
  }
  lines.push("");

  lines.push("FIELD MAPPING");
  for (const m of plan.fieldMappings) {
    lines.push(
      `- ${m.sourceObject}.${m.sourceField} → ${m.targetObject ?? "?"}.${m.targetField ?? "?"} [${m.status}] ${m.transformation}`,
    );
  }
  lines.push("");

  lines.push("USER MAPPING");
  for (const u of plan.userMappings) {
    lines.push(
      `- ${u.sourceUser} → ${u.targetUser ?? "?"} [${u.status}] active:${u.active}`,
    );
  }
  lines.push("");

  lines.push("PIPELINES");
  for (const p of plan.pipelineMappings) {
    lines.push(`- ${p.sourcePipelineName} → ${p.targetPipelineName ?? "?"}`);
    for (const st of p.stageMaps) {
      lines.push(`    ${st.sourceStage} → ${st.targetStage ?? "?"}`);
    }
  }
  lines.push("");

  lines.push("CLEANING");
  for (const t of plan.cleaningTasks) {
    const mark =
      t.status === "done" ? "[x]" : t.status === "not-applicable" ? "[-]" : "[ ]";
    lines.push(`${mark} ${t.label}`);
  }
  lines.push("");

  lines.push("TEST MIGRATION");
  lines.push(`Status: ${plan.testMigration.status}`);
  for (const s of plan.testMigration.steps) {
    const mark =
      s.status === "done" ? "[x]" : s.status === "not-applicable" ? "[-]" : "[ ]";
    lines.push(`${mark} ${s.label}`);
  }
  lines.push("");

  lines.push("VALIDATION");
  for (const v of plan.validationChecks) {
    lines.push(
      `- [${v.status}] ${v.objectLabel} / ${v.checkKind} src:${v.sourceCount ?? "?"} imported:${v.importedCount ?? "?"}`,
    );
  }
  lines.push("");

  lines.push("CUTOVER (planning defaults — editable)");
  for (const c of plan.cutoverSteps) {
    const mark =
      c.status === "done" ? "[x]" : c.status === "not-applicable" ? "[-]" : "[ ]";
    lines.push(`${mark} [${c.relativeDay}] ${c.title}`);
  }
  lines.push("");

  lines.push("ROLLBACK CONSIDERATIONS");
  lines.push(
    `- Retain source access: ${plan.rollback.retainSourceAccess ? "yes" : "no"}`,
  );
  lines.push(
    `- Preserve original export: ${plan.rollback.preserveOriginalExport ? "yes" : "no"}`,
  );
  lines.push(
    `- Do not delete source data: ${plan.rollback.doNotDeleteSourceData ? "yes" : "no"}`,
  );
  if (plan.rollback.goLiveApprover) {
    lines.push(`- Go-live approver: ${plan.rollback.goLiveApprover}`);
  }
  lines.push("");

  lines.push("RISKS");
  for (const r of plan.risks) {
    lines.push(`- [${r.severity}/${r.status}] ${r.title}`);
    lines.push(`  ${r.reason}`);
    lines.push(`  Action: ${r.recommendedAction}`);
  }
  lines.push("");

  lines.push("Generated by SoftwareGlimpse CRM Migration Planner");
  lines.push("Affiliate status does not influence this plan.");
  return lines.join("\n");
}

export function migrationChecklistText(plan: CrmMigrationPlan): string {
  const lines: string[] = [];
  lines.push("CRM MIGRATION CHECKLIST");
  lines.push("");

  const sections: Array<{
    title: string;
    items: Array<{ done: boolean; label: string }>;
  }> = [
    {
      title: "Discovery",
      items: [
        {
          done: plan.sourceSystems.length > 0,
          label: "Confirm sources",
        },
        {
          done: plan.sourceSystems.every((s) => Boolean(s.dataOwner)),
          label: "Confirm data owners",
        },
      ],
    },
    {
      title: "Inventory",
      items: plan.objects.map((o) => ({
        done: o.status === "ready" || o.priority === "do-not-migrate",
        label: `Inventory ${o.sourceObjectLabel}`,
      })),
    },
    {
      title: "Mapping",
      items: [
        {
          done: plan.fieldMappings.some((m) => m.status === "mapped"),
          label: "Map required fields",
        },
        {
          done: plan.userMappings.every(
            (u) => u.status === "mapped" || u.status === "excluded",
          ),
          label: "Map users / ownership",
        },
        {
          done:
            plan.pipelineMappings.length === 0 ||
            plan.pipelineMappings.every((p) =>
              p.stageMaps.every((s) => Boolean(s.targetStage)),
            ),
          label: "Map pipeline stages",
        },
      ],
    },
    {
      title: "Cleaning",
      items: plan.cleaningTasks.map((t) => ({
        done: t.status === "done" || t.status === "not-applicable",
        label: t.label,
      })),
    },
    {
      title: "Test",
      items: plan.testMigration.steps.map((s) => ({
        done: s.status === "done" || s.status === "not-applicable",
        label: s.label,
      })),
    },
    {
      title: "Cutover",
      items: plan.cutoverSteps.map((c) => ({
        done: c.status === "done" || c.status === "not-applicable",
        label: c.title,
      })),
    },
  ];

  for (const section of sections) {
    lines.push(section.title);
    for (const item of section.items) {
      lines.push(`${item.done ? "☑" : "☐"} ${item.label}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function fieldMappingToCsv(plan: CrmMigrationPlan): string {
  const header = [
    "source_system_id",
    "source_object",
    "source_field",
    "source_type",
    "example_value",
    "target_object",
    "target_field",
    "target_type",
    "transformation",
    "required",
    "status",
    "notes",
  ];
  const rows = [header.map(csvEscape).join(",")];
  for (const m of plan.fieldMappings) {
    rows.push(
      [
        m.sourceSystemId,
        m.sourceObject,
        m.sourceField,
        m.sourceType ?? "",
        m.exampleValue ?? "",
        m.targetObject ?? "",
        m.targetField ?? "",
        m.targetType ?? "",
        m.transformation,
        m.required ? "yes" : "no",
        m.status,
        m.notes ?? "",
      ]
        .map(csvEscape)
        .join(","),
    );
  }
  return rows.join("\n");
}

/** Multi-sheet workbook as sequential CSV sections (no XLSX dependency). */
export function migrationWorkbookCsv(plan: CrmMigrationPlan): string {
  const parts: string[] = [];

  parts.push("### Summary");
  parts.push(
    ["key", "value"]
      .map(csvEscape)
      .join(","),
  );
  const progress = fieldMappingProgress(plan);
  const summaryRows: Array<[string, string]> = [
    ["target", plan.targetProductName ?? (plan.vendorNeutral ? "vendor-neutral" : "")],
    ["sources", String(plan.sourceSystems.length)],
    ["objects", String(plan.objects.length)],
    ["fields_mapped", `${progress.mapped}/${progress.total}`],
    ["complexity", plan.complexity?.level ?? ""],
    ["open_risks", String(openMigrationRiskCount(plan))],
  ];
  for (const [k, v] of summaryRows) {
    parts.push([k, v].map(csvEscape).join(","));
  }

  parts.push("");
  parts.push("### Sources");
  parts.push(
    ["id", "name", "type", "export", "api", "format", "owner"]
      .map(csvEscape)
      .join(","),
  );
  for (const s of plan.sourceSystems) {
    parts.push(
      [
        s.id,
        s.name,
        s.type,
        s.exportAvailable,
        s.apiAvailable,
        s.formatKnown,
        s.dataOwner ?? "",
      ]
        .map(csvEscape)
        .join(","),
    );
  }

  parts.push("");
  parts.push("### Objects");
  parts.push(
    [
      "id",
      "source",
      "object",
      "target",
      "records",
      "priority",
      "history",
      "status",
    ]
      .map(csvEscape)
      .join(","),
  );
  for (const o of plan.objects) {
    parts.push(
      [
        o.id,
        o.sourceSystemId,
        o.sourceObjectLabel,
        o.targetObjectLabel ?? "",
        o.recordCount == null ? "" : String(o.recordCount),
        o.priority,
        o.historyDepth,
        o.status,
      ]
        .map(csvEscape)
        .join(","),
    );
  }

  parts.push("");
  parts.push("### Field Mapping");
  parts.push(fieldMappingToCsv(plan));

  parts.push("");
  parts.push("### Value Mapping");
  parts.push(
    ["id", "field_mapping_id", "source_value", "target_value", "status"]
      .map(csvEscape)
      .join(","),
  );
  for (const v of plan.valueMappings) {
    parts.push(
      [v.id, v.fieldMappingId, v.sourceValue, v.targetValue ?? "", v.status]
        .map(csvEscape)
        .join(","),
    );
  }

  parts.push("");
  parts.push("### Users");
  parts.push(
    ["id", "source_user", "email", "active", "target_user", "role", "status"]
      .map(csvEscape)
      .join(","),
  );
  for (const u of plan.userMappings) {
    parts.push(
      [
        u.id,
        u.sourceUser,
        u.email ?? "",
        u.active,
        u.targetUser ?? "",
        u.role ?? "",
        u.status,
      ]
        .map(csvEscape)
        .join(","),
    );
  }

  parts.push("");
  parts.push("### Pipelines");
  parts.push(
    ["pipeline_id", "source_pipeline", "source_stage", "target_pipeline", "target_stage"]
      .map(csvEscape)
      .join(","),
  );
  for (const p of plan.pipelineMappings) {
    for (const st of p.stageMaps) {
      parts.push(
        [
          p.id,
          p.sourcePipelineName,
          st.sourceStage,
          p.targetPipelineName ?? "",
          st.targetStage ?? "",
        ]
          .map(csvEscape)
          .join(","),
      );
    }
  }

  parts.push("");
  parts.push("### Cleaning");
  parts.push(
    ["id", "label", "status", "owner", "category"].map(csvEscape).join(","),
  );
  for (const t of plan.cleaningTasks) {
    parts.push(
      [t.id, t.label, t.status, t.owner ?? "", t.category]
        .map(csvEscape)
        .join(","),
    );
  }

  parts.push("");
  parts.push("### Validation");
  parts.push(
    [
      "id",
      "object",
      "kind",
      "source_count",
      "imported_count",
      "sample",
      "status",
    ]
      .map(csvEscape)
      .join(","),
  );
  for (const v of plan.validationChecks) {
    parts.push(
      [
        v.id,
        v.objectLabel,
        v.checkKind,
        v.sourceCount == null ? "" : String(v.sourceCount),
        v.importedCount == null ? "" : String(v.importedCount),
        v.validatedSampleCount == null ? "" : String(v.validatedSampleCount),
        v.status,
      ]
        .map(csvEscape)
        .join(","),
    );
  }

  parts.push("");
  parts.push("### Risks");
  parts.push(
    ["id", "title", "severity", "status", "reason", "action"]
      .map(csvEscape)
      .join(","),
  );
  for (const r of plan.risks) {
    parts.push(
      [r.id, r.title, r.severity, r.status, r.reason, r.recommendedAction]
        .map(csvEscape)
        .join(","),
    );
  }

  parts.push("");
  parts.push("### Cutover");
  parts.push(
    ["id", "relative_day", "title", "status"].map(csvEscape).join(","),
  );
  for (const c of plan.cutoverSteps) {
    parts.push(
      [c.id, c.relativeDay, c.title, c.status].map(csvEscape).join(","),
    );
  }

  return parts.join("\n");
}

export function downloadTextFile(
  filename: string,
  content: string,
  mime = "text/plain;charset=utf-8",
): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
