import { requirementLabel } from "@/data/config/plan-selector/requirements";
import type { CrmPlanSelectorAnswers } from "@/domain";
import { formatMoney } from "@/domain";
import type { PlanSelectorAnalysis } from "./analyze";

/** Plain-text / Markdown download — no email gate. */
export function buildPlanSelectorMarkdown(
  analysis: PlanSelectorAnalysis,
  answers: CrmPlanSelectorAnswers,
): string {
  const lines: string[] = [];
  lines.push(`# CRM Plan Recommendation — ${analysis.productName}`);
  lines.push("");
  lines.push(`Generated by SoftwareGlimpse CRM Plan Selector.`);
  lines.push("");

  if (analysis.recommendedPlan) {
    lines.push(`## Recommended plan`);
    lines.push("");
    lines.push(`**${analysis.recommendedPlan.name}**`);
    lines.push("");
    lines.push(analysis.explanation);
    lines.push("");
  } else {
    lines.push(`## Result`);
    lines.push("");
    lines.push(analysis.explanation);
    lines.push("");
  }

  lines.push(`## Team assumptions`);
  lines.push("");
  lines.push(`- CRM users (now): ${answers.crmUsers}`);
  if (answers.usersIn12Months != null) {
    lines.push(`- CRM users (12 months): ${answers.usersIn12Months}`);
  }
  lines.push(`- Billing preference: ${answers.billingPreference}`);
  lines.push(`- Preference: ${answers.preference}`);
  lines.push("");

  lines.push(`## Must-have requirements`);
  lines.push("");
  if (analysis.mustHaveSlugs.length === 0) {
    lines.push("- (none selected)");
  } else {
    for (const slug of analysis.mustHaveSlugs) {
      lines.push(`- ${requirementLabel(slug)}`);
    }
  }
  lines.push("");

  if (analysis.niceToHaveSlugs.length > 0) {
    lines.push(`## Nice-to-have requirements`);
    lines.push("");
    for (const slug of analysis.niceToHaveSlugs) {
      lines.push(`- ${requirementLabel(slug)}`);
    }
    lines.push("");
  }

  lines.push(`## Plan ladder`);
  lines.push("");
  for (const entry of analysis.planLadder) {
    const mark =
      entry.status === "recommended"
        ? "✓ RECOMMENDED"
        : entry.status === "failed"
          ? "✕"
          : entry.status === "upgrade"
            ? "↑"
            : "·";
    lines.push(
      `- ${mark} **${entry.plan.name}** — ${entry.summary}`,
    );
  }
  lines.push("");

  if (analysis.requirementDrivers.length > 0) {
    lines.push(`## What is driving your plan`);
    lines.push("");
    for (const d of analysis.requirementDrivers) {
      lines.push(
        `- ${d.label}: forces upgrade from ${d.fromPlanName ?? "lower plan"} → ${d.toPlanName}`,
      );
    }
    lines.push("");
  }

  if (analysis.pricingNow) {
    lines.push(`## Pricing estimate (list)`);
    lines.push("");
    lines.push(
      `- Estimated monthly equivalent: ${formatMoney(analysis.pricingNow.monthlyEquivalent)}`,
    );
    lines.push(
      `- Estimated annual: ${formatMoney(analysis.pricingNow.annualCost)}`,
    );
    for (const a of analysis.pricingNow.assumptions) {
      lines.push(`- Assumption: ${a}`);
    }
    lines.push("");
  } else {
    lines.push(`## Pricing estimate`);
    lines.push("");
    lines.push(
      "Exact pricing depends on configuration / contact vendor — no invented total.",
    );
    lines.push("");
  }

  if (analysis.unknowns.length > 0) {
    lines.push(`## Unknowns requiring vendor confirmation`);
    lines.push("");
    for (const u of analysis.unknowns) {
      lines.push(`- ${requirementLabel(u)}`);
    }
    lines.push("");
  }

  lines.push(`## Confidence`);
  lines.push("");
  lines.push(`**${analysis.confidence.toUpperCase()}**`);
  for (const r of analysis.confidenceReasons) {
    lines.push(`- ${r}`);
  }
  lines.push("");

  if (analysis.verifiedAt) {
    lines.push(`Plan information last checked: ${analysis.verifiedAt}`);
    lines.push("");
  }

  lines.push(`## Next-step questions for the vendor`);
  lines.push("");
  lines.push("- Confirm current list vs promotional pricing for my seat count.");
  lines.push("- Confirm which edition includes each must-have above.");
  lines.push("- Ask about seat minimums, light seats, and required add-ons.");
  lines.push("- Clarify usage limits that could force an upgrade as we grow.");
  lines.push("");

  return lines.join("\n");
}
