import type {
  AssetEnrichmentBacklogItem,
  AssetEnrichmentBacklogReport,
  AssetImplementationBatch,
} from "@/domain/schemas/asset-discovery";

function esc(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 220);
}

const BATCH_LABELS: Record<AssetImplementationBatch, string> = {
  "official-videos-to-embed": "Official videos to embed",
  "official-docs-to-link": "Official docs to link",
  "screenshots-to-add": "Screenshots to add",
  "existing-research-media-to-reuse": "Existing ResearchMedia to reuse",
  "original-diagrams-to-create": "Original diagrams to create",
  "original-workflow-visuals-to-create": "Original workflow visuals to create",
  "stale-media-to-replace": "Stale media to replace",
  "template-fix": "Template fixes",
};

function tableRow(i: AssetEnrichmentBacklogItem): string {
  return (
    `| ${i.priority} | ${esc(i.page)} | ${esc(i.pageType)} | ${esc(i.section)} | ${esc(i.asset)} | ${esc(i.assetType)} | ${esc(i.source)} | ${i.official ? "yes" : "no"} | ${esc(i.recommendation)} | ${esc(i.whatItAdds)} | ${esc(i.relatedContentQualityIssue ?? "—")} | ${esc(i.researchEvidenceImpact)} | ${i.implementationEffort} | ${esc(i.usageConstraints)} |`
  );
}

const TABLE_HEADER = `| Priority | Page | Page type | Section | Asset | Asset type | Source | Official? | Recommendation | What it adds | Related content-quality issue | Research/evidence impact | Implementation effort | Usage constraints |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |`;

function sectionForBand(
  report: AssetEnrichmentBacklogReport,
  band: "A0" | "A1" | "A2" | "A3",
  limit?: number,
): string[] {
  const lines: string[] = [];
  let rows = report.items.filter((i) => i.priority === band);
  if (limit != null) rows = rows.slice(0, limit);
  lines.push(TABLE_HEADER);
  if (rows.length === 0) {
    lines.push("| — | — | — | — | — | — | — | — | — | — | — | — | — | — |");
  } else {
    for (const i of rows) lines.push(tableRow(i));
  }
  return lines;
}

export function formatAssetEnrichmentBacklogMarkdown(
  report: AssetEnrichmentBacklogReport,
): string {
  const s = report.summary;
  const lines: string[] = [];

  lines.push("# Asset Enrichment Backlog");
  lines.push("");
  lines.push(
    `> Generated by **AssetOpportunityPrioritizationAgent** \`${report.agentVersion}\`. Prioritization only — does **not** implement, embed, download, or publish assets.`,
  );
  lines.push("");
  lines.push(`- **Generated:** ${report.generatedAt}`);
  lines.push(
    `- **Totals:** A0 ${s.a0} · A1 ${s.a1} · A2 ${s.a2} · A3 ${s.a3} · Template ${s.templateOpportunities} · Page-specific ${s.pageSpecificOpportunities} · Original visuals ${s.originalVisualOpportunities}`,
  );
  lines.push("");
  lines.push("## Inputs");
  lines.push("");
  for (const inp of report.inputs) {
    lines.push(`- \`${inp}\``);
  }
  lines.push("");
  lines.push("## Priority factors (not asset count)");
  lines.push("");
  lines.push(
    "Page importance · current quality weakness · asset relevance · buyer usefulness · evidence value · differentiation · ease of use · source quality · freshness · implementation effort.",
  );
  lines.push("");
  lines.push(
    "**Do not prioritize by asset count** — one excellent workflow video can outrank fifteen screenshots.",
  );
  lines.push("");
  lines.push("## Priority bands");
  lines.push("");
  lines.push("| Band | Meaning | Count |");
  lines.push("| --- | --- | ---: |");
  lines.push(
    `| **A0** | Critical / high-impact missing media on important pages | ${s.a0} |`,
  );
  lines.push(`| **A1** | Strong near-term improvement | ${s.a1} |`);
  lines.push(`| **A2** | Useful enhancement | ${s.a2} |`);
  lines.push(`| **A3** | Optional | ${s.a3} |`);
  lines.push("");

  lines.push("## Final report snapshot");
  lines.push("");
  lines.push("| Metric | Count |");
  lines.push("| --- | ---: |");
  lines.push(`| A0 | ${s.a0} |`);
  lines.push(`| A1 | ${s.a1} |`);
  lines.push(`| A2 | ${s.a2} |`);
  lines.push(`| A3 | ${s.a3} |`);
  lines.push(`| Template opportunities | ${s.templateOpportunities} |`);
  lines.push(`| Page-specific opportunities | ${s.pageSpecificOpportunities} |`);
  lines.push(
    `| Original visual opportunities | ${s.originalVisualOpportunities} |`,
  );
  lines.push("");

  lines.push("## Top 30 actions");
  lines.push("");
  lines.push(TABLE_HEADER);
  for (const i of report.topActions) {
    lines.push(tableRow(i));
  }
  lines.push("");

  lines.push("## Systemic / template opportunities");
  lines.push("");
  lines.push(
    "Prefer **TEMPLATE FIX** when one platform change closes many gaps.",
  );
  lines.push("");
  if (report.systemicOpportunities.length === 0) {
    lines.push("_No systemic patterns above threshold._");
  } else {
    for (const sys of report.systemicOpportunities) {
      lines.push(`### ${sys.id} — ${sys.title} (${sys.priority})`);
      lines.push("");
      lines.push(`- **Count:** ${sys.count}`);
      lines.push(`- **Fix class:** ${sys.fixClass}`);
      lines.push(`- **Effort:** ${sys.implementationEffort}`);
      lines.push(
        `- **Products (sample):** ${sys.products.slice(0, 12).join(", ") || "—"}`,
      );
      lines.push(
        `- **Routes (sample):** ${sys.affectedRoutes
          .slice(0, 8)
          .map((r) => `\`${r}\``)
          .join(", ") || "—"}`,
      );
      lines.push(`- **What it adds:** ${sys.whatItAdds}`);
      lines.push(`- **Recommendation:** ${sys.recommendation}`);
      lines.push("");
    }
  }

  lines.push("## Grouped by implementation type");
  lines.push("");
  for (const [batch, label] of Object.entries(BATCH_LABELS) as [
    AssetImplementationBatch,
    string,
  ][]) {
    const rows = report.items.filter((i) => i.implementationBatch === batch);
    lines.push(`### ${label} (${rows.length})`);
    lines.push("");
    if (rows.length === 0) {
      lines.push("_None._");
      lines.push("");
      continue;
    }
    lines.push(TABLE_HEADER);
    for (const i of rows.slice(0, 40)) lines.push(tableRow(i));
    if (rows.length > 40) {
      lines.push("");
      lines.push(`_…and ${rows.length - 40} more in this batch._`);
    }
    lines.push("");
  }

  lines.push("## Grouped by product");
  lines.push("");
  const products = Object.entries(s.byProduct).sort((a, b) => b[1] - a[1]);
  lines.push("| Product | Items |");
  lines.push("| --- | ---: |");
  for (const [slug, n] of products) {
    lines.push(`| ${slug} | ${n} |`);
  }
  if (products.length === 0) lines.push("| — | 0 |");
  lines.push("");

  for (const [slug] of products.slice(0, 12)) {
    const rows = report.items
      .filter((i) => i.productSlug === slug && !i.isTemplateFix)
      .slice(0, 15);
    if (rows.length === 0) continue;
    lines.push(`### ${slug}`);
    lines.push("");
    lines.push(TABLE_HEADER);
    for (const i of rows) lines.push(tableRow(i));
    lines.push("");
  }

  lines.push("## Grouped by cluster");
  lines.push("");
  const clusters = Object.entries(s.byCluster).sort((a, b) => b[1] - a[1]);
  lines.push("| Cluster | Items |");
  lines.push("| --- | ---: |");
  for (const [c, n] of clusters) {
    lines.push(`| ${c} | ${n} |`);
  }
  lines.push("");

  for (const [cluster] of clusters) {
    const rows = report.items
      .filter((i) => i.cluster === cluster)
      .slice(0, 20);
    lines.push(`### ${cluster} (${s.byCluster[cluster] ?? 0})`);
    lines.push("");
    lines.push(TABLE_HEADER);
    for (const i of rows) lines.push(tableRow(i));
    const total = s.byCluster[cluster] ?? 0;
    if (total > 20) {
      lines.push("");
      lines.push(`_…and ${total - 20} more in this cluster._`);
    }
    lines.push("");
  }

  lines.push("## Full backlog by priority band");
  lines.push("");
  lines.push("### A0 — Critical / high-impact");
  lines.push("");
  lines.push(...sectionForBand(report, "A0"));
  lines.push("");
  lines.push("### A1 — Strong near-term");
  lines.push("");
  lines.push(...sectionForBand(report, "A1", 80));
  lines.push("");
  lines.push("### A2 — Useful enhancement (top 60)");
  lines.push("");
  lines.push(...sectionForBand(report, "A2", 60));
  lines.push("");
  lines.push("### A3 — Optional (top 40)");
  lines.push("");
  lines.push(...sectionForBand(report, "A3", 40));
  lines.push("");

  lines.push("## Guardrails");
  lines.push("");
  lines.push("- Recommendations only — no auto-embed / download / publish");
  lines.push("- Do not invent asset URLs");
  lines.push("- Affiliate URLs are never evidence");
  lines.push("- Prefer primary official / authoritative sources");
  lines.push(
    "- Prefer original SoftwareGlimpse visuals when vendor imagery rights are unclear",
  );
  lines.push("- Media must not affect rankings");
  lines.push("");

  return `${lines.join("\n")}\n`;
}
