/**
 * CRM Field Mapping Template — Excel working artifact (slug: crm-field-mapping-template).
 * Blank inputs + EXAMPLE-marked teaching rows only. Formulas compute when opened in Excel.
 * Do not invent vendor capabilities as SoftwareGlimpse research.
 */

type AOA = (string | number | null)[][];

/** Field-map data rows: Excel rows 6–40 (header on row 5). */
const FIELD_DATA_FIRST = 6;
const FIELD_DATA_LAST = 40;

const FIELD_HEADERS = [
  "ID",
  "Source System",
  "Source Object",
  "Source Field",
  "Source Label",
  "Source Type",
  "Source Required",
  "Example Value",
  "Target System",
  "Target Object",
  "Target Field",
  "Target Label",
  "Target Type",
  "Target Required",
  "Mapping Type",
  "Transformation Rule",
  "Default Value",
  "Value Map Required",
  "Lookup Rule",
  "Null Handling",
  "Duplicate Handling",
  "Business Owner",
  "Technical Owner",
  "Migration Scope",
  "Data Classification",
  "Validation Rule",
  "Test Status",
  "Migration Status",
  "Issue",
  "Notes",
] as const;

/** Build all sheets as array-of-arrays; formulas as Excel formula strings. */
export function buildCrmFieldMappingWorkbookAoa(): {
  name: string;
  aoa: AOA;
  cols?: { wch: number }[];
}[] {
  const readme: AOA = [
    ["SoftwareGlimpse — CRM Field Mapping Template (Excel)"],
    ["Updated", new Date().toISOString().slice(0, 10)],
    ["Stable slug", "crm-field-mapping-template"],
    ["Version", "1.0"],
    [],
    ["Purpose"],
    [
      "This workbook is the primary working artifact for source→target CRM field mapping: objects, fields, transforms, value maps, lookups, validation, and open decisions. It is not a checklist dump — fill it from real schemas and lock it before load.",
    ],
    [],
    ["How to use"],
    ["1. Complete 02_PROJECT (systems, owners, target date, environment)."],
    [
      "2. List objects on 03_OBJECT_MAP (migrate yes/no, volumes, strategy, owner).",
    ],
    [
      "3. Map fields on 04_FIELD_MAP — one row per source field (or explicit new-target / do-not-migrate decision).",
    ],
    [
      "4. Detail picklists on 05_VALUE_MAPS, reusable rules on 06_TRANSFORMATIONS, and owner/key lookups on 07_LOOKUPS.",
    ],
    [
      "5. Record sample tests on 08_VALIDATION; log blockers and decisions on 09_ISSUES_DECISIONS.",
    ],
    [
      "6. Review 10_DASHBOARD counts and readiness text — formulas recalculate when you open the file in Excel / Google Sheets.",
    ],
    [
      "7. EXAMPLE — rows are teaching only (illustrative Pipedrive→HubSpot). Replace or clear them. Do not treat EXAMPLE rows as SoftwareGlimpse research or vendor guarantees.",
    ],
    [],
    ["Status definitions (Migration Status / Issue Status)"],
    ["Draft", "Row proposed; not yet reviewed"],
    ["In review", "Awaiting business or technical acceptance"],
    ["Approved", "Accepted for the locked mapping version"],
    ["Blocked", "Cannot proceed until a decision or fix lands"],
    ["Deferred", "Out of this cutover; tracked deliberately"],
    ["Done", "Implemented and verified for this scope"],
    [],
    ["Test Status definitions"],
    ["Not tested", "No sample run yet — do not invent Pass"],
    ["Pass", "Sample input produced the expected output"],
    ["Fail", "Sample did not match expected output"],
    ["Blocked", "Cannot test until an upstream issue is resolved"],
    [],
    ["Mapping Type definitions (allowed values on 04_FIELD_MAP)"],
    ["Direct", "Same meaning and compatible type; copy as-is (or trivial cast)"],
    ["Rename", "Same meaning; different field API name / label only"],
    ["Transform", "Shape change (format, units, trim, case, parse) without a picklist table"],
    ["Concatenate", "Combine multiple source fields into one target"],
    ["Split", "Split one source field into multiple targets"],
    ["Lookup", "Resolve via another table/user list (e.g. owner email → user id)"],
    ["Calculated", "Derived from other fields or constants at load time"],
    ["Default value", "No source; set a documented default"],
    ["Value mapping", "Discrete source values map to allowed target values (see 05_VALUE_MAPS)"],
    ["Do not migrate", "Explicitly excluded from this migration"],
    ["Archive", "Retain offline / archive store; not loaded to live CRM"],
    ["New target field", "No source equivalent; create and populate in target process"],
    ["Manual remediation", "Cannot automate safely; human fix before or after load"],
    [],
    ["Recommended workflow"],
    ["A. Export real source schema / sample rows per object."],
    ["B. Confirm required target fields in the configured CRM."],
    ["C. Map required targets first; every required target needs a source, transform, default, or explicit exclusion with an owner."],
    ["D. Attach value maps and lookups; write one sample + expected output for non-trivial rules."],
    ["E. Run 08_VALIDATION; clear 09 blockers; freeze a version id on 02_PROJECT Notes."],
    [],
    ["Excel UX notes (SheetJS community build)"],
    [
      "Freeze panes: freeze below the header row on 04_FIELD_MAP (View → Freeze Panes) after open — intended freeze is row 5 headers + columns A–D visible.",
    ],
    [
      "Dropdowns (set Data Validation in Excel): Mapping Type (list above); Source/Target Required = Yes/No; Value Map Required = Yes/No; Migrate? = Yes/No/Partial; Test Status; Migration Status; Issue Severity = Blocker/Critical/Major/Minor; Issue Status = Open/Decided/Closed.",
    ],
    [
      "AutoFilter is enabled on 04_FIELD_MAP header row when generated. Column widths are pre-set; extend data through Excel row 40 (dashboard formulas use D6:D40 / O6:O40 / N6:N40).",
    ],
    [],
    ["Sheet map"],
    ["01_README", "Purpose, instructions, definitions, links (this sheet)"],
    ["02_PROJECT", "Project metadata and owners"],
    ["03_OBJECT_MAP", "Object-level migrate scope"],
    ["04_FIELD_MAP", "Primary field dictionary (working artifact)"],
    ["05_VALUE_MAPS", "Picklist / enum value translations"],
    ["06_TRANSFORMATIONS", "Named transform catalogue (TR-###)"],
    ["07_LOOKUPS", "Lookup rules (owners, keys, references)"],
    ["08_VALIDATION", "Sample tests against mapping rules"],
    ["09_ISSUES_DECISIONS", "Open issues and decisions log"],
    ["10_DASHBOARD", "Counts + readiness (formulas; no fabricated %)"],
    [],
    ["Related SoftwareGlimpse resources"],
    [
      "CRM Field Mapping Template (this resource)",
      "https://softwareglimpse.com/resources/crm-field-mapping-template/",
    ],
    [
      "CRM Field Mapping Guide",
      "https://softwareglimpse.com/guides/crm-field-mapping/",
    ],
    [
      "CRM Data Migration Guide",
      "https://softwareglimpse.com/guides/crm-data-migration/",
    ],
    [
      "CRM Data Migration Template",
      "https://softwareglimpse.com/resources/crm-data-migration-template/",
    ],
    [
      "CRM Migration Checklist",
      "https://softwareglimpse.com/resources/crm-migration-checklist/",
    ],
    [
      "CRM Implementation Guide",
      "https://softwareglimpse.com/guides/crm-implementation/",
    ],
  ];

  const project: AOA = [
    ["02 — PROJECT"],
    [],
    ["Project", ""],
    ["Source CRM", ""],
    ["Target CRM", ""],
    ["Migration owner", ""],
    ["Business owner", ""],
    ["Data owner", ""],
    ["Implementation partner", ""],
    ["Target date", ""],
    ["Environment", ""],
    ["Notes", ""],
  ];

  // 03_OBJECT_MAP — header Excel row 5; EXAMPLE + blanks from row 6
  const objectMap: AOA = [
    ["03 — OBJECT MAP"],
    [],
    [
      "EXAMPLE rows illustrate a Pipedrive→HubSpot object scope for teaching only. Replace with your systems. Do not invent volumes.",
    ],
    [],
    [
      "Source System",
      "Source Object",
      "Target System",
      "Target Object",
      "Migrate?",
      "Approx Record Count",
      "Migration Strategy",
      "Owner",
      "Status",
      "Notes",
    ],
    [
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Person",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Contact",
      "Yes",
      "",
      "Full load then delta",
      "",
      "Draft",
      "Teaching row — clear or replace",
    ],
    [
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Organization",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Company",
      "Yes",
      "",
      "Full load; match on domain/name",
      "",
      "Draft",
      "Teaching row — clear or replace",
    ],
    [
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Deal",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Deal",
      "Yes",
      "",
      "Open + closed (window TBD)",
      "",
      "Draft",
      "Teaching row — clear or replace",
    ],
    [
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Activity",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Engagement",
      "Partial",
      "",
      "Notes/calls only; skip system noise",
      "",
      "Draft",
      "Teaching row — clear or replace",
    ],
    ...Array.from({ length: 12 }, () => [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ]),
  ];

  const blankFieldRow = (): (string | number | null)[] =>
    Array.from({ length: FIELD_HEADERS.length }, () => "");

  // 04_FIELD_MAP — PRIMARY. Header Excel row 5; data rows 6–40.
  const fieldExamples: AOA = [
    [
      "FM-001",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Person",
      "EXAMPLE — email",
      "Email",
      "string",
      "Yes",
      "alex@example.com",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Contact",
      "email",
      "Email",
      "string",
      "Yes",
      "Direct",
      "",
      "",
      "No",
      "",
      "Reject if blank on create",
      "Match existing on email",
      "",
      "",
      "In scope",
      "PII",
      "Valid email format",
      "Not tested",
      "Draft",
      "",
      "EXAMPLE — Direct copy",
    ],
    [
      "FM-002",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Deal",
      "EXAMPLE — title",
      "Deal title",
      "string",
      "Yes",
      "Acme renewal",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Deal",
      "dealname",
      "Deal Name",
      "string",
      "Yes",
      "Rename",
      "Map title → dealname",
      "",
      "No",
      "",
      "Reject if blank",
      "Allow duplicate names",
      "",
      "",
      "In scope",
      "Internal",
      "Non-empty string",
      "Not tested",
      "Draft",
      "",
      "EXAMPLE — Rename only",
    ],
    [
      "FM-003",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Deal",
      "EXAMPLE — value",
      "Value",
      "currency/amount",
      "No",
      "€12,500.00",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Deal",
      "amount",
      "Amount",
      "number",
      "No",
      "Transform",
      "TR-001 — strip currency symbols and thousands separators; parse decimal",
      "",
      "No",
      "",
      "Leave blank if source blank",
      "",
      "",
      "",
      "In scope",
      "Financial",
      "Numeric ≥ 0",
      "Not tested",
      "Draft",
      "",
      "EXAMPLE — Transform (see 06)",
    ],
    [
      "FM-004",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Deal",
      "EXAMPLE — stage_id",
      "Stage",
      "enum",
      "Yes",
      "Verbal",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Deal",
      "dealstage",
      "Deal Stage",
      "enumeration",
      "Yes",
      "Value mapping",
      "Use VM-STAGE (05_VALUE_MAPS)",
      "",
      "Yes",
      "",
      "Block load if unmapped stage",
      "",
      "",
      "",
      "In scope",
      "Internal",
      "Target value in allowed pipeline stages",
      "Not tested",
      "Draft",
      "",
      "EXAMPLE — Value mapping",
    ],
    [
      "FM-005",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Deal",
      "EXAMPLE — owner_email",
      "Owner email",
      "string",
      "Yes",
      "sam@company.com",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Deal",
      "hubspot_owner_id",
      "Deal owner",
      "enumeration",
      "Yes",
      "Lookup",
      "LU-001 — owner email → active HubSpot user id",
      "",
      "No",
      "LU-001",
      "If no match: assign fallback owner (document on 07)",
      "",
      "",
      "",
      "In scope",
      "PII",
      "Resolved owner exists and is active",
      "Not tested",
      "Draft",
      "",
      "EXAMPLE — Lookup (see 07)",
    ],
    [
      "FM-006",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Person",
      "EXAMPLE — first_name",
      "First name",
      "string",
      "No",
      "Alex",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Contact",
      "firstname",
      "First Name",
      "string",
      "No",
      "Direct",
      "",
      "",
      "No",
      "",
      "Allow blank",
      "",
      "",
      "",
      "In scope",
      "PII",
      "",
      "Not tested",
      "Draft",
      "",
      "EXAMPLE — Optional direct",
    ],
    [
      "FM-007",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Person",
      "EXAMPLE — last_name",
      "Last name",
      "string",
      "No",
      "Rivera",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Contact",
      "lastname",
      "Last Name",
      "string",
      "No",
      "Direct",
      "",
      "",
      "No",
      "",
      "Allow blank",
      "",
      "",
      "",
      "In scope",
      "PII",
      "",
      "Not tested",
      "Draft",
      "",
      "EXAMPLE — Optional direct",
    ],
    [
      "FM-008",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Deal",
      "EXAMPLE — internal_sync_hash",
      "Internal sync hash",
      "string",
      "No",
      "a1b2c3",
      "",
      "",
      "",
      "",
      "",
      "",
      "Do not migrate",
      "",
      "",
      "No",
      "",
      "N/A",
      "N/A",
      "",
      "",
      "Out of scope",
      "Internal",
      "",
      "Not tested",
      "Approved",
      "",
      "EXAMPLE — Explicit exclusion",
    ],
  ];

  const fieldBlankCount =
    FIELD_DATA_LAST - FIELD_DATA_FIRST + 1 - fieldExamples.length;
  const fieldMap: AOA = [
    ["04 — FIELD MAP (primary working artifact)"],
    [],
    [
      `One row per field decision. Data range for dashboard formulas: Excel rows ${FIELD_DATA_FIRST}–${FIELD_DATA_LAST}. EXAMPLE — rows are teaching only — replace or clear. Prefer required target fields first.`,
    ],
    [],
    [...FIELD_HEADERS],
    ...fieldExamples,
    ...Array.from({ length: Math.max(0, fieldBlankCount) }, () =>
      blankFieldRow(),
    ),
  ];

  const valueMaps: AOA = [
    ["05 — VALUE MAPS"],
    [],
    [
      "Picklist / enum translations referenced from 04 (Value Map Required = Yes). EXAMPLE rows are teaching only.",
    ],
    [],
    [
      "Value Map ID",
      "Source System",
      "Source Object",
      "Source Field",
      "Source Value",
      "Target System",
      "Target Object",
      "Target Field",
      "Target Value",
      "Owner",
      "Status",
      "Notes",
    ],
    [
      "VM-STAGE",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Deal",
      "EXAMPLE — stage_id",
      "EXAMPLE — Qualified",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Deal",
      "dealstage",
      "appointmentscheduled",
      "",
      "Draft",
      "Teaching row — replace with real pipeline values",
    ],
    [
      "VM-STAGE",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Deal",
      "EXAMPLE — stage_id",
      "EXAMPLE — Verbal",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Deal",
      "dealstage",
      "presentationscheduled",
      "",
      "Draft",
      "Teaching row — replace with real pipeline values",
    ],
    [
      "VM-STAGE",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Deal",
      "EXAMPLE — stage_id",
      "EXAMPLE — Won",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Deal",
      "dealstage",
      "closedwon",
      "",
      "Draft",
      "Teaching row — replace with real pipeline values",
    ],
    [
      "VM-STAGE",
      "EXAMPLE — Pipedrive",
      "EXAMPLE — Deal",
      "EXAMPLE — stage_id",
      "EXAMPLE — Lost",
      "EXAMPLE — HubSpot",
      "EXAMPLE — Deal",
      "dealstage",
      "closedlost",
      "",
      "Draft",
      "Teaching row — replace with real pipeline values",
    ],
    ...Array.from({ length: 16 }, () => [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ]),
  ];

  const transformations: AOA = [
    ["06 — TRANSFORMATIONS"],
    [],
    [
      "Named transform catalogue. Reference Transform IDs from 04_FIELD_MAP. EXAMPLE rules are teaching only.",
    ],
    [],
    [
      "Transform ID",
      "Name",
      "Description",
      "Input Fields",
      "Output Field",
      "Rule (plain language)",
      "Owner",
      "Status",
      "Notes",
    ],
    [
      "TR-001",
      "EXAMPLE — Amount parse",
      "EXAMPLE — Parse currency-formatted deal value to number",
      "EXAMPLE — Deal.value",
      "amount",
      "Strip currency symbols and thousands separators; treat comma or dot per locale agreement; blank stays blank",
      "",
      "Draft",
      "Teaching row — clear or replace",
    ],
    [
      "TR-002",
      "EXAMPLE — Phone E.164-ish",
      "EXAMPLE — Normalize phone to digits with country code policy",
      "EXAMPLE — Person.phone",
      "phone",
      "Keep digits; apply agreed default country code when missing; reject extensions unless stored separately",
      "",
      "Draft",
      "Teaching row — clear or replace",
    ],
    [
      "TR-003",
      "EXAMPLE — Close date",
      "EXAMPLE — Convert source date/time to target date field",
      "EXAMPLE — Deal.expected_close_date",
      "closedate",
      "Interpret source timezone; store target date-only or midnight UTC per CRM setting",
      "",
      "Draft",
      "Teaching row — clear or replace",
    ],
    ...Array.from({ length: 12 }, () => [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ]),
  ];

  const lookups: AOA = [
    ["07 — LOOKUPS"],
    [],
    [
      "Lookup rules for owners, foreign keys, and reference resolution. EXAMPLE rows are teaching only.",
    ],
    [],
    [
      "Lookup ID",
      "Name",
      "Source Key Field",
      "Lookup Source",
      "Match On",
      "Return Field",
      "Fallback",
      "Owner",
      "Status",
      "Notes",
    ],
    [
      "LU-001",
      "EXAMPLE — Deal owner",
      "EXAMPLE — owner_email",
      "EXAMPLE — Target active users",
      "email (case-insensitive)",
      "hubspot_owner_id",
      "Document named fallback owner — do not invent",
      "",
      "Draft",
      "Teaching row — clear or replace",
    ],
    [
      "LU-002",
      "EXAMPLE — Company link",
      "EXAMPLE — org_id / domain",
      "EXAMPLE — Migrated companies",
      "external id or domain",
      "associated company id",
      "Queue for manual match if no hit",
      "",
      "Draft",
      "Teaching row — clear or replace",
    ],
    ...Array.from({ length: 12 }, () => [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ]),
  ];

  // 08_VALIDATION — blank test rows (plus light EXAMPLE guidance in title area only)
  const validation: AOA = [
    ["08 — VALIDATION"],
    [],
    [
      "Sample tests against mapping rules. Leave Result blank until executed. Do not invent Pass. Link Field Map ID to 04.",
    ],
    [],
    [
      "Test ID",
      "Field Map ID",
      "Object",
      "Field",
      "Test Type",
      "Sample Input",
      "Expected Output",
      "Actual Output",
      "Result",
      "Tester",
      "Date",
      "Notes",
    ],
    [
      "VT-001",
      "FM-003",
      "EXAMPLE — Deal",
      "EXAMPLE — amount",
      "Transform sample",
      "EXAMPLE — €12,500.00",
      "EXAMPLE — 12500",
      "",
      "Not tested",
      "",
      "",
      "EXAMPLE teaching row — replace with real samples",
    ],
    [
      "VT-002",
      "FM-004",
      "EXAMPLE — Deal",
      "EXAMPLE — dealstage",
      "Value map sample",
      "EXAMPLE — Verbal",
      "EXAMPLE — presentationscheduled",
      "",
      "Not tested",
      "",
      "",
      "EXAMPLE teaching row — replace with real samples",
    ],
    ...Array.from({ length: 18 }, () => [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ]),
  ];

  const issues: AOA = [
    ["09 — ISSUES & DECISIONS"],
    [],
    [
      "Log blockers and decisions that hold the mapping lock. Severity: Blocker / Critical / Major / Minor. Status: Open / Decided / Closed.",
    ],
    [],
    [
      "Issue ID",
      "Related Field / Object",
      "Severity",
      "Status",
      "Description",
      "Decision",
      "Owner",
      "Due Date",
      "Notes",
    ],
    [
      "ISS-001",
      "EXAMPLE — FM-005 / owner_email",
      "Critical",
      "Open",
      "EXAMPLE — Some source owner emails have no active target user; fallback not decided",
      "",
      "",
      "",
      "Teaching row — replace or clear; do not invent resolutions",
    ],
    ...Array.from({ length: 14 }, () => [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ]),
  ];

  // 10_DASHBOARD — formulas only; readiness is interpretable text (not a fake %).
  // Field map columns: D=Source Field, N=Target Required, O=Mapping Type
  // Validation Result col I rows 6–40; Issues Severity C / Status D rows 6–40
  const r = `'04_FIELD_MAP'`;
  const dRange = `${r}!D${FIELD_DATA_FIRST}:D${FIELD_DATA_LAST}`;
  const nRange = `${r}!N${FIELD_DATA_FIRST}:N${FIELD_DATA_LAST}`;
  const oRange = `${r}!O${FIELD_DATA_FIRST}:O${FIELD_DATA_LAST}`;

  const dashboard: AOA = [
    ["10 — DASHBOARD"],
    [],
    [
      `Counts reference ${r} rows ${FIELD_DATA_FIRST}–${FIELD_DATA_LAST}. Clear EXAMPLE rows before treating readiness as project status. No fabricated percentage.`,
    ],
    [],
    ["Metric", "Value", "Definition"],
    [
      "Total field rows",
      `=COUNTA(${dRange})`,
      "Non-blank Source Field",
    ],
    [
      "Mapped",
      `=COUNTIFS(${dRange},"<>",${oRange},"<>",${oRange},"<>Do not migrate")`,
      "Source Field filled; Mapping Type filled and not Do not migrate",
    ],
    [
      "Excluded",
      `=COUNTIF(${oRange},"Do not migrate")+COUNTIF(${oRange},"Archive")`,
      "Mapping Type = Do not migrate or Archive",
    ],
    [
      "Unmapped",
      `=COUNTIFS(${dRange},"<>",${oRange},"")`,
      "Source Field filled; Mapping Type blank",
    ],
    [
      "Direct",
      `=COUNTIF(${oRange},"Direct")`,
      "COUNTIF Mapping Type",
    ],
    [
      "Transform",
      `=COUNTIF(${oRange},"Transform")`,
      "COUNTIF Mapping Type",
    ],
    [
      "Value mapping",
      `=COUNTIF(${oRange},"Value mapping")`,
      "COUNTIF Mapping Type",
    ],
    [
      "Required target unmapped (BLOCKER)",
      `=COUNTIFS(${nRange},"Yes",${oRange},"")+COUNTIFS(${nRange},"Yes",${oRange},"Do not migrate")`,
      "Target Required = Yes AND (Mapping Type blank OR Do not migrate)",
    ],
    [
      "Open issues",
      `=COUNTIF('09_ISSUES_DECISIONS'!D6:D40,"Open")`,
      "09 Status = Open",
    ],
    [
      "Open blocker issues",
      `=COUNTIFS('09_ISSUES_DECISIONS'!C6:C40,"Blocker",'09_ISSUES_DECISIONS'!D6:D40,"Open")`,
      "Severity Blocker + Status Open",
    ],
    [
      "Open critical issues",
      `=COUNTIFS('09_ISSUES_DECISIONS'!C6:C40,"Critical",'09_ISSUES_DECISIONS'!D6:D40,"Open")`,
      "Severity Critical + Status Open",
    ],
    [
      "Tests passed",
      `=COUNTIF('08_VALIDATION'!I6:I40,"Pass")`,
      "08 Result = Pass",
    ],
    [
      "Tests failed",
      `=COUNTIF('08_VALIDATION'!I6:I40,"Fail")`,
      "08 Result = Fail",
    ],
    [
      "Tests not tested",
      `=COUNTIF('08_VALIDATION'!I6:I40,"Not tested")`,
      "08 Result = Not tested",
    ],
    [],
    ["Readiness", "Result", "Logic"],
    [
      "Mapping readiness",
      // B6=total … keep cell refs aligned with metric rows above:
      // B6 Total, B9 Unmapped, B13 Required unmapped, B15 Open blockers, B16 Open critical, B17 Passed, B18 Failed
      '=IF(B6=0,"NOT STARTED",IF(B13>0,"BLOCKED",IF(OR(B9>0,B16>0),"NOT READY",IF(OR(B18>0,B15>0,B17=0),"TEST READY","PRODUCTION READY"))))',
      "BLOCKED if required target unmapped > 0; NOT READY if unmapped > 0 or open critical issues; TEST READY if required covered but validation incomplete (no Pass yet) or failed/blocker open; PRODUCTION READY only if required covered, failed tests = 0, open blockers = 0, and at least one Pass. Empty workbook → NOT STARTED (never claims PRODUCTION READY).",
    ],
    [],
    ["Notes"],
    [
      "Replace or clear EXAMPLE rows so dashboard counts reflect your project only. Extend formulas past row 40 if you add more field rows.",
    ],
  ];

  const fieldCols = FIELD_HEADERS.map((h) => ({
    wch: Math.min(28, Math.max(10, h.length + 2)),
  }));
  // Widen key columns
  const widen: Record<number, number> = {
    0: 10,
    1: 18,
    2: 16,
    3: 22,
    4: 16,
    7: 16,
    8: 18,
    10: 18,
    14: 16,
    15: 36,
    18: 14,
    28: 14,
    29: 28,
  };
  for (const [i, w] of Object.entries(widen)) {
    const idx = Number(i);
    if (fieldCols[idx]) fieldCols[idx] = { wch: w };
  }

  return [
    { name: "01_README", aoa: readme, cols: [{ wch: 36 }, { wch: 88 }] },
    { name: "02_PROJECT", aoa: project, cols: [{ wch: 28 }, { wch: 48 }] },
    {
      name: "03_OBJECT_MAP",
      aoa: objectMap,
      cols: [
        { wch: 18 },
        { wch: 18 },
        { wch: 18 },
        { wch: 18 },
        { wch: 10 },
        { wch: 16 },
        { wch: 28 },
        { wch: 14 },
        { wch: 12 },
        { wch: 28 },
      ],
    },
    { name: "04_FIELD_MAP", aoa: fieldMap, cols: fieldCols },
    {
      name: "05_VALUE_MAPS",
      aoa: valueMaps,
      cols: [
        { wch: 14 },
        { wch: 18 },
        { wch: 16 },
        { wch: 18 },
        { wch: 18 },
        { wch: 18 },
        { wch: 16 },
        { wch: 16 },
        { wch: 22 },
        { wch: 12 },
        { wch: 10 },
        { wch: 32 },
      ],
    },
    {
      name: "06_TRANSFORMATIONS",
      aoa: transformations,
      cols: [
        { wch: 12 },
        { wch: 24 },
        { wch: 36 },
        { wch: 22 },
        { wch: 16 },
        { wch: 48 },
        { wch: 12 },
        { wch: 10 },
        { wch: 28 },
      ],
    },
    {
      name: "07_LOOKUPS",
      aoa: lookups,
      cols: [
        { wch: 12 },
        { wch: 20 },
        { wch: 20 },
        { wch: 24 },
        { wch: 22 },
        { wch: 18 },
        { wch: 28 },
        { wch: 12 },
        { wch: 10 },
        { wch: 28 },
      ],
    },
    {
      name: "08_VALIDATION",
      aoa: validation,
      cols: [
        { wch: 10 },
        { wch: 12 },
        { wch: 16 },
        { wch: 16 },
        { wch: 16 },
        { wch: 20 },
        { wch: 22 },
        { wch: 16 },
        { wch: 12 },
        { wch: 12 },
        { wch: 12 },
        { wch: 32 },
      ],
    },
    {
      name: "09_ISSUES_DECISIONS",
      aoa: issues,
      cols: [
        { wch: 10 },
        { wch: 28 },
        { wch: 12 },
        { wch: 10 },
        { wch: 48 },
        { wch: 28 },
        { wch: 12 },
        { wch: 12 },
        { wch: 32 },
      ],
    },
    {
      name: "10_DASHBOARD",
      aoa: dashboard,
      cols: [{ wch: 36 }, { wch: 14 }, { wch: 72 }],
    },
  ];
}

export async function buildCrmFieldMappingXlsxBuffer(): Promise<Buffer> {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();
  const sheets = buildCrmFieldMappingWorkbookAoa();

  for (const s of sheets) {
    const ws = XLSX.utils.aoa_to_sheet(
      s.aoa.map((row) =>
        row.map((cell) =>
          typeof cell === "string" && cell.startsWith("=") ? null : cell,
        ),
      ),
    );
    if (s.cols) ws["!cols"] = s.cols;

    // Write formulas explicitly (SheetJS needs { f } cells; avoid stripping on write)
    s.aoa.forEach((row, r) => {
      row.forEach((value, c) => {
        if (typeof value === "string" && value.startsWith("=")) {
          const addr = XLSX.utils.encode_cell({ r, c });
          ws[addr] = { t: "n", f: value.slice(1), v: 0 };
        }
      });
    });

    // Ensure !ref covers formula cells
    const range = XLSX.utils.decode_range(ws["!ref"] ?? "A1");
    s.aoa.forEach((row, r) => {
      range.e.r = Math.max(range.e.r, r);
      range.e.c = Math.max(range.e.c, row.length - 1);
    });
    ws["!ref"] = XLSX.utils.encode_range(range);

    if (s.name === "04_FIELD_MAP") {
      // Header Excel row 5 → A5 through last header col; filter through data last row
      const lastCol = XLSX.utils.encode_col(FIELD_HEADERS.length - 1);
      ws["!autofilter"] = {
        ref: `A5:${lastCol}${FIELD_DATA_LAST}`,
      };
    }

    XLSX.utils.book_append_sheet(wb, ws, s.name);
  }

  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}
